void tracks_ByType()
{
//=========Macro generated from canvas: c/c
//=========  (Tue Nov  7 09:20:53 2023) by ROOT version 6.12/06
   TCanvas *c = new TCanvas("c", "c",0,0,800,600);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: p_legend
   TPad *p_legend = new TPad("p_legend", "p_legend",0,0.85,1,1);
   p_legend->Draw();
   p_legend->cd();
   p_legend->Range(0,0,1,1);
   p_legend->SetFillColor(0);
   p_legend->SetBorderMode(0);
   p_legend->SetBorderSize(2);
   p_legend->SetBottomMargin(0);
   p_legend->SetFrameBorderMode(0);
   
   TLegend *leg = new TLegend(0.1,0,0.9,1,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("h_ByType_Signal","Signal","F");
   entry->SetFillColor(8);
   entry->SetFillStyle(1001);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_ByType_OtherNu","Other #nu","F");
   entry->SetFillColor(38);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_ByType_Dirt","Dirt","F");
   entry->SetFillColor(30);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_ByType_EXT","Cosmic","F");
   entry->SetFillColor(15);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   p_legend->Modified();
   c->cd();
  
// ------------>Primitives in pad: p_plot
   TPad *p_plot = new TPad("p_plot", "p_plot",0,0,1,0.85);
   p_plot->Draw();
   p_plot->cd();
   p_plot->Range(-1.25,-0.2895698,11.25,2.606128);
   p_plot->SetFillColor(0);
   p_plot->SetBorderMode(0);
   p_plot->SetBorderSize(2);
   p_plot->SetTopMargin(0.01);
   p_plot->SetFrameBorderMode(0);
   p_plot->SetFrameBorderMode(0);
   
   TH1D *h_errors__1 = new TH1D("h_errors__1","",10,0,10);
   h_errors__1->SetBinContent(1,0.1092428);
   h_errors__1->SetBinContent(2,0.5462138);
   h_errors__1->SetBinContent(3,0.4369711);
   h_errors__1->SetBinContent(4,1.638641);
   h_errors__1->SetBinContent(5,0.8739421);
   h_errors__1->SetBinContent(6,0.9831849);
   h_errors__1->SetBinContent(7,0.3277283);
   h_errors__1->SetBinContent(9,0.2184855);
   h_errors__1->SetBinContent(10,0.1092428);
   h_errors__1->SetBinError(1,0.1092428);
   h_errors__1->SetBinError(2,0.2442742);
   h_errors__1->SetBinError(3,0.2184855);
   h_errors__1->SetBinError(4,0.4230954);
   h_errors__1->SetBinError(5,0.3089852);
   h_errors__1->SetBinError(6,0.3277283);
   h_errors__1->SetBinError(7,0.189214);
   h_errors__1->SetBinError(9,0.1544926);
   h_errors__1->SetBinError(10,0.1092428);
   h_errors__1->SetMinimum(0);
   h_errors__1->SetMaximum(2.577171);
   h_errors__1->SetEntries(48);
   h_errors__1->SetStats(0);
   h_errors__1->SetFillColor(1);
   h_errors__1->SetFillStyle(3253);

   ci = TColor::GetColor("#000099");
   h_errors__1->SetLineColor(ci);
   h_errors__1->GetXaxis()->SetTitle("Tracks");
   h_errors__1->GetXaxis()->SetLabelFont(42);
   h_errors__1->GetXaxis()->SetLabelSize(0.045);
   h_errors__1->GetXaxis()->SetTitleSize(0.05);
   h_errors__1->GetXaxis()->SetTitleOffset(0.93);
   h_errors__1->GetXaxis()->SetTitleFont(42);
   h_errors__1->GetYaxis()->SetTitle("Events");
   h_errors__1->GetYaxis()->SetLabelFont(42);
   h_errors__1->GetYaxis()->SetLabelSize(0.045);
   h_errors__1->GetYaxis()->SetTitleSize(0.05);
   h_errors__1->GetYaxis()->SetTitleOffset(1.06);
   h_errors__1->GetYaxis()->SetTitleFont(42);
   h_errors__1->GetZaxis()->SetLabelFont(42);
   h_errors__1->GetZaxis()->SetLabelSize(0.035);
   h_errors__1->GetZaxis()->SetTitleSize(0.035);
   h_errors__1->GetZaxis()->SetTitleFont(42);
   h_errors__1->Draw("E2");
   
   THStack *hs = new THStack();
   hs->SetName("hs");
   hs->SetTitle("");
   
   TH1F *hs_stack_1 = new TH1F("hs_stack_1","",10,0,10);
   hs_stack_1->SetMinimum(0);
   hs_stack_1->SetMaximum(2.164824);
   hs_stack_1->SetDirectory(0);
   hs_stack_1->SetStats(0);

   ci = TColor::GetColor("#000099");
   hs_stack_1->SetLineColor(ci);
   hs_stack_1->GetXaxis()->SetLabelFont(42);
   hs_stack_1->GetXaxis()->SetLabelSize(0.035);
   hs_stack_1->GetXaxis()->SetTitleSize(0.035);
   hs_stack_1->GetXaxis()->SetTitleFont(42);
   hs_stack_1->GetYaxis()->SetLabelFont(42);
   hs_stack_1->GetYaxis()->SetLabelSize(0.035);
   hs_stack_1->GetYaxis()->SetTitleSize(0.035);
   hs_stack_1->GetYaxis()->SetTitleOffset(0);
   hs_stack_1->GetYaxis()->SetTitleFont(42);
   hs_stack_1->GetZaxis()->SetLabelFont(42);
   hs_stack_1->GetZaxis()->SetLabelSize(0.035);
   hs_stack_1->GetZaxis()->SetTitleSize(0.035);
   hs_stack_1->GetZaxis()->SetTitleFont(42);
   hs->SetHistogram(hs_stack_1);
   
   
   TH1D *h_ByType_Signal_stack_1 = new TH1D("h_ByType_Signal_stack_1","",10,0,10);
   h_ByType_Signal_stack_1->SetBinContent(1,0.1092428);
   h_ByType_Signal_stack_1->SetBinContent(2,0.5462138);
   h_ByType_Signal_stack_1->SetBinContent(3,0.4369711);
   h_ByType_Signal_stack_1->SetBinContent(4,1.638641);
   h_ByType_Signal_stack_1->SetBinContent(5,0.8739421);
   h_ByType_Signal_stack_1->SetBinContent(6,0.9831849);
   h_ByType_Signal_stack_1->SetBinContent(7,0.3277283);
   h_ByType_Signal_stack_1->SetBinContent(9,0.2184855);
   h_ByType_Signal_stack_1->SetBinContent(10,0.1092428);
   h_ByType_Signal_stack_1->SetBinError(1,0.1092428);
   h_ByType_Signal_stack_1->SetBinError(2,0.2442742);
   h_ByType_Signal_stack_1->SetBinError(3,0.2184855);
   h_ByType_Signal_stack_1->SetBinError(4,0.4230954);
   h_ByType_Signal_stack_1->SetBinError(5,0.3089852);
   h_ByType_Signal_stack_1->SetBinError(6,0.3277283);
   h_ByType_Signal_stack_1->SetBinError(7,0.189214);
   h_ByType_Signal_stack_1->SetBinError(9,0.1544926);
   h_ByType_Signal_stack_1->SetBinError(10,0.1092428);
   h_ByType_Signal_stack_1->SetEntries(48);
   h_ByType_Signal_stack_1->SetFillColor(8);

   ci = TColor::GetColor("#000099");
   h_ByType_Signal_stack_1->SetLineColor(ci);
   h_ByType_Signal_stack_1->GetXaxis()->SetTitle("Tracks");
   h_ByType_Signal_stack_1->GetXaxis()->SetLabelFont(42);
   h_ByType_Signal_stack_1->GetXaxis()->SetLabelSize(0.035);
   h_ByType_Signal_stack_1->GetXaxis()->SetTitleSize(0.035);
   h_ByType_Signal_stack_1->GetXaxis()->SetTitleFont(42);
   h_ByType_Signal_stack_1->GetYaxis()->SetTitle("Events");
   h_ByType_Signal_stack_1->GetYaxis()->SetLabelFont(42);
   h_ByType_Signal_stack_1->GetYaxis()->SetLabelSize(0.035);
   h_ByType_Signal_stack_1->GetYaxis()->SetTitleSize(0.035);
   h_ByType_Signal_stack_1->GetYaxis()->SetTitleOffset(0);
   h_ByType_Signal_stack_1->GetYaxis()->SetTitleFont(42);
   h_ByType_Signal_stack_1->GetZaxis()->SetLabelFont(42);
   h_ByType_Signal_stack_1->GetZaxis()->SetLabelSize(0.035);
   h_ByType_Signal_stack_1->GetZaxis()->SetTitleSize(0.035);
   h_ByType_Signal_stack_1->GetZaxis()->SetTitleFont(42);
   hs->Add(h_ByType_Signal_stack_1,"HIST");
   
   TH1D *h_ByType_OtherNu_stack_2 = new TH1D("h_ByType_OtherNu_stack_2","",10,0,10);
   h_ByType_OtherNu_stack_2->SetFillColor(38);

   ci = TColor::GetColor("#000099");
   h_ByType_OtherNu_stack_2->SetLineColor(ci);
   h_ByType_OtherNu_stack_2->GetXaxis()->SetTitle("Tracks");
   h_ByType_OtherNu_stack_2->GetXaxis()->SetLabelFont(42);
   h_ByType_OtherNu_stack_2->GetXaxis()->SetLabelSize(0.035);
   h_ByType_OtherNu_stack_2->GetXaxis()->SetTitleSize(0.035);
   h_ByType_OtherNu_stack_2->GetXaxis()->SetTitleFont(42);
   h_ByType_OtherNu_stack_2->GetYaxis()->SetTitle("Events");
   h_ByType_OtherNu_stack_2->GetYaxis()->SetLabelFont(42);
   h_ByType_OtherNu_stack_2->GetYaxis()->SetLabelSize(0.035);
   h_ByType_OtherNu_stack_2->GetYaxis()->SetTitleSize(0.035);
   h_ByType_OtherNu_stack_2->GetYaxis()->SetTitleOffset(0);
   h_ByType_OtherNu_stack_2->GetYaxis()->SetTitleFont(42);
   h_ByType_OtherNu_stack_2->GetZaxis()->SetLabelFont(42);
   h_ByType_OtherNu_stack_2->GetZaxis()->SetLabelSize(0.035);
   h_ByType_OtherNu_stack_2->GetZaxis()->SetTitleSize(0.035);
   h_ByType_OtherNu_stack_2->GetZaxis()->SetTitleFont(42);
   hs->Add(h_ByType_OtherNu_stack_2,"HIST");
   
   TH1D *h_ByType_Dirt_stack_3 = new TH1D("h_ByType_Dirt_stack_3","",10,0,10);
   h_ByType_Dirt_stack_3->SetFillColor(30);

   ci = TColor::GetColor("#000099");
   h_ByType_Dirt_stack_3->SetLineColor(ci);
   h_ByType_Dirt_stack_3->GetXaxis()->SetTitle("Tracks");
   h_ByType_Dirt_stack_3->GetXaxis()->SetLabelFont(42);
   h_ByType_Dirt_stack_3->GetXaxis()->SetLabelSize(0.035);
   h_ByType_Dirt_stack_3->GetXaxis()->SetTitleSize(0.035);
   h_ByType_Dirt_stack_3->GetXaxis()->SetTitleFont(42);
   h_ByType_Dirt_stack_3->GetYaxis()->SetTitle("Events");
   h_ByType_Dirt_stack_3->GetYaxis()->SetLabelFont(42);
   h_ByType_Dirt_stack_3->GetYaxis()->SetLabelSize(0.035);
   h_ByType_Dirt_stack_3->GetYaxis()->SetTitleSize(0.035);
   h_ByType_Dirt_stack_3->GetYaxis()->SetTitleOffset(0);
   h_ByType_Dirt_stack_3->GetYaxis()->SetTitleFont(42);
   h_ByType_Dirt_stack_3->GetZaxis()->SetLabelFont(42);
   h_ByType_Dirt_stack_3->GetZaxis()->SetLabelSize(0.035);
   h_ByType_Dirt_stack_3->GetZaxis()->SetTitleSize(0.035);
   h_ByType_Dirt_stack_3->GetZaxis()->SetTitleFont(42);
   hs->Add(h_ByType_Dirt_stack_3,"HIST");
   
   TH1D *h_ByType_EXT_stack_4 = new TH1D("h_ByType_EXT_stack_4","",10,0,10);
   h_ByType_EXT_stack_4->SetFillColor(15);

   ci = TColor::GetColor("#000099");
   h_ByType_EXT_stack_4->SetLineColor(ci);
   h_ByType_EXT_stack_4->GetXaxis()->SetTitle("Tracks");
   h_ByType_EXT_stack_4->GetXaxis()->SetLabelFont(42);
   h_ByType_EXT_stack_4->GetXaxis()->SetLabelSize(0.035);
   h_ByType_EXT_stack_4->GetXaxis()->SetTitleSize(0.035);
   h_ByType_EXT_stack_4->GetXaxis()->SetTitleFont(42);
   h_ByType_EXT_stack_4->GetYaxis()->SetTitle("Events");
   h_ByType_EXT_stack_4->GetYaxis()->SetLabelFont(42);
   h_ByType_EXT_stack_4->GetYaxis()->SetLabelSize(0.035);
   h_ByType_EXT_stack_4->GetYaxis()->SetTitleSize(0.035);
   h_ByType_EXT_stack_4->GetYaxis()->SetTitleOffset(0);
   h_ByType_EXT_stack_4->GetYaxis()->SetTitleFont(42);
   h_ByType_EXT_stack_4->GetZaxis()->SetLabelFont(42);
   h_ByType_EXT_stack_4->GetZaxis()->SetLabelSize(0.035);
   h_ByType_EXT_stack_4->GetZaxis()->SetTitleSize(0.035);
   h_ByType_EXT_stack_4->GetZaxis()->SetTitleFont(42);
   hs->Add(h_ByType_EXT_stack_4,"HIST");
   hs->Draw("hist same");
   
   TH1D *h_errors__2 = new TH1D("h_errors__2","",10,0,10);
   h_errors__2->SetBinContent(1,0.1092428);
   h_errors__2->SetBinContent(2,0.5462138);
   h_errors__2->SetBinContent(3,0.4369711);
   h_errors__2->SetBinContent(4,1.638641);
   h_errors__2->SetBinContent(5,0.8739421);
   h_errors__2->SetBinContent(6,0.9831849);
   h_errors__2->SetBinContent(7,0.3277283);
   h_errors__2->SetBinContent(9,0.2184855);
   h_errors__2->SetBinContent(10,0.1092428);
   h_errors__2->SetBinError(1,0.1092428);
   h_errors__2->SetBinError(2,0.2442742);
   h_errors__2->SetBinError(3,0.2184855);
   h_errors__2->SetBinError(4,0.4230954);
   h_errors__2->SetBinError(5,0.3089852);
   h_errors__2->SetBinError(6,0.3277283);
   h_errors__2->SetBinError(7,0.189214);
   h_errors__2->SetBinError(9,0.1544926);
   h_errors__2->SetBinError(10,0.1092428);
   h_errors__2->SetMinimum(0);
   h_errors__2->SetMaximum(2.577171);
   h_errors__2->SetEntries(48);
   h_errors__2->SetStats(0);
   h_errors__2->SetFillColor(1);
   h_errors__2->SetFillStyle(3253);

   ci = TColor::GetColor("#000099");
   h_errors__2->SetLineColor(ci);
   h_errors__2->GetXaxis()->SetTitle("Tracks");
   h_errors__2->GetXaxis()->SetLabelFont(42);
   h_errors__2->GetXaxis()->SetLabelSize(0.045);
   h_errors__2->GetXaxis()->SetTitleSize(0.05);
   h_errors__2->GetXaxis()->SetTitleOffset(0.93);
   h_errors__2->GetXaxis()->SetTitleFont(42);
   h_errors__2->GetYaxis()->SetTitle("Events");
   h_errors__2->GetYaxis()->SetLabelFont(42);
   h_errors__2->GetYaxis()->SetLabelSize(0.045);
   h_errors__2->GetYaxis()->SetTitleSize(0.05);
   h_errors__2->GetYaxis()->SetTitleOffset(1.06);
   h_errors__2->GetYaxis()->SetTitleFont(42);
   h_errors__2->GetZaxis()->SetLabelFont(42);
   h_errors__2->GetZaxis()->SetLabelSize(0.035);
   h_errors__2->GetZaxis()->SetTitleSize(0.035);
   h_errors__2->GetZaxis()->SetTitleFont(42);
   h_errors__2->Draw("E2 same");
   
   TH1D *h_errors_copy__3 = new TH1D("h_errors_copy__3","",10,0,10);
   h_errors_copy__3->SetBinContent(1,0.1092428);
   h_errors_copy__3->SetBinContent(2,0.5462138);
   h_errors_copy__3->SetBinContent(3,0.4369711);
   h_errors_copy__3->SetBinContent(4,1.638641);
   h_errors_copy__3->SetBinContent(5,0.8739421);
   h_errors_copy__3->SetBinContent(6,0.9831849);
   h_errors_copy__3->SetBinContent(7,0.3277283);
   h_errors_copy__3->SetBinContent(9,0.2184855);
   h_errors_copy__3->SetBinContent(10,0.1092428);
   h_errors_copy__3->SetBinError(1,0.1092428);
   h_errors_copy__3->SetBinError(2,0.2442742);
   h_errors_copy__3->SetBinError(3,0.2184855);
   h_errors_copy__3->SetBinError(4,0.4230954);
   h_errors_copy__3->SetBinError(5,0.3089852);
   h_errors_copy__3->SetBinError(6,0.3277283);
   h_errors_copy__3->SetBinError(7,0.189214);
   h_errors_copy__3->SetBinError(9,0.1544926);
   h_errors_copy__3->SetBinError(10,0.1092428);
   h_errors_copy__3->SetMinimum(0);
   h_errors_copy__3->SetMaximum(2.577171);
   h_errors_copy__3->SetEntries(48);
   h_errors_copy__3->SetDirectory(0);
   h_errors_copy__3->SetStats(0);
   h_errors_copy__3->SetFillColor(1);
   h_errors_copy__3->SetFillStyle(3253);

   ci = TColor::GetColor("#000099");
   h_errors_copy__3->SetLineColor(ci);
   h_errors_copy__3->GetXaxis()->SetTitle("Tracks");
   h_errors_copy__3->GetXaxis()->SetLabelFont(42);
   h_errors_copy__3->GetXaxis()->SetLabelSize(0.045);
   h_errors_copy__3->GetXaxis()->SetTitleSize(0.05);
   h_errors_copy__3->GetXaxis()->SetTitleOffset(0.93);
   h_errors_copy__3->GetXaxis()->SetTitleFont(42);
   h_errors_copy__3->GetYaxis()->SetTitle("Events");
   h_errors_copy__3->GetYaxis()->SetLabelFont(42);
   h_errors_copy__3->GetYaxis()->SetLabelSize(0.045);
   h_errors_copy__3->GetYaxis()->SetTitleSize(0.05);
   h_errors_copy__3->GetYaxis()->SetTitleOffset(1.06);
   h_errors_copy__3->GetYaxis()->SetTitleFont(42);
   h_errors_copy__3->GetZaxis()->SetLabelFont(42);
   h_errors_copy__3->GetZaxis()->SetLabelSize(0.035);
   h_errors_copy__3->GetZaxis()->SetTitleSize(0.035);
   h_errors_copy__3->GetZaxis()->SetTitleFont(42);
   h_errors_copy__3->Draw("sameaxis");
   
   leg = new TLegend(0.54,0.815,0.885,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(32);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("NULL","NuMI FHC, 10.0 #times 10^{20} POT","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   leg = new TLegend(0.45,0.9,0.89,0.985,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(32);
   leg->SetTextFont(62);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("NULL","MicroBooNE Simulation, Preliminary","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   p_plot->Modified();
   c->cd();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
