void background_rhc_shower_multi_ByPureKaonType()
{
//=========Macro generated from canvas: c/c
//=========  (Wed Feb 14 06:00:57 2024) by ROOT version 6.12/06
   TCanvas *c = new TCanvas("c", "c",0,0,800,600);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: p_legend
   TPad *p_legend = new TPad("p_legend", "p_legend",0,0.85,1,1);
   p_legend->Draw();
   p_legend->cd();
   p_legend->Range(0,0,1,1);
   p_legend->SetFillColor(0);
   p_legend->SetBorderMode(0);
   p_legend->SetBorderSize(2);
   p_legend->SetBottomMargin(0);
   p_legend->SetFrameBorderMode(0);
   
   TLegend *leg = new TLegend(0.1,0,0.9,1,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaon","#nu_{#mu}CCK^{0}0#pi","F");

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaonMultiPion","#nu_{#mu}CCK^{0}N#pi","F");

   ci = TColor::GetColor("#00cc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaonHyperon","#nu_{#mu}CCK^{0}Y0#pi","F");

   ci = TColor::GetColor("#009900");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaonHyperonMultiPion","#nu_{#mu}CCK^{0}YN#pi","F");

   ci = TColor::GetColor("#006600");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonOtherNuMuCC","Other #nu_{#mu}CC","F");
   entry->SetFillColor(30);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonNuECC","#nu_{e}CC","F");

   ci = TColor::GetColor("#cc33ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonNC","NC","F");

   ci = TColor::GetColor("#ffcc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonOutFV","Out FV","F");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonBeamOff","Beam-Off","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3004);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonOther","Other","F");

   ci = TColor::GetColor("#cc0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   p_legend->Modified();
   c->cd();
  
// ------------>Primitives in pad: p_plot
   TPad *p_plot = new TPad("p_plot", "p_plot",0,0,1,0.85);
   p_plot->Draw();
   p_plot->cd();
   p_plot->Range(-0.625,-37894.14,5.625,341047.2);
   p_plot->SetFillColor(0);
   p_plot->SetBorderMode(0);
   p_plot->SetBorderSize(2);
   p_plot->SetTopMargin(0.01);
   p_plot->SetFrameBorderMode(0);
   p_plot->SetFrameBorderMode(0);
   
   TH1D *h_errors__1 = new TH1D("h_errors__1","",5,0,5);
   h_errors__1->SetBinContent(1,268132.6);
   h_errors__1->SetBinContent(2,122409.5);
   h_errors__1->SetBinContent(3,33310.82);
   h_errors__1->SetBinContent(4,9784.821);
   h_errors__1->SetBinContent(5,3352.917);
   h_errors__1->SetBinContent(6,1554.054);
   h_errors__1->SetBinError(1,1673.67);
   h_errors__1->SetBinError(2,1123.994);
   h_errors__1->SetBinError(3,527.6122);
   h_errors__1->SetBinError(4,263.2503);
   h_errors__1->SetBinError(5,140.5729);
   h_errors__1->SetBinError(6,92.94425);
   h_errors__1->SetMinimum(0);
   h_errors__1->SetMaximum(337257.8);
   h_errors__1->SetEntries(109855);
   h_errors__1->SetStats(0);
   h_errors__1->SetFillColor(1);
   h_errors__1->SetFillStyle(3253);

   ci = TColor::GetColor("#000099");
   h_errors__1->SetLineColor(ci);
   h_errors__1->GetXaxis()->SetTitle("Shower Multiplicity");
   h_errors__1->GetXaxis()->SetLabelFont(42);
   h_errors__1->GetXaxis()->SetLabelSize(0.045);
   h_errors__1->GetXaxis()->SetTitleSize(0.05);
   h_errors__1->GetXaxis()->SetTitleOffset(0.93);
   h_errors__1->GetXaxis()->SetTitleFont(42);
   h_errors__1->GetYaxis()->SetTitle(" Events/bin");
   h_errors__1->GetYaxis()->SetLabelFont(42);
   h_errors__1->GetYaxis()->SetLabelSize(0.045);
   h_errors__1->GetYaxis()->SetTitleSize(0.05);
   h_errors__1->GetYaxis()->SetTitleOffset(1.06);
   h_errors__1->GetYaxis()->SetTitleFont(42);
   h_errors__1->GetZaxis()->SetLabelFont(42);
   h_errors__1->GetZaxis()->SetLabelSize(0.035);
   h_errors__1->GetZaxis()->SetTitleSize(0.035);
   h_errors__1->GetZaxis()->SetTitleFont(42);
   h_errors__1->Draw("E2");
   
   THStack *hs = new THStack();
   hs->SetName("hs");
   hs->SetTitle("");
   
   TH1F *hs_stack_1 = new TH1F("hs_stack_1","",5,0,5);
   hs_stack_1->SetMinimum(0);
   hs_stack_1->SetMaximum(281539.2);
   hs_stack_1->SetDirectory(0);
   hs_stack_1->SetStats(0);

   ci = TColor::GetColor("#000099");
   hs_stack_1->SetLineColor(ci);
   hs_stack_1->GetXaxis()->SetLabelFont(42);
   hs_stack_1->GetXaxis()->SetLabelSize(0.035);
   hs_stack_1->GetXaxis()->SetTitleSize(0.035);
   hs_stack_1->GetXaxis()->SetTitleFont(42);
   hs_stack_1->GetYaxis()->SetLabelFont(42);
   hs_stack_1->GetYaxis()->SetLabelSize(0.035);
   hs_stack_1->GetYaxis()->SetTitleSize(0.035);
   hs_stack_1->GetYaxis()->SetTitleOffset(0);
   hs_stack_1->GetYaxis()->SetTitleFont(42);
   hs_stack_1->GetZaxis()->SetLabelFont(42);
   hs_stack_1->GetZaxis()->SetLabelSize(0.035);
   hs_stack_1->GetZaxis()->SetTitleSize(0.035);
   hs_stack_1->GetZaxis()->SetTitleFont(42);
   hs->SetHistogram(hs_stack_1);
   
   
   TH1D *h_PureKaonSignalNuMuCCKaon_stack_1 = new TH1D("h_PureKaonSignalNuMuCCKaon_stack_1","",5,0,5);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(1,1.06857);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(2,1.997327);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(3,1.488009);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(4,0.9986636);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(5,0.4693719);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(6,0.2097194);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(1,0.1033026);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(2,0.1412324);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(3,0.1219024);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(4,0.09986636);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(5,0.06846493);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(6,0.04576451);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetEntries(629);

   ci = TColor::GetColor("#00ff00");
   h_PureKaonSignalNuMuCCKaon_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaon_stack_1->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetTitle("Shower Multiplicity");
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaon_stack_1,"HIST");
   
   TH1D *h_PureKaonSignalNuMuCCKaonMultiPion_stack_2 = new TH1D("h_PureKaonSignalNuMuCCKaonMultiPion_stack_2","",5,0,5);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(1,0.7589843);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(2,5.818306);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(3,6.527357);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(4,5.698467);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(5,1.677755);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(6,1.737675);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(1,0.08706147);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(2,3.126224);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(3,3.127357);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(4,3.126033);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(5,0.1294416);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(6,0.1317328);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetEntries(1398);

   ci = TColor::GetColor("#00cc00");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetTitle("Shower Multiplicity");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaonMultiPion_stack_2,"HIST");
   
   TH1D *h_PureKaonSignalNuMuCCKaonHyperon_stack_3 = new TH1D("h_PureKaonSignalNuMuCCKaonHyperon_stack_3","",5,0,5);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(1,6.567304);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(2,19.53822);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(3,13.03474);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(4,3.764962);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(5,4.420177);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(6,0.8388774);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(1,3.12742);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(2,6.249465);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(3,4.422727);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(4,0.1939054);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(5,3.12399);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(6,0.09152903);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetEntries(2330);

   ci = TColor::GetColor("#009900");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetTitle("Shower Multiplicity");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaonHyperon_stack_3,"HIST");
   
   TH1D *h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4 = new TH1D("h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4","",5,0,5);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(1,13.31046);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(2,33.21819);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(3,27.5475);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(4,24.39173);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(5,28.94391);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(6,5.43273);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(1,5.410956);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(2,8.266677);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(3,6.255861);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(4,6.253342);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(5,8.264095);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(6,0.2329264);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetEntries(5518);

   ci = TColor::GetColor("#006600");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetTitle("Shower Multiplicity");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4,"HIST");
   
   TH1D *h_PureKaonOtherNuMuCC_stack_5 = new TH1D("h_PureKaonOtherNuMuCC_stack_5","",5,0,5);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(1,49608.26);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(2,21110.29);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(3,9530.423);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(4,3672.593);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(5,1581.742);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(6,848.8707);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(1,393.5099);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(2,256.6247);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(3,172.3009);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(4,106.7868);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(5,69.94864);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(6,51.014);
   h_PureKaonOtherNuMuCC_stack_5->SetEntries(37518);
   h_PureKaonOtherNuMuCC_stack_5->SetFillColor(30);

   ci = TColor::GetColor("#000099");
   h_PureKaonOtherNuMuCC_stack_5->SetLineColor(ci);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetTitle("Shower Multiplicity");
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetLabelFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetTitleFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetLabelFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitleOffset(0);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitleFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetLabelFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonOtherNuMuCC_stack_5,"HIST");
   
   TH1D *h_PureKaonNuECC_stack_6 = new TH1D("h_PureKaonNuECC_stack_6","",5,0,5);
   h_PureKaonNuECC_stack_6->SetBinContent(1,340.4984);
   h_PureKaonNuECC_stack_6->SetBinContent(2,1942.61);
   h_PureKaonNuECC_stack_6->SetBinContent(3,909.6056);
   h_PureKaonNuECC_stack_6->SetBinContent(4,413.1813);
   h_PureKaonNuECC_stack_6->SetBinContent(5,156.9046);
   h_PureKaonNuECC_stack_6->SetBinContent(6,44.71545);
   h_PureKaonNuECC_stack_6->SetBinError(1,32.59378);
   h_PureKaonNuECC_stack_6->SetBinError(2,77.86037);
   h_PureKaonNuECC_stack_6->SetBinError(3,53.25598);
   h_PureKaonNuECC_stack_6->SetBinError(4,35.86822);
   h_PureKaonNuECC_stack_6->SetBinError(5,22.07545);
   h_PureKaonNuECC_stack_6->SetBinError(6,11.68157);
   h_PureKaonNuECC_stack_6->SetEntries(1742);

   ci = TColor::GetColor("#cc33ff");
   h_PureKaonNuECC_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonNuECC_stack_6->SetLineColor(ci);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetTitle("Shower Multiplicity");
   h_PureKaonNuECC_stack_6->GetXaxis()->SetLabelFont(42);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetTitleFont(42);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonNuECC_stack_6->GetYaxis()->SetLabelFont(42);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitleOffset(0);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitleFont(42);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetLabelFont(42);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonNuECC_stack_6,"HIST");
   
   TH1D *h_PureKaonNC_stack_7 = new TH1D("h_PureKaonNC_stack_7","",5,0,5);
   h_PureKaonNC_stack_7->SetBinContent(1,9154.563);
   h_PureKaonNC_stack_7->SetBinContent(2,5615.972);
   h_PureKaonNC_stack_7->SetBinContent(3,3451.261);
   h_PureKaonNC_stack_7->SetBinContent(4,1192.185);
   h_PureKaonNC_stack_7->SetBinContent(5,488.039);
   h_PureKaonNC_stack_7->SetBinContent(6,205.3989);
   h_PureKaonNC_stack_7->SetBinError(1,168.9591);
   h_PureKaonNC_stack_7->SetBinError(2,132.1578);
   h_PureKaonNC_stack_7->SetBinError(3,103.4491);
   h_PureKaonNC_stack_7->SetBinError(4,60.53768);
   h_PureKaonNC_stack_7->SetBinError(5,38.61729);
   h_PureKaonNC_stack_7->SetBinError(6,24.78118);
   h_PureKaonNC_stack_7->SetEntries(16020);

   ci = TColor::GetColor("#ffcc00");
   h_PureKaonNC_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonNC_stack_7->SetLineColor(ci);
   h_PureKaonNC_stack_7->GetXaxis()->SetTitle("Shower Multiplicity");
   h_PureKaonNC_stack_7->GetXaxis()->SetLabelFont(42);
   h_PureKaonNC_stack_7->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonNC_stack_7->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonNC_stack_7->GetXaxis()->SetTitleFont(42);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonNC_stack_7->GetYaxis()->SetLabelFont(42);
   h_PureKaonNC_stack_7->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitleOffset(0);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitleFont(42);
   h_PureKaonNC_stack_7->GetZaxis()->SetLabelFont(42);
   h_PureKaonNC_stack_7->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonNC_stack_7->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonNC_stack_7->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonNC_stack_7,"HIST");
   
   TH1D *h_PureKaonOutFV_stack_8 = new TH1D("h_PureKaonOutFV_stack_8","",5,0,5);
   h_PureKaonOutFV_stack_8->SetBinContent(1,15393.84);
   h_PureKaonOutFV_stack_8->SetBinContent(2,7650.106);
   h_PureKaonOutFV_stack_8->SetBinContent(3,2253.019);
   h_PureKaonOutFV_stack_8->SetBinContent(4,692.0841);
   h_PureKaonOutFV_stack_8->SetBinContent(5,189.5319);
   h_PureKaonOutFV_stack_8->SetBinContent(6,85.59994);
   h_PureKaonOutFV_stack_8->SetBinError(1,218.9803);
   h_PureKaonOutFV_stack_8->SetBinError(2,154.3067);
   h_PureKaonOutFV_stack_8->SetBinError(3,83.65401);
   h_PureKaonOutFV_stack_8->SetBinError(4,46.30604);
   h_PureKaonOutFV_stack_8->SetBinError(5,24.1827);
   h_PureKaonOutFV_stack_8->SetBinError(6,16.22235);
   h_PureKaonOutFV_stack_8->SetEntries(16441);

   ci = TColor::GetColor("#cccccc");
   h_PureKaonOutFV_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonOutFV_stack_8->SetLineColor(ci);
   h_PureKaonOutFV_stack_8->GetXaxis()->SetTitle("Shower Multiplicity");
   h_PureKaonOutFV_stack_8->GetXaxis()->SetLabelFont(42);
   h_PureKaonOutFV_stack_8->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonOutFV_stack_8->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonOutFV_stack_8->GetXaxis()->SetTitleFont(42);
   h_PureKaonOutFV_stack_8->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonOutFV_stack_8->GetYaxis()->SetLabelFont(42);
   h_PureKaonOutFV_stack_8->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonOutFV_stack_8->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonOutFV_stack_8->GetYaxis()->SetTitleOffset(0);
   h_PureKaonOutFV_stack_8->GetYaxis()->SetTitleFont(42);
   h_PureKaonOutFV_stack_8->GetZaxis()->SetLabelFont(42);
   h_PureKaonOutFV_stack_8->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonOutFV_stack_8->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonOutFV_stack_8->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonOutFV_stack_8,"HIST");
   
   TH1D *h_PureKaonBeamOff_stack_9 = new TH1D("h_PureKaonBeamOff_stack_9","",5,0,5);
   h_PureKaonBeamOff_stack_9->SetBinContent(1,19417.39);
   h_PureKaonBeamOff_stack_9->SetBinContent(2,7856.034);
   h_PureKaonBeamOff_stack_9->SetBinContent(3,1629.961);
   h_PureKaonBeamOff_stack_9->SetBinContent(4,325.3605);
   h_PureKaonBeamOff_stack_9->SetBinContent(5,66.33563);
   h_PureKaonBeamOff_stack_9->SetBinContent(6,15.7942);
   h_PureKaonBeamOff_stack_9->SetBinError(1,247.6619);
   h_PureKaonBeamOff_stack_9->SetBinError(2,157.5308);
   h_PureKaonBeamOff_stack_9->SetBinError(3,71.75504);
   h_PureKaonBeamOff_stack_9->SetBinError(4,32.05872);
   h_PureKaonBeamOff_stack_9->SetBinError(5,14.47562);
   h_PureKaonBeamOff_stack_9->SetBinError(6,7.06338);
   h_PureKaonBeamOff_stack_9->SetEntries(9328);
   h_PureKaonBeamOff_stack_9->SetFillColor(1);
   h_PureKaonBeamOff_stack_9->SetFillStyle(3004);

   ci = TColor::GetColor("#000099");
   h_PureKaonBeamOff_stack_9->SetLineColor(ci);
   h_PureKaonBeamOff_stack_9->GetXaxis()->SetTitle("Shower Multiplicity");
   h_PureKaonBeamOff_stack_9->GetXaxis()->SetLabelFont(42);
   h_PureKaonBeamOff_stack_9->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonBeamOff_stack_9->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonBeamOff_stack_9->GetXaxis()->SetTitleFont(42);
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetLabelFont(42);
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetTitleOffset(0);
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetTitleFont(42);
   h_PureKaonBeamOff_stack_9->GetZaxis()->SetLabelFont(42);
   h_PureKaonBeamOff_stack_9->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonBeamOff_stack_9->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonBeamOff_stack_9->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonBeamOff_stack_9,"HIST");
   
   TH1D *h_PureKaonOther_stack_10 = new TH1D("h_PureKaonOther_stack_10","",5,0,5);
   h_PureKaonOther_stack_10->SetBinContent(1,174196.3);
   h_PureKaonOther_stack_10->SetBinContent(2,78173.88);
   h_PureKaonOther_stack_10->SetBinContent(3,15487.96);
   h_PureKaonOther_stack_10->SetBinContent(4,3454.563);
   h_PureKaonOther_stack_10->SetBinContent(5,834.8527);
   h_PureKaonOther_stack_10->SetBinContent(6,345.4563);
   h_PureKaonOther_stack_10->SetBinError(1,1583.472);
   h_PureKaonOther_stack_10->SetBinError(2,1060.771);
   h_PureKaonOther_stack_10->SetBinError(3,472.1587);
   h_PureKaonOther_stack_10->SetBinError(4,222.9911);
   h_PureKaonOther_stack_10->SetBinError(5,109.6215);
   h_PureKaonOther_stack_10->SetBinError(6,70.51597);
   h_PureKaonOther_stack_10->SetEntries(18931);

   ci = TColor::GetColor("#cc0000");
   h_PureKaonOther_stack_10->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonOther_stack_10->SetLineColor(ci);
   h_PureKaonOther_stack_10->GetXaxis()->SetTitle("Shower Multiplicity");
   h_PureKaonOther_stack_10->GetXaxis()->SetLabelFont(42);
   h_PureKaonOther_stack_10->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonOther_stack_10->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonOther_stack_10->GetXaxis()->SetTitleFont(42);
   h_PureKaonOther_stack_10->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonOther_stack_10->GetYaxis()->SetLabelFont(42);
   h_PureKaonOther_stack_10->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonOther_stack_10->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonOther_stack_10->GetYaxis()->SetTitleOffset(0);
   h_PureKaonOther_stack_10->GetYaxis()->SetTitleFont(42);
   h_PureKaonOther_stack_10->GetZaxis()->SetLabelFont(42);
   h_PureKaonOther_stack_10->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonOther_stack_10->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonOther_stack_10->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonOther_stack_10,"HIST");
   hs->Draw("hist same");
   
   TH1D *h_errors__2 = new TH1D("h_errors__2","",5,0,5);
   h_errors__2->SetBinContent(1,268132.6);
   h_errors__2->SetBinContent(2,122409.5);
   h_errors__2->SetBinContent(3,33310.82);
   h_errors__2->SetBinContent(4,9784.821);
   h_errors__2->SetBinContent(5,3352.917);
   h_errors__2->SetBinContent(6,1554.054);
   h_errors__2->SetBinError(1,1673.67);
   h_errors__2->SetBinError(2,1123.994);
   h_errors__2->SetBinError(3,527.6122);
   h_errors__2->SetBinError(4,263.2503);
   h_errors__2->SetBinError(5,140.5729);
   h_errors__2->SetBinError(6,92.94425);
   h_errors__2->SetMinimum(0);
   h_errors__2->SetMaximum(337257.8);
   h_errors__2->SetEntries(109855);
   h_errors__2->SetStats(0);
   h_errors__2->SetFillColor(1);
   h_errors__2->SetFillStyle(3253);

   ci = TColor::GetColor("#000099");
   h_errors__2->SetLineColor(ci);
   h_errors__2->GetXaxis()->SetTitle("Shower Multiplicity");
   h_errors__2->GetXaxis()->SetLabelFont(42);
   h_errors__2->GetXaxis()->SetLabelSize(0.045);
   h_errors__2->GetXaxis()->SetTitleSize(0.05);
   h_errors__2->GetXaxis()->SetTitleOffset(0.93);
   h_errors__2->GetXaxis()->SetTitleFont(42);
   h_errors__2->GetYaxis()->SetTitle(" Events/bin");
   h_errors__2->GetYaxis()->SetLabelFont(42);
   h_errors__2->GetYaxis()->SetLabelSize(0.045);
   h_errors__2->GetYaxis()->SetTitleSize(0.05);
   h_errors__2->GetYaxis()->SetTitleOffset(1.06);
   h_errors__2->GetYaxis()->SetTitleFont(42);
   h_errors__2->GetZaxis()->SetLabelFont(42);
   h_errors__2->GetZaxis()->SetLabelSize(0.035);
   h_errors__2->GetZaxis()->SetTitleSize(0.035);
   h_errors__2->GetZaxis()->SetTitleFont(42);
   h_errors__2->Draw("E2 same");
   
   TH1D *h_errors_copy__3 = new TH1D("h_errors_copy__3","",5,0,5);
   h_errors_copy__3->SetBinContent(1,268132.6);
   h_errors_copy__3->SetBinContent(2,122409.5);
   h_errors_copy__3->SetBinContent(3,33310.82);
   h_errors_copy__3->SetBinContent(4,9784.821);
   h_errors_copy__3->SetBinContent(5,3352.917);
   h_errors_copy__3->SetBinContent(6,1554.054);
   h_errors_copy__3->SetBinError(1,1673.67);
   h_errors_copy__3->SetBinError(2,1123.994);
   h_errors_copy__3->SetBinError(3,527.6122);
   h_errors_copy__3->SetBinError(4,263.2503);
   h_errors_copy__3->SetBinError(5,140.5729);
   h_errors_copy__3->SetBinError(6,92.94425);
   h_errors_copy__3->SetMinimum(0);
   h_errors_copy__3->SetMaximum(337257.8);
   h_errors_copy__3->SetEntries(109855);
   h_errors_copy__3->SetDirectory(0);
   h_errors_copy__3->SetStats(0);
   h_errors_copy__3->SetFillColor(1);
   h_errors_copy__3->SetFillStyle(3253);

   ci = TColor::GetColor("#000099");
   h_errors_copy__3->SetLineColor(ci);
   h_errors_copy__3->GetXaxis()->SetTitle("Shower Multiplicity");
   h_errors_copy__3->GetXaxis()->SetLabelFont(42);
   h_errors_copy__3->GetXaxis()->SetLabelSize(0.045);
   h_errors_copy__3->GetXaxis()->SetTitleSize(0.05);
   h_errors_copy__3->GetXaxis()->SetTitleOffset(0.93);
   h_errors_copy__3->GetXaxis()->SetTitleFont(42);
   h_errors_copy__3->GetYaxis()->SetTitle(" Events/bin");
   h_errors_copy__3->GetYaxis()->SetLabelFont(42);
   h_errors_copy__3->GetYaxis()->SetLabelSize(0.045);
   h_errors_copy__3->GetYaxis()->SetTitleSize(0.05);
   h_errors_copy__3->GetYaxis()->SetTitleOffset(1.06);
   h_errors_copy__3->GetYaxis()->SetTitleFont(42);
   h_errors_copy__3->GetZaxis()->SetLabelFont(42);
   h_errors_copy__3->GetZaxis()->SetLabelSize(0.035);
   h_errors_copy__3->GetZaxis()->SetTitleSize(0.035);
   h_errors_copy__3->GetZaxis()->SetTitleFont(42);
   h_errors_copy__3->Draw("sameaxis");
   
   leg = new TLegend(0.54,0.815,0.885,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(32);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("NULL","NuMI RHC, 1.5 #times 10^{21} POT","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   leg = new TLegend(0.45,0.9,0.89,0.985,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(32);
   leg->SetTextFont(62);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("NULL","MicroBooNE Simulation, Preliminary","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   p_plot->Modified();
   c->cd();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
