void background_rhc_invariant_mass_ByPureKaonType()
{
//=========Macro generated from canvas: c/c
//=========  (Wed Feb 14 06:38:38 2024) by ROOT version 6.12/06
   TCanvas *c = new TCanvas("c", "c",0,0,800,600);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: p_legend
   TPad *p_legend = new TPad("p_legend", "p_legend",0,0.85,1,1);
   p_legend->Draw();
   p_legend->cd();
   p_legend->Range(0,0,1,1);
   p_legend->SetFillColor(0);
   p_legend->SetBorderMode(0);
   p_legend->SetBorderSize(2);
   p_legend->SetBottomMargin(0);
   p_legend->SetFrameBorderMode(0);
   
   TLegend *leg = new TLegend(0.1,0,0.9,1,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaon","#nu_{#mu}CCK^{0}0#pi","F");

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaonMultiPion","#nu_{#mu}CCK^{0}N#pi","F");

   ci = TColor::GetColor("#00cc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaonHyperon","#nu_{#mu}CCK^{0}Y0#pi","F");

   ci = TColor::GetColor("#009900");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaonHyperonMultiPion","#nu_{#mu}CCK^{0}YN#pi","F");

   ci = TColor::GetColor("#006600");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonOtherNuMuCC","Other #nu_{#mu}CC","F");
   entry->SetFillColor(30);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonNuECC","#nu_{e}CC","F");

   ci = TColor::GetColor("#cc33ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonNC","NC","F");

   ci = TColor::GetColor("#ffcc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonOutFV","Out FV","F");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonBeamOff","Beam-Off","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3004);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonOther","Other","F");

   ci = TColor::GetColor("#cc0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   p_legend->Modified();
   c->cd();
  
// ------------>Primitives in pad: p_plot
   TPad *p_plot = new TPad("p_plot", "p_plot",0,0,1,0.85);
   p_plot->Draw();
   p_plot->cd();
   p_plot->Range(0.08749999,-53.12725,1.2125,478.1453);
   p_plot->SetFillColor(0);
   p_plot->SetBorderMode(0);
   p_plot->SetBorderSize(2);
   p_plot->SetTopMargin(0.01);
   p_plot->SetFrameBorderMode(0);
   p_plot->SetFrameBorderMode(0);
   
   TH1D *h_errors__1 = new TH1D("h_errors__1","",9,0.2,1.1);
   h_errors__1->SetBinContent(1,82.29524);
   h_errors__1->SetBinContent(2,345.6715);
   h_errors__1->SetBinContent(3,171.11);
   h_errors__1->SetBinContent(4,129.7748);
   h_errors__1->SetBinContent(5,59.77576);
   h_errors__1->SetBinContent(6,25.19502);
   h_errors__1->SetBinContent(7,15.69945);
   h_errors__1->SetBinContent(8,60.72792);
   h_errors__1->SetBinContent(9,3.141888);
   h_errors__1->SetBinContent(10,1056.354);
   h_errors__1->SetBinError(1,15.92633);
   h_errors__1->SetBinError(2,32.59457);
   h_errors__1->SetBinError(3,22.94184);
   h_errors__1->SetBinError(4,26.95368);
   h_errors__1->SetBinError(5,13.60828);
   h_errors__1->SetBinError(6,8.830232);
   h_errors__1->SetBinError(7,6.980877);
   h_errors__1->SetBinError(8,28.95681);
   h_errors__1->SetBinError(9,3.121946);
   h_errors__1->SetBinError(10,71.05301);
   h_errors__1->SetMinimum(0);
   h_errors__1->SetMaximum(472.8326);
   h_errors__1->SetEntries(2824);
   h_errors__1->SetStats(0);
   h_errors__1->SetFillColor(1);
   h_errors__1->SetFillStyle(3253);

   ci = TColor::GetColor("#000099");
   h_errors__1->SetLineColor(ci);
   h_errors__1->GetXaxis()->SetTitle("Invariant Mass (GeV)");
   h_errors__1->GetXaxis()->SetLabelFont(42);
   h_errors__1->GetXaxis()->SetLabelSize(0.045);
   h_errors__1->GetXaxis()->SetTitleSize(0.05);
   h_errors__1->GetXaxis()->SetTitleOffset(0.93);
   h_errors__1->GetXaxis()->SetTitleFont(42);
   h_errors__1->GetYaxis()->SetTitle("Events/bin");
   h_errors__1->GetYaxis()->SetLabelFont(42);
   h_errors__1->GetYaxis()->SetLabelSize(0.045);
   h_errors__1->GetYaxis()->SetTitleSize(0.05);
   h_errors__1->GetYaxis()->SetTitleOffset(1.06);
   h_errors__1->GetYaxis()->SetTitleFont(42);
   h_errors__1->GetZaxis()->SetLabelFont(42);
   h_errors__1->GetZaxis()->SetLabelSize(0.035);
   h_errors__1->GetZaxis()->SetTitleSize(0.035);
   h_errors__1->GetZaxis()->SetTitleFont(42);
   h_errors__1->Draw("E2");
   
   THStack *hs = new THStack();
   hs->SetName("hs");
   hs->SetTitle("");
   
   TH1F *hs_stack_1 = new TH1F("hs_stack_1","",9,0.2,1.1);
   hs_stack_1->SetMinimum(0);
   hs_stack_1->SetMaximum(362.955);
   hs_stack_1->SetDirectory(0);
   hs_stack_1->SetStats(0);

   ci = TColor::GetColor("#000099");
   hs_stack_1->SetLineColor(ci);
   hs_stack_1->GetXaxis()->SetLabelFont(42);
   hs_stack_1->GetXaxis()->SetLabelSize(0.035);
   hs_stack_1->GetXaxis()->SetTitleSize(0.035);
   hs_stack_1->GetXaxis()->SetTitleFont(42);
   hs_stack_1->GetYaxis()->SetLabelFont(42);
   hs_stack_1->GetYaxis()->SetLabelSize(0.035);
   hs_stack_1->GetYaxis()->SetTitleSize(0.035);
   hs_stack_1->GetYaxis()->SetTitleOffset(0);
   hs_stack_1->GetYaxis()->SetTitleFont(42);
   hs_stack_1->GetZaxis()->SetLabelFont(42);
   hs_stack_1->GetZaxis()->SetLabelSize(0.035);
   hs_stack_1->GetZaxis()->SetTitleSize(0.035);
   hs_stack_1->GetZaxis()->SetTitleFont(42);
   hs->SetHistogram(hs_stack_1);
   
   
   TH1D *h_PureKaonSignalNuMuCCKaon_stack_1 = new TH1D("h_PureKaonSignalNuMuCCKaon_stack_1","",9,0.2,1.1);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(1,0.009986636);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(2,0.109853);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(3,0.05991982);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(4,0.009986636);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(5,0.009986636);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(6,0.009986636);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(10,0.2995991);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(1,0.009986636);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(2,0.03312192);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(3,0.02446216);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(4,0.009986636);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(5,0.009986636);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(6,0.009986636);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(10,0.05469906);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetEntries(52);

   ci = TColor::GetColor("#00ff00");
   h_PureKaonSignalNuMuCCKaon_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaon_stack_1->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetTitle("Invariant Mass (GeV)");
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitle("Events/bin");
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaon_stack_1,"HIST");
   
   TH1D *h_PureKaonSignalNuMuCCKaonMultiPion_stack_2 = new TH1D("h_PureKaonSignalNuMuCCKaonMultiPion_stack_2","",9,0.2,1.1);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(1,0.109853);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(2,0.3195723);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(3,0.1697728);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(4,0.109853);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(5,0.03994654);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(6,0.03994654);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(10,0.7489977);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(1,0.03312192);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(2,0.05649294);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(3,0.04117595);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(4,0.03312192);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(5,0.01997327);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(6,0.01997327);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(10,0.0864868);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetEntries(166);

   ci = TColor::GetColor("#00cc00");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetTitle("Invariant Mass (GeV)");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitle("Events/bin");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaonMultiPion_stack_2,"HIST");
   
   TH1D *h_PureKaonSignalNuMuCCKaonHyperon_stack_3 = new TH1D("h_PureKaonSignalNuMuCCKaonHyperon_stack_3","",9,0.2,1.1);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(1,0.05991982);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(2,0.5592516);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(3,3.471447);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(4,0.109853);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(5,0.02995991);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(6,0.04993318);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(7,0.009986636);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(8,0.009986636);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(10,1.308249);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(1,0.02446216);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(2,0.07473314);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(3,3.122473);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(4,0.03312192);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(5,0.01729736);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(6,0.0223308);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(7,0.009986636);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(8,0.009986636);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(10,0.1143023);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetEntries(250);

   ci = TColor::GetColor("#009900");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetTitle("Invariant Mass (GeV)");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitle("Events/bin");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaonHyperon_stack_3,"HIST");
   
   TH1D *h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4 = new TH1D("h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4","",9,0.2,1.1);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(1,3.541353);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(2,4.609923);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(3,0.8388774);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(4,0.3595189);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(5,0.08987972);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(6,0.03994654);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(7,0.02995991);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(8,0.01997327);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(10,9.469512);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(1,3.122585);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(2,3.124294);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(3,0.09152903);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(4,0.05991982);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(5,0.02995991);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(6,0.01997327);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(7,0.01729736);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(8,0.01412324);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(10,4.4187);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetEntries(657);

   ci = TColor::GetColor("#006600");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetTitle("Invariant Mass (GeV)");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitle("Events/bin");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4,"HIST");
   
   TH1D *h_PureKaonOtherNuMuCC_stack_5 = new TH1D("h_PureKaonOtherNuMuCC_stack_5","",9,0.2,1.1);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(1,68.9218);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(2,282.72);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(3,134.8016);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(4,81.51931);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(5,53.27228);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(6,18.80139);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(7,12.5276);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(8,3.121914);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(9,3.131901);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(10,761.8509);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(1,14.64316);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(2,29.61738);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(3,20.4719);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(4,15.91881);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(5,12.87206);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(6,7.647143);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(7,6.243861);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(8,3.121914);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(9,3.12193);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(10,48.66616);
   h_PureKaonOtherNuMuCC_stack_5->SetEntries(1126);
   h_PureKaonOtherNuMuCC_stack_5->SetFillColor(30);

   ci = TColor::GetColor("#000099");
   h_PureKaonOtherNuMuCC_stack_5->SetLineColor(ci);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetTitle("Invariant Mass (GeV)");
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetLabelFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetTitleFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitle("Events/bin");
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetLabelFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitleOffset(0);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitleFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetLabelFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonOtherNuMuCC_stack_5,"HIST");
   
   TH1D *h_PureKaonNuECC_stack_6 = new TH1D("h_PureKaonNuECC_stack_6","",9,0.2,1.1);
   h_PureKaonNuECC_stack_6->SetBinContent(2,0.06990645);
   h_PureKaonNuECC_stack_6->SetBinContent(3,6.253816);
   h_PureKaonNuECC_stack_6->SetBinContent(4,0.009986636);
   h_PureKaonNuECC_stack_6->SetBinContent(5,0.009986636);
   h_PureKaonNuECC_stack_6->SetBinContent(10,12.5276);
   h_PureKaonNuECC_stack_6->SetBinError(2,0.02642215);
   h_PureKaonNuECC_stack_6->SetBinError(3,4.415065);
   h_PureKaonNuECC_stack_6->SetBinError(4,0.009986636);
   h_PureKaonNuECC_stack_6->SetBinError(5,0.009986636);
   h_PureKaonNuECC_stack_6->SetBinError(10,6.243861);
   h_PureKaonNuECC_stack_6->SetEntries(20);

   ci = TColor::GetColor("#cc33ff");
   h_PureKaonNuECC_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonNuECC_stack_6->SetLineColor(ci);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetTitle("Invariant Mass (GeV)");
   h_PureKaonNuECC_stack_6->GetXaxis()->SetLabelFont(42);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetTitleFont(42);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitle("Events/bin");
   h_PureKaonNuECC_stack_6->GetYaxis()->SetLabelFont(42);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitleOffset(0);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitleFont(42);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetLabelFont(42);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonNuECC_stack_6,"HIST");
   
   TH1D *h_PureKaonNC_stack_7 = new TH1D("h_PureKaonNC_stack_7","",9,0.2,1.1);
   h_PureKaonNC_stack_7->SetBinContent(1,6.443562);
   h_PureKaonNC_stack_7->SetBinContent(2,31.9981);
   h_PureKaonNC_stack_7->SetBinContent(3,19.15093);
   h_PureKaonNC_stack_7->SetBinContent(4,3.171848);
   h_PureKaonNC_stack_7->SetBinContent(5,0.01997327);
   h_PureKaonNC_stack_7->SetBinContent(6,3.131901);
   h_PureKaonNC_stack_7->SetBinContent(7,3.121914);
   h_PureKaonNC_stack_7->SetBinContent(9,0.009986636);
   h_PureKaonNC_stack_7->SetBinContent(10,54.82021);
   h_PureKaonNC_stack_7->SetBinError(1,4.41528);
   h_PureKaonNC_stack_7->SetBinError(2,9.872754);
   h_PureKaonNC_stack_7->SetBinError(3,7.647371);
   h_PureKaonNC_stack_7->SetBinError(4,3.121994);
   h_PureKaonNC_stack_7->SetBinError(5,0.01412324);
   h_PureKaonNC_stack_7->SetBinError(6,3.12193);
   h_PureKaonNC_stack_7->SetBinError(7,3.121914);
   h_PureKaonNC_stack_7->SetBinError(9,0.009986636);
   h_PureKaonNC_stack_7->SetBinError(10,12.87266);
   h_PureKaonNC_stack_7->SetEntries(372);

   ci = TColor::GetColor("#ffcc00");
   h_PureKaonNC_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonNC_stack_7->SetLineColor(ci);
   h_PureKaonNC_stack_7->GetXaxis()->SetTitle("Invariant Mass (GeV)");
   h_PureKaonNC_stack_7->GetXaxis()->SetLabelFont(42);
   h_PureKaonNC_stack_7->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonNC_stack_7->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonNC_stack_7->GetXaxis()->SetTitleFont(42);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitle("Events/bin");
   h_PureKaonNC_stack_7->GetYaxis()->SetLabelFont(42);
   h_PureKaonNC_stack_7->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitleOffset(0);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitleFont(42);
   h_PureKaonNC_stack_7->GetZaxis()->SetLabelFont(42);
   h_PureKaonNC_stack_7->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonNC_stack_7->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonNC_stack_7->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonNC_stack_7,"HIST");
   
   TH1D *h_PureKaonOutFV_stack_8 = new TH1D("h_PureKaonOutFV_stack_8","",9,0.2,1.1);
   h_PureKaonOutFV_stack_8->SetBinContent(1,0.04993318);
   h_PureKaonOutFV_stack_8->SetBinContent(2,25.2849);
   h_PureKaonOutFV_stack_8->SetBinContent(3,6.363669);
   h_PureKaonOutFV_stack_8->SetBinContent(4,12.53759);
   h_PureKaonOutFV_stack_8->SetBinContent(5,6.303749);
   h_PureKaonOutFV_stack_8->SetBinContent(6,3.121914);
   h_PureKaonOutFV_stack_8->SetBinContent(7,0.009986636);
   h_PureKaonOutFV_stack_8->SetBinContent(10,38.0422);
   h_PureKaonOutFV_stack_8->SetBinError(1,0.0223308);
   h_PureKaonOutFV_stack_8->SetBinError(2,8.830283);
   h_PureKaonOutFV_stack_8->SetBinError(3,4.415189);
   h_PureKaonOutFV_stack_8->SetBinError(4,6.243869);
   h_PureKaonOutFV_stack_8->SetBinError(5,4.415122);
   h_PureKaonOutFV_stack_8->SetBinError(6,3.121914);
   h_PureKaonOutFV_stack_8->SetBinError(7,0.009986636);
   h_PureKaonOutFV_stack_8->SetBinError(10,10.8149);
   h_PureKaonOutFV_stack_8->SetEntries(156);

   ci = TColor::GetColor("#cccccc");
   h_PureKaonOutFV_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonOutFV_stack_8->SetLineColor(ci);
   h_PureKaonOutFV_stack_8->GetXaxis()->SetTitle("Invariant Mass (GeV)");
   h_PureKaonOutFV_stack_8->GetXaxis()->SetLabelFont(42);
   h_PureKaonOutFV_stack_8->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonOutFV_stack_8->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonOutFV_stack_8->GetXaxis()->SetTitleFont(42);
   h_PureKaonOutFV_stack_8->GetYaxis()->SetTitle("Events/bin");
   h_PureKaonOutFV_stack_8->GetYaxis()->SetLabelFont(42);
   h_PureKaonOutFV_stack_8->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonOutFV_stack_8->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonOutFV_stack_8->GetYaxis()->SetTitleOffset(0);
   h_PureKaonOutFV_stack_8->GetYaxis()->SetTitleFont(42);
   h_PureKaonOutFV_stack_8->GetZaxis()->SetLabelFont(42);
   h_PureKaonOutFV_stack_8->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonOutFV_stack_8->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonOutFV_stack_8->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonOutFV_stack_8,"HIST");
   
   TH1D *h_PureKaonBeamOff_stack_9 = new TH1D("h_PureKaonBeamOff_stack_9","",9,0.2,1.1);
   h_PureKaonBeamOff_stack_9->SetBinContent(1,3.15884);
   h_PureKaonBeamOff_stack_9->SetBinContent(4,3.15884);
   h_PureKaonBeamOff_stack_9->SetBinContent(10,18.95304);
   h_PureKaonBeamOff_stack_9->SetBinError(1,3.15884);
   h_PureKaonBeamOff_stack_9->SetBinError(4,3.15884);
   h_PureKaonBeamOff_stack_9->SetBinError(10,7.737545);
   h_PureKaonBeamOff_stack_9->SetEntries(8);
   h_PureKaonBeamOff_stack_9->SetFillColor(1);
   h_PureKaonBeamOff_stack_9->SetFillStyle(3004);

   ci = TColor::GetColor("#000099");
   h_PureKaonBeamOff_stack_9->SetLineColor(ci);
   h_PureKaonBeamOff_stack_9->GetXaxis()->SetTitle("Invariant Mass (GeV)");
   h_PureKaonBeamOff_stack_9->GetXaxis()->SetLabelFont(42);
   h_PureKaonBeamOff_stack_9->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonBeamOff_stack_9->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonBeamOff_stack_9->GetXaxis()->SetTitleFont(42);
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetTitle("Events/bin");
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetLabelFont(42);
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetTitleOffset(0);
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetTitleFont(42);
   h_PureKaonBeamOff_stack_9->GetZaxis()->SetLabelFont(42);
   h_PureKaonBeamOff_stack_9->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonBeamOff_stack_9->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonBeamOff_stack_9->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonBeamOff_stack_9,"HIST");
   
   TH1D *h_PureKaonOther_stack_10 = new TH1D("h_PureKaonOther_stack_10","",9,0.2,1.1);
   h_PureKaonOther_stack_10->SetBinContent(4,28.78802);
   h_PureKaonOther_stack_10->SetBinContent(8,57.57605);
   h_PureKaonOther_stack_10->SetBinContent(10,158.3341);
   h_PureKaonOther_stack_10->SetBinError(4,20.35621);
   h_PureKaonOther_stack_10->SetBinError(8,28.78802);
   h_PureKaonOther_stack_10->SetBinError(10,47.73954);
   h_PureKaonOther_stack_10->SetEntries(17);

   ci = TColor::GetColor("#cc0000");
   h_PureKaonOther_stack_10->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonOther_stack_10->SetLineColor(ci);
   h_PureKaonOther_stack_10->GetXaxis()->SetTitle("Invariant Mass (GeV)");
   h_PureKaonOther_stack_10->GetXaxis()->SetLabelFont(42);
   h_PureKaonOther_stack_10->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonOther_stack_10->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonOther_stack_10->GetXaxis()->SetTitleFont(42);
   h_PureKaonOther_stack_10->GetYaxis()->SetTitle("Events/bin");
   h_PureKaonOther_stack_10->GetYaxis()->SetLabelFont(42);
   h_PureKaonOther_stack_10->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonOther_stack_10->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonOther_stack_10->GetYaxis()->SetTitleOffset(0);
   h_PureKaonOther_stack_10->GetYaxis()->SetTitleFont(42);
   h_PureKaonOther_stack_10->GetZaxis()->SetLabelFont(42);
   h_PureKaonOther_stack_10->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonOther_stack_10->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonOther_stack_10->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonOther_stack_10,"HIST");
   hs->Draw("hist same");
   
   TH1D *h_errors__2 = new TH1D("h_errors__2","",9,0.2,1.1);
   h_errors__2->SetBinContent(1,82.29524);
   h_errors__2->SetBinContent(2,345.6715);
   h_errors__2->SetBinContent(3,171.11);
   h_errors__2->SetBinContent(4,129.7748);
   h_errors__2->SetBinContent(5,59.77576);
   h_errors__2->SetBinContent(6,25.19502);
   h_errors__2->SetBinContent(7,15.69945);
   h_errors__2->SetBinContent(8,60.72792);
   h_errors__2->SetBinContent(9,3.141888);
   h_errors__2->SetBinContent(10,1056.354);
   h_errors__2->SetBinError(1,15.92633);
   h_errors__2->SetBinError(2,32.59457);
   h_errors__2->SetBinError(3,22.94184);
   h_errors__2->SetBinError(4,26.95368);
   h_errors__2->SetBinError(5,13.60828);
   h_errors__2->SetBinError(6,8.830232);
   h_errors__2->SetBinError(7,6.980877);
   h_errors__2->SetBinError(8,28.95681);
   h_errors__2->SetBinError(9,3.121946);
   h_errors__2->SetBinError(10,71.05301);
   h_errors__2->SetMinimum(0);
   h_errors__2->SetMaximum(472.8326);
   h_errors__2->SetEntries(2824);
   h_errors__2->SetStats(0);
   h_errors__2->SetFillColor(1);
   h_errors__2->SetFillStyle(3253);

   ci = TColor::GetColor("#000099");
   h_errors__2->SetLineColor(ci);
   h_errors__2->GetXaxis()->SetTitle("Invariant Mass (GeV)");
   h_errors__2->GetXaxis()->SetLabelFont(42);
   h_errors__2->GetXaxis()->SetLabelSize(0.045);
   h_errors__2->GetXaxis()->SetTitleSize(0.05);
   h_errors__2->GetXaxis()->SetTitleOffset(0.93);
   h_errors__2->GetXaxis()->SetTitleFont(42);
   h_errors__2->GetYaxis()->SetTitle("Events/bin");
   h_errors__2->GetYaxis()->SetLabelFont(42);
   h_errors__2->GetYaxis()->SetLabelSize(0.045);
   h_errors__2->GetYaxis()->SetTitleSize(0.05);
   h_errors__2->GetYaxis()->SetTitleOffset(1.06);
   h_errors__2->GetYaxis()->SetTitleFont(42);
   h_errors__2->GetZaxis()->SetLabelFont(42);
   h_errors__2->GetZaxis()->SetLabelSize(0.035);
   h_errors__2->GetZaxis()->SetTitleSize(0.035);
   h_errors__2->GetZaxis()->SetTitleFont(42);
   h_errors__2->Draw("E2 same");
   
   TH1D *h_errors_copy__3 = new TH1D("h_errors_copy__3","",9,0.2,1.1);
   h_errors_copy__3->SetBinContent(1,82.29524);
   h_errors_copy__3->SetBinContent(2,345.6715);
   h_errors_copy__3->SetBinContent(3,171.11);
   h_errors_copy__3->SetBinContent(4,129.7748);
   h_errors_copy__3->SetBinContent(5,59.77576);
   h_errors_copy__3->SetBinContent(6,25.19502);
   h_errors_copy__3->SetBinContent(7,15.69945);
   h_errors_copy__3->SetBinContent(8,60.72792);
   h_errors_copy__3->SetBinContent(9,3.141888);
   h_errors_copy__3->SetBinContent(10,1056.354);
   h_errors_copy__3->SetBinError(1,15.92633);
   h_errors_copy__3->SetBinError(2,32.59457);
   h_errors_copy__3->SetBinError(3,22.94184);
   h_errors_copy__3->SetBinError(4,26.95368);
   h_errors_copy__3->SetBinError(5,13.60828);
   h_errors_copy__3->SetBinError(6,8.830232);
   h_errors_copy__3->SetBinError(7,6.980877);
   h_errors_copy__3->SetBinError(8,28.95681);
   h_errors_copy__3->SetBinError(9,3.121946);
   h_errors_copy__3->SetBinError(10,71.05301);
   h_errors_copy__3->SetMinimum(0);
   h_errors_copy__3->SetMaximum(472.8326);
   h_errors_copy__3->SetEntries(2824);
   h_errors_copy__3->SetDirectory(0);
   h_errors_copy__3->SetStats(0);
   h_errors_copy__3->SetFillColor(1);
   h_errors_copy__3->SetFillStyle(3253);

   ci = TColor::GetColor("#000099");
   h_errors_copy__3->SetLineColor(ci);
   h_errors_copy__3->GetXaxis()->SetTitle("Invariant Mass (GeV)");
   h_errors_copy__3->GetXaxis()->SetLabelFont(42);
   h_errors_copy__3->GetXaxis()->SetLabelSize(0.045);
   h_errors_copy__3->GetXaxis()->SetTitleSize(0.05);
   h_errors_copy__3->GetXaxis()->SetTitleOffset(0.93);
   h_errors_copy__3->GetXaxis()->SetTitleFont(42);
   h_errors_copy__3->GetYaxis()->SetTitle("Events/bin");
   h_errors_copy__3->GetYaxis()->SetLabelFont(42);
   h_errors_copy__3->GetYaxis()->SetLabelSize(0.045);
   h_errors_copy__3->GetYaxis()->SetTitleSize(0.05);
   h_errors_copy__3->GetYaxis()->SetTitleOffset(1.06);
   h_errors_copy__3->GetYaxis()->SetTitleFont(42);
   h_errors_copy__3->GetZaxis()->SetLabelFont(42);
   h_errors_copy__3->GetZaxis()->SetLabelSize(0.035);
   h_errors_copy__3->GetZaxis()->SetTitleSize(0.035);
   h_errors_copy__3->GetZaxis()->SetTitleFont(42);
   h_errors_copy__3->Draw("sameaxis");
   
   leg = new TLegend(0.54,0.815,0.885,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(32);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("NULL","NuMI RHC, 1.5 #times 10^{21} POT","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   leg = new TLegend(0.45,0.9,0.89,0.985,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(32);
   leg->SetTextFont(62);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("NULL","MicroBooNE Simulation, Preliminary","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   p_plot->Modified();
   c->cd();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
