void background_rhc_track_multi_ByPureKaonType()
{
//=========Macro generated from canvas: c/c
//=========  (Wed Feb 14 05:52:55 2024) by ROOT version 6.12/06
   TCanvas *c = new TCanvas("c", "c",0,0,800,600);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: p_legend
   TPad *p_legend = new TPad("p_legend", "p_legend",0,0.85,1,1);
   p_legend->Draw();
   p_legend->cd();
   p_legend->Range(0,0,1,1);
   p_legend->SetFillColor(0);
   p_legend->SetBorderMode(0);
   p_legend->SetBorderSize(2);
   p_legend->SetBottomMargin(0);
   p_legend->SetFrameBorderMode(0);
   
   TLegend *leg = new TLegend(0.1,0,0.9,1,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaon","#nu_{#mu}CCK^{0}0#pi","F");

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaonMultiPion","#nu_{#mu}CCK^{0}N#pi","F");

   ci = TColor::GetColor("#00cc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaonHyperon","#nu_{#mu}CCK^{0}Y0#pi","F");

   ci = TColor::GetColor("#009900");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaonHyperonMultiPion","#nu_{#mu}CCK^{0}YN#pi","F");

   ci = TColor::GetColor("#006600");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonOtherNuMuCC","Other #nu_{#mu}CC","F");
   entry->SetFillColor(30);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonNuECC","#nu_{e}CC","F");

   ci = TColor::GetColor("#cc33ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonNC","NC","F");

   ci = TColor::GetColor("#ffcc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonOutFV","Out FV","F");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonBeamOff","Beam-Off","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3004);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonOther","Other","F");

   ci = TColor::GetColor("#cc0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   p_legend->Modified();
   c->cd();
  
// ------------>Primitives in pad: p_plot
   TPad *p_plot = new TPad("p_plot", "p_plot",0,0,1,0.85);
   p_plot->Draw();
   p_plot->cd();
   p_plot->Range(-1,-25406.57,9,228659.1);
   p_plot->SetFillColor(0);
   p_plot->SetBorderMode(0);
   p_plot->SetBorderSize(2);
   p_plot->SetTopMargin(0.01);
   p_plot->SetFrameBorderMode(0);
   p_plot->SetFrameBorderMode(0);
   
   TH1D *h_errors__1 = new TH1D("h_errors__1","",8,0,8);
   h_errors__1->SetBinContent(1,22998.85);
   h_errors__1->SetBinContent(2,179484.9);
   h_errors__1->SetBinContent(3,158158.7);
   h_errors__1->SetBinContent(4,51125.16);
   h_errors__1->SetBinContent(5,17193.62);
   h_errors__1->SetBinContent(6,6286.966);
   h_errors__1->SetBinContent(7,2070.961);
   h_errors__1->SetBinContent(8,771.0637);
   h_errors__1->SetBinContent(9,454.4657);
   h_errors__1->SetBinError(1,503.2175);
   h_errors__1->SetBinError(2,1409.902);
   h_errors__1->SetBinError(3,1270.587);
   h_errors__1->SetBinError(4,653.7169);
   h_errors__1->SetBinError(5,330.8887);
   h_errors__1->SetBinError(6,184.2565);
   h_errors__1->SetBinError(7,96.52123);
   h_errors__1->SetBinError(8,57.86571);
   h_errors__1->SetBinError(9,41.48679);
   h_errors__1->SetMinimum(0);
   h_errors__1->SetMaximum(226118.5);
   h_errors__1->SetEntries(109855);
   h_errors__1->SetStats(0);
   h_errors__1->SetFillColor(1);
   h_errors__1->SetFillStyle(3253);

   ci = TColor::GetColor("#000099");
   h_errors__1->SetLineColor(ci);
   h_errors__1->GetXaxis()->SetTitle("Track Multiplicity");
   h_errors__1->GetXaxis()->SetLabelFont(42);
   h_errors__1->GetXaxis()->SetLabelSize(0.045);
   h_errors__1->GetXaxis()->SetTitleSize(0.05);
   h_errors__1->GetXaxis()->SetTitleOffset(0.93);
   h_errors__1->GetXaxis()->SetTitleFont(42);
   h_errors__1->GetYaxis()->SetTitle(" Events/bin");
   h_errors__1->GetYaxis()->SetLabelFont(42);
   h_errors__1->GetYaxis()->SetLabelSize(0.045);
   h_errors__1->GetYaxis()->SetTitleSize(0.05);
   h_errors__1->GetYaxis()->SetTitleOffset(1.06);
   h_errors__1->GetYaxis()->SetTitleFont(42);
   h_errors__1->GetZaxis()->SetLabelFont(42);
   h_errors__1->GetZaxis()->SetLabelSize(0.035);
   h_errors__1->GetZaxis()->SetTitleSize(0.035);
   h_errors__1->GetZaxis()->SetTitleFont(42);
   h_errors__1->Draw("E2");
   
   THStack *hs = new THStack();
   hs->SetName("hs");
   hs->SetTitle("");
   
   TH1F *hs_stack_1 = new TH1F("hs_stack_1","",8,0,8);
   hs_stack_1->SetMinimum(0);
   hs_stack_1->SetMaximum(188459.1);
   hs_stack_1->SetDirectory(0);
   hs_stack_1->SetStats(0);

   ci = TColor::GetColor("#000099");
   hs_stack_1->SetLineColor(ci);
   hs_stack_1->GetXaxis()->SetLabelFont(42);
   hs_stack_1->GetXaxis()->SetLabelSize(0.035);
   hs_stack_1->GetXaxis()->SetTitleSize(0.035);
   hs_stack_1->GetXaxis()->SetTitleFont(42);
   hs_stack_1->GetYaxis()->SetLabelFont(42);
   hs_stack_1->GetYaxis()->SetLabelSize(0.035);
   hs_stack_1->GetYaxis()->SetTitleSize(0.035);
   hs_stack_1->GetYaxis()->SetTitleOffset(0);
   hs_stack_1->GetYaxis()->SetTitleFont(42);
   hs_stack_1->GetZaxis()->SetLabelFont(42);
   hs_stack_1->GetZaxis()->SetLabelSize(0.035);
   hs_stack_1->GetZaxis()->SetTitleSize(0.035);
   hs_stack_1->GetZaxis()->SetTitleFont(42);
   hs->SetHistogram(hs_stack_1);
   
   
   TH1D *h_PureKaonSignalNuMuCCKaon_stack_1 = new TH1D("h_PureKaonSignalNuMuCCKaon_stack_1","",8,0,8);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(1,0.01997327);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(2,0.3095857);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(3,0.7190378);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(4,1.028623);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(5,1.428089);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(6,1.278289);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(7,0.7489977);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(8,0.3794922);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(9,0.3195723);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(1,0.01412324);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(2,0.05560324);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(3,0.08473942);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(4,0.1013533);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(5,0.1194228);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(6,0.1129859);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(7,0.0864868);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(8,0.06156176);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(9,0.05649294);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetEntries(629);

   ci = TColor::GetColor("#00ff00");
   h_PureKaonSignalNuMuCCKaon_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaon_stack_1->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaon_stack_1,"HIST");
   
   TH1D *h_PureKaonSignalNuMuCCKaonMultiPion_stack_2 = new TH1D("h_PureKaonSignalNuMuCCKaonMultiPion_stack_2","",8,0,8);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(1,0.05991982);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(2,0.6291581);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(3,1.497995);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(4,2.386806);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(5,2.416766);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(6,5.089282);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(7,1.787608);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(8,4.140551);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(9,4.210458);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(1,0.02446216);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(2,0.07926646);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(3,0.1223108);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(4,0.1543896);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(5,0.1553556);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(6,3.12506);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(7,0.1336121);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(8,3.123543);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(9,3.123655);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetEntries(1398);

   ci = TColor::GetColor("#00cc00");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaonMultiPion_stack_2,"HIST");
   
   TH1D *h_PureKaonSignalNuMuCCKaonHyperon_stack_3 = new TH1D("h_PureKaonSignalNuMuCCKaonHyperon_stack_3","",8,0,8);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(1,0.07989309);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(2,4.050672);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(3,6.028025);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(4,8.155179);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(5,15.41764);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(6,4.264294);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(7,8.740488);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(8,0.8888106);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(9,0.5392783);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(1,0.02824647);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(2,3.1234);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(3,3.126559);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(4,3.129955);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(5,5.4129);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(6,0.2063636);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(7,4.417877);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(8,0.09421373);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(9,0.07338649);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetEntries(2330);

   ci = TColor::GetColor("#009900");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaonHyperon_stack_3,"HIST");
   
   TH1D *h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4 = new TH1D("h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4","",8,0,8);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(1,0.3495323);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(2,5.928159);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(3,13.04473);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(4,20.24119);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(5,39.64178);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(6,31.87998);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(7,9.733067);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(8,6.387544);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(9,5.638547);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(1,0.05908173);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(2,3.1264);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(3,4.422739);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(4,5.417348);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(5,9.371896);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(6,8.265868);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(7,3.132471);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(8,3.127133);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(9,3.125937);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetEntries(5518);

   ci = TColor::GetColor("#006600");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4,"HIST");
   
   TH1D *h_PureKaonOtherNuMuCC_stack_5 = new TH1D("h_PureKaonOtherNuMuCC_stack_5","",8,0,8);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(1,638.2787);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(2,18695.06);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(3,33174.63);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(4,18570.27);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(5,9118.666);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(6,3807.273);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(7,1466.748);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(8,548.7818);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(9,332.4509);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(1,44.59002);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(2,241.5202);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(3,321.7242);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(4,240.631);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(5,168.555);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(6,108.8654);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(7,67.53776);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(8,41.29934);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(9,32.14231);
   h_PureKaonOtherNuMuCC_stack_5->SetEntries(37518);
   h_PureKaonOtherNuMuCC_stack_5->SetFillColor(30);

   ci = TColor::GetColor("#000099");
   h_PureKaonOtherNuMuCC_stack_5->SetLineColor(ci);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetLabelFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetTitleFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetLabelFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitleOffset(0);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitleFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetLabelFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonOtherNuMuCC_stack_5,"HIST");
   
   TH1D *h_PureKaonNuECC_stack_6 = new TH1D("h_PureKaonNuECC_stack_6","",8,0,8);
   h_PureKaonNuECC_stack_6->SetBinContent(1,668.3893);
   h_PureKaonNuECC_stack_6->SetBinContent(2,1361.994);
   h_PureKaonNuECC_stack_6->SetBinContent(3,959.9157);
   h_PureKaonNuECC_stack_6->SetBinContent(4,531.7541);
   h_PureKaonNuECC_stack_6->SetBinContent(5,200.4317);
   h_PureKaonNuECC_stack_6->SetBinContent(6,59.78575);
   h_PureKaonNuECC_stack_6->SetBinContent(7,18.88129);
   h_PureKaonNuECC_stack_6->SetBinContent(8,6.333709);
   h_PureKaonNuECC_stack_6->SetBinContent(9,0.02995991);
   h_PureKaonNuECC_stack_6->SetBinError(1,45.6697);
   h_PureKaonNuECC_stack_6->SetBinError(2,65.18755);
   h_PureKaonNuECC_stack_6->SetBinError(3,54.7005);
   h_PureKaonNuECC_stack_6->SetBinError(4,40.70491);
   h_PureKaonNuECC_stack_6->SetBinError(5,24.97544);
   h_PureKaonNuECC_stack_6->SetBinError(6,13.60828);
   h_PureKaonNuECC_stack_6->SetBinError(7,7.647195);
   h_PureKaonNuECC_stack_6->SetBinError(8,4.415155);
   h_PureKaonNuECC_stack_6->SetBinError(9,0.01729736);
   h_PureKaonNuECC_stack_6->SetEntries(1742);

   ci = TColor::GetColor("#cc33ff");
   h_PureKaonNuECC_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonNuECC_stack_6->SetLineColor(ci);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonNuECC_stack_6->GetXaxis()->SetLabelFont(42);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetTitleFont(42);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonNuECC_stack_6->GetYaxis()->SetLabelFont(42);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitleOffset(0);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitleFont(42);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetLabelFont(42);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonNuECC_stack_6,"HIST");
   
   TH1D *h_PureKaonNC_stack_7 = new TH1D("h_PureKaonNC_stack_7","",8,0,8);
   h_PureKaonNC_stack_7->SetBinContent(1,1663.199);
   h_PureKaonNC_stack_7->SetBinContent(2,7501.101);
   h_PureKaonNC_stack_7->SetBinContent(3,5712.671);
   h_PureKaonNC_stack_7->SetBinContent(4,3054.963);
   h_PureKaonNC_stack_7->SetBinContent(5,1301.568);
   h_PureKaonNC_stack_7->SetBinContent(6,582.9708);
   h_PureKaonNC_stack_7->SetBinContent(7,163.3921);
   h_PureKaonNC_stack_7->SetBinContent(8,76.6836);
   h_PureKaonNC_stack_7->SetBinContent(9,50.8694);
   h_PureKaonNC_stack_7->SetBinError(1,71.94002);
   h_PureKaonNC_stack_7->SetBinError(2,152.8787);
   h_PureKaonNC_stack_7->SetBinError(3,133.2959);
   h_PureKaonNC_stack_7->SetBinError(4,97.33271);
   h_PureKaonNC_stack_7->SetBinError(5,63.36915);
   h_PureKaonNC_stack_7->SetBinError(6,42.34871);
   h_PureKaonNC_stack_7->SetBinError(7,22.29586);
   h_PureKaonNC_stack_7->SetBinError(8,15.29477);
   h_PureKaonNC_stack_7->SetBinError(9,12.48803);
   h_PureKaonNC_stack_7->SetEntries(16020);

   ci = TColor::GetColor("#ffcc00");
   h_PureKaonNC_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonNC_stack_7->SetLineColor(ci);
   h_PureKaonNC_stack_7->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonNC_stack_7->GetXaxis()->SetLabelFont(42);
   h_PureKaonNC_stack_7->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonNC_stack_7->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonNC_stack_7->GetXaxis()->SetTitleFont(42);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonNC_stack_7->GetYaxis()->SetLabelFont(42);
   h_PureKaonNC_stack_7->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitleOffset(0);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitleFont(42);
   h_PureKaonNC_stack_7->GetZaxis()->SetLabelFont(42);
   h_PureKaonNC_stack_7->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonNC_stack_7->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonNC_stack_7->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonNC_stack_7,"HIST");
   
   TH1D *h_PureKaonOutFV_stack_8 = new TH1D("h_PureKaonOutFV_stack_8","",8,0,8);
   h_PureKaonOutFV_stack_8->SetBinContent(1,1892.198);
   h_PureKaonOutFV_stack_8->SetBinContent(2,11441.92);
   h_PureKaonOutFV_stack_8->SetBinContent(3,8811.598);
   h_PureKaonOutFV_stack_8->SetBinContent(4,2679.523);
   h_PureKaonOutFV_stack_8->SetBinContent(5,935.3039);
   h_PureKaonOutFV_stack_8->SetBinContent(6,326.986);
   h_PureKaonOutFV_stack_8->SetBinContent(7,113.4076);
   h_PureKaonOutFV_stack_8->SetBinContent(8,41.10419);
   h_PureKaonOutFV_stack_8->SetBinContent(9,22.14301);
   h_PureKaonOutFV_stack_8->SetBinError(1,76.72588);
   h_PureKaonOutFV_stack_8->SetBinError(2,188.7669);
   h_PureKaonOutFV_stack_8->SetBinError(3,165.6388);
   h_PureKaonOutFV_stack_8->SetBinError(4,91.28654);
   h_PureKaonOutFV_stack_8->SetBinError(5,53.89306);
   h_PureKaonOutFV_stack_8->SetBinError(6,31.83777);
   h_PureKaonOutFV_stack_8->SetBinError(7,18.73176);
   h_PureKaonOutFV_stack_8->SetBinError(8,11.25645);
   h_PureKaonOutFV_stack_8->SetBinError(9,8.259984);
   h_PureKaonOutFV_stack_8->SetEntries(16441);

   ci = TColor::GetColor("#cccccc");
   h_PureKaonOutFV_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonOutFV_stack_8->SetLineColor(ci);
   h_PureKaonOutFV_stack_8->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonOutFV_stack_8->GetXaxis()->SetLabelFont(42);
   h_PureKaonOutFV_stack_8->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonOutFV_stack_8->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonOutFV_stack_8->GetXaxis()->SetTitleFont(42);
   h_PureKaonOutFV_stack_8->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonOutFV_stack_8->GetYaxis()->SetLabelFont(42);
   h_PureKaonOutFV_stack_8->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonOutFV_stack_8->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonOutFV_stack_8->GetYaxis()->SetTitleOffset(0);
   h_PureKaonOutFV_stack_8->GetYaxis()->SetTitleFont(42);
   h_PureKaonOutFV_stack_8->GetZaxis()->SetLabelFont(42);
   h_PureKaonOutFV_stack_8->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonOutFV_stack_8->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonOutFV_stack_8->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonOutFV_stack_8,"HIST");
   
   TH1D *h_PureKaonBeamOff_stack_9 = new TH1D("h_PureKaonBeamOff_stack_9","",8,0,8);
   h_PureKaonBeamOff_stack_9->SetBinContent(1,2043.769);
   h_PureKaonBeamOff_stack_9->SetBinContent(2,13864.15);
   h_PureKaonBeamOff_stack_9->SetBinContent(3,10073.54);
   h_PureKaonBeamOff_stack_9->SetBinContent(4,2492.324);
   h_PureKaonBeamOff_stack_9->SetBinContent(5,612.8149);
   h_PureKaonBeamOff_stack_9->SetBinContent(6,186.3715);
   h_PureKaonBeamOff_stack_9->SetBinContent(7,28.42956);
   h_PureKaonBeamOff_stack_9->SetBinContent(9,9.476519);
   h_PureKaonBeamOff_stack_9->SetBinError(1,80.34886);
   h_PureKaonBeamOff_stack_9->SetBinError(2,209.2716);
   h_PureKaonBeamOff_stack_9->SetBinError(3,178.3836);
   h_PureKaonBeamOff_stack_9->SetBinError(4,88.7291);
   h_PureKaonBeamOff_stack_9->SetBinError(5,43.99754);
   h_PureKaonBeamOff_stack_9->SetBinError(6,24.26351);
   h_PureKaonBeamOff_stack_9->SetBinError(7,9.476519);
   h_PureKaonBeamOff_stack_9->SetBinError(9,5.471271);
   h_PureKaonBeamOff_stack_9->SetEntries(9328);
   h_PureKaonBeamOff_stack_9->SetFillColor(1);
   h_PureKaonBeamOff_stack_9->SetFillStyle(3004);

   ci = TColor::GetColor("#000099");
   h_PureKaonBeamOff_stack_9->SetLineColor(ci);
   h_PureKaonBeamOff_stack_9->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonBeamOff_stack_9->GetXaxis()->SetLabelFont(42);
   h_PureKaonBeamOff_stack_9->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonBeamOff_stack_9->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonBeamOff_stack_9->GetXaxis()->SetTitleFont(42);
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetLabelFont(42);
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetTitleOffset(0);
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetTitleFont(42);
   h_PureKaonBeamOff_stack_9->GetZaxis()->SetLabelFont(42);
   h_PureKaonBeamOff_stack_9->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonBeamOff_stack_9->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonBeamOff_stack_9->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonBeamOff_stack_9,"HIST");
   
   TH1D *h_PureKaonOther_stack_10 = new TH1D("h_PureKaonOther_stack_10","",8,0,8);
   h_PureKaonOther_stack_10->SetBinContent(1,16092.51);
   h_PureKaonOther_stack_10->SetBinContent(2,126609.7);
   h_PureKaonOther_stack_10->SetBinContent(3,99405.05);
   h_PureKaonOther_stack_10->SetBinContent(4,23764.51);
   h_PureKaonOther_stack_10->SetBinContent(5,4965.934);
   h_PureKaonOther_stack_10->SetBinContent(6,1281.067);
   h_PureKaonOther_stack_10->SetBinContent(7,259.0922);
   h_PureKaonOther_stack_10->SetBinContent(8,86.36407);
   h_PureKaonOther_stack_10->SetBinContent(9,28.78802);
   h_PureKaonOther_stack_10->SetBinError(1,481.2855);
   h_PureKaonOther_stack_10->SetBinError(2,1349.971);
   h_PureKaonOther_stack_10->SetBinError(3,1196.176);
   h_PureKaonOther_stack_10->SetBinError(4,584.8647);
   h_PureKaonOther_stack_10->SetBinError(5,267.3569);
   h_PureKaonOther_stack_10->SetBinError(6,135.7928);
   h_PureKaonOther_stack_10->SetBinError(7,61.06862);
   h_PureKaonOther_stack_10->SetBinError(8,35.25798);
   h_PureKaonOther_stack_10->SetBinError(9,20.35621);
   h_PureKaonOther_stack_10->SetEntries(18931);

   ci = TColor::GetColor("#cc0000");
   h_PureKaonOther_stack_10->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonOther_stack_10->SetLineColor(ci);
   h_PureKaonOther_stack_10->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonOther_stack_10->GetXaxis()->SetLabelFont(42);
   h_PureKaonOther_stack_10->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonOther_stack_10->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonOther_stack_10->GetXaxis()->SetTitleFont(42);
   h_PureKaonOther_stack_10->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonOther_stack_10->GetYaxis()->SetLabelFont(42);
   h_PureKaonOther_stack_10->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonOther_stack_10->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonOther_stack_10->GetYaxis()->SetTitleOffset(0);
   h_PureKaonOther_stack_10->GetYaxis()->SetTitleFont(42);
   h_PureKaonOther_stack_10->GetZaxis()->SetLabelFont(42);
   h_PureKaonOther_stack_10->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonOther_stack_10->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonOther_stack_10->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonOther_stack_10,"HIST");
   hs->Draw("hist same");
   
   TH1D *h_errors__2 = new TH1D("h_errors__2","",8,0,8);
   h_errors__2->SetBinContent(1,22998.85);
   h_errors__2->SetBinContent(2,179484.9);
   h_errors__2->SetBinContent(3,158158.7);
   h_errors__2->SetBinContent(4,51125.16);
   h_errors__2->SetBinContent(5,17193.62);
   h_errors__2->SetBinContent(6,6286.966);
   h_errors__2->SetBinContent(7,2070.961);
   h_errors__2->SetBinContent(8,771.0637);
   h_errors__2->SetBinContent(9,454.4657);
   h_errors__2->SetBinError(1,503.2175);
   h_errors__2->SetBinError(2,1409.902);
   h_errors__2->SetBinError(3,1270.587);
   h_errors__2->SetBinError(4,653.7169);
   h_errors__2->SetBinError(5,330.8887);
   h_errors__2->SetBinError(6,184.2565);
   h_errors__2->SetBinError(7,96.52123);
   h_errors__2->SetBinError(8,57.86571);
   h_errors__2->SetBinError(9,41.48679);
   h_errors__2->SetMinimum(0);
   h_errors__2->SetMaximum(226118.5);
   h_errors__2->SetEntries(109855);
   h_errors__2->SetStats(0);
   h_errors__2->SetFillColor(1);
   h_errors__2->SetFillStyle(3253);

   ci = TColor::GetColor("#000099");
   h_errors__2->SetLineColor(ci);
   h_errors__2->GetXaxis()->SetTitle("Track Multiplicity");
   h_errors__2->GetXaxis()->SetLabelFont(42);
   h_errors__2->GetXaxis()->SetLabelSize(0.045);
   h_errors__2->GetXaxis()->SetTitleSize(0.05);
   h_errors__2->GetXaxis()->SetTitleOffset(0.93);
   h_errors__2->GetXaxis()->SetTitleFont(42);
   h_errors__2->GetYaxis()->SetTitle(" Events/bin");
   h_errors__2->GetYaxis()->SetLabelFont(42);
   h_errors__2->GetYaxis()->SetLabelSize(0.045);
   h_errors__2->GetYaxis()->SetTitleSize(0.05);
   h_errors__2->GetYaxis()->SetTitleOffset(1.06);
   h_errors__2->GetYaxis()->SetTitleFont(42);
   h_errors__2->GetZaxis()->SetLabelFont(42);
   h_errors__2->GetZaxis()->SetLabelSize(0.035);
   h_errors__2->GetZaxis()->SetTitleSize(0.035);
   h_errors__2->GetZaxis()->SetTitleFont(42);
   h_errors__2->Draw("E2 same");
   
   TH1D *h_errors_copy__3 = new TH1D("h_errors_copy__3","",8,0,8);
   h_errors_copy__3->SetBinContent(1,22998.85);
   h_errors_copy__3->SetBinContent(2,179484.9);
   h_errors_copy__3->SetBinContent(3,158158.7);
   h_errors_copy__3->SetBinContent(4,51125.16);
   h_errors_copy__3->SetBinContent(5,17193.62);
   h_errors_copy__3->SetBinContent(6,6286.966);
   h_errors_copy__3->SetBinContent(7,2070.961);
   h_errors_copy__3->SetBinContent(8,771.0637);
   h_errors_copy__3->SetBinContent(9,454.4657);
   h_errors_copy__3->SetBinError(1,503.2175);
   h_errors_copy__3->SetBinError(2,1409.902);
   h_errors_copy__3->SetBinError(3,1270.587);
   h_errors_copy__3->SetBinError(4,653.7169);
   h_errors_copy__3->SetBinError(5,330.8887);
   h_errors_copy__3->SetBinError(6,184.2565);
   h_errors_copy__3->SetBinError(7,96.52123);
   h_errors_copy__3->SetBinError(8,57.86571);
   h_errors_copy__3->SetBinError(9,41.48679);
   h_errors_copy__3->SetMinimum(0);
   h_errors_copy__3->SetMaximum(226118.5);
   h_errors_copy__3->SetEntries(109855);
   h_errors_copy__3->SetDirectory(0);
   h_errors_copy__3->SetStats(0);
   h_errors_copy__3->SetFillColor(1);
   h_errors_copy__3->SetFillStyle(3253);

   ci = TColor::GetColor("#000099");
   h_errors_copy__3->SetLineColor(ci);
   h_errors_copy__3->GetXaxis()->SetTitle("Track Multiplicity");
   h_errors_copy__3->GetXaxis()->SetLabelFont(42);
   h_errors_copy__3->GetXaxis()->SetLabelSize(0.045);
   h_errors_copy__3->GetXaxis()->SetTitleSize(0.05);
   h_errors_copy__3->GetXaxis()->SetTitleOffset(0.93);
   h_errors_copy__3->GetXaxis()->SetTitleFont(42);
   h_errors_copy__3->GetYaxis()->SetTitle(" Events/bin");
   h_errors_copy__3->GetYaxis()->SetLabelFont(42);
   h_errors_copy__3->GetYaxis()->SetLabelSize(0.045);
   h_errors_copy__3->GetYaxis()->SetTitleSize(0.05);
   h_errors_copy__3->GetYaxis()->SetTitleOffset(1.06);
   h_errors_copy__3->GetYaxis()->SetTitleFont(42);
   h_errors_copy__3->GetZaxis()->SetLabelFont(42);
   h_errors_copy__3->GetZaxis()->SetLabelSize(0.035);
   h_errors_copy__3->GetZaxis()->SetTitleSize(0.035);
   h_errors_copy__3->GetZaxis()->SetTitleFont(42);
   h_errors_copy__3->Draw("sameaxis");
   
   leg = new TLegend(0.54,0.815,0.885,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(32);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("NULL","NuMI RHC, 1.5 #times 10^{21} POT","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   leg = new TLegend(0.45,0.9,0.89,0.985,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(32);
   leg->SetTextFont(62);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("NULL","MicroBooNE Simulation, Preliminary","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   p_plot->Modified();
   c->cd();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
