void background_fhc_track_multi_ByPureKaonType()
{
//=========Macro generated from canvas: c/c
//=========  (Wed Feb 14 05:46:31 2024) by ROOT version 6.12/06
   TCanvas *c = new TCanvas("c", "c",0,0,800,600);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: p_legend
   TPad *p_legend = new TPad("p_legend", "p_legend",0,0.85,1,1);
   p_legend->Draw();
   p_legend->cd();
   p_legend->Range(0,0,1,1);
   p_legend->SetFillColor(0);
   p_legend->SetBorderMode(0);
   p_legend->SetBorderSize(2);
   p_legend->SetBottomMargin(0);
   p_legend->SetFrameBorderMode(0);
   
   TLegend *leg = new TLegend(0.1,0,0.9,1,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaon","#nu_{#mu}CCK^{0}0#pi","F");

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaonMultiPion","#nu_{#mu}CCK^{0}N#pi","F");

   ci = TColor::GetColor("#00cc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaonHyperon","#nu_{#mu}CCK^{0}Y0#pi","F");

   ci = TColor::GetColor("#009900");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaonHyperonMultiPion","#nu_{#mu}CCK^{0}YN#pi","F");

   ci = TColor::GetColor("#006600");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonOtherNuMuCC","Other #nu_{#mu}CC","F");
   entry->SetFillColor(30);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonNuECC","#nu_{e}CC","F");

   ci = TColor::GetColor("#cc33ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonNC","NC","F");

   ci = TColor::GetColor("#ffcc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonOutFV","Out FV","F");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonBeamOff","Beam-Off","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3004);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonOther","Other","F");

   ci = TColor::GetColor("#cc0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   p_legend->Modified();
   c->cd();
  
// ------------>Primitives in pad: p_plot
   TPad *p_plot = new TPad("p_plot", "p_plot",0,0,1,0.85);
   p_plot->Draw();
   p_plot->cd();
   p_plot->Range(-1,-13966.43,9,125697.9);
   p_plot->SetFillColor(0);
   p_plot->SetBorderMode(0);
   p_plot->SetBorderSize(2);
   p_plot->SetTopMargin(0.01);
   p_plot->SetFrameBorderMode(0);
   p_plot->SetFrameBorderMode(0);
   
   TH1D *h_errors__1 = new TH1D("h_errors__1","",8,0,8);
   h_errors__1->SetBinContent(1,12557.62);
   h_errors__1->SetBinContent(2,98571.44);
   h_errors__1->SetBinContent(3,90990.22);
   h_errors__1->SetBinContent(4,32500.38);
   h_errors__1->SetBinContent(5,11201.03);
   h_errors__1->SetBinContent(6,3969.161);
   h_errors__1->SetBinContent(7,1360.94);
   h_errors__1->SetBinContent(8,487.6383);
   h_errors__1->SetBinContent(9,228.7313);
   h_errors__1->SetBinError(1,309.9665);
   h_errors__1->SetBinError(2,869.5513);
   h_errors__1->SetBinError(3,793.2021);
   h_errors__1->SetBinError(4,422.7864);
   h_errors__1->SetBinError(5,221.4148);
   h_errors__1->SetBinError(6,124.4156);
   h_errors__1->SetBinError(7,67.64885);
   h_errors__1->SetBinError(8,40.14652);
   h_errors__1->SetBinError(9,26.6333);
   h_errors__1->SetMinimum(0);
   h_errors__1->SetMaximum(124301.2);
   h_errors__1->SetEntries(101491);
   h_errors__1->SetStats(0);
   h_errors__1->SetFillColor(1);
   h_errors__1->SetFillStyle(3253);

   ci = TColor::GetColor("#000099");
   h_errors__1->SetLineColor(ci);
   h_errors__1->GetXaxis()->SetTitle("Track Multiplicity");
   h_errors__1->GetXaxis()->SetLabelFont(42);
   h_errors__1->GetXaxis()->SetLabelSize(0.045);
   h_errors__1->GetXaxis()->SetTitleSize(0.05);
   h_errors__1->GetXaxis()->SetTitleOffset(0.93);
   h_errors__1->GetXaxis()->SetTitleFont(42);
   h_errors__1->GetYaxis()->SetTitle(" Events/bin");
   h_errors__1->GetYaxis()->SetLabelFont(42);
   h_errors__1->GetYaxis()->SetLabelSize(0.045);
   h_errors__1->GetYaxis()->SetTitleSize(0.05);
   h_errors__1->GetYaxis()->SetTitleOffset(1.06);
   h_errors__1->GetYaxis()->SetTitleFont(42);
   h_errors__1->GetZaxis()->SetLabelFont(42);
   h_errors__1->GetZaxis()->SetLabelSize(0.035);
   h_errors__1->GetZaxis()->SetTitleSize(0.035);
   h_errors__1->GetZaxis()->SetTitleFont(42);
   h_errors__1->Draw("E2");
   
   THStack *hs = new THStack();
   hs->SetName("hs");
   hs->SetTitle("");
   
   TH1F *hs_stack_1 = new TH1F("hs_stack_1","",8,0,8);
   hs_stack_1->SetMinimum(0);
   hs_stack_1->SetMaximum(103500);
   hs_stack_1->SetDirectory(0);
   hs_stack_1->SetStats(0);

   ci = TColor::GetColor("#000099");
   hs_stack_1->SetLineColor(ci);
   hs_stack_1->GetXaxis()->SetLabelFont(42);
   hs_stack_1->GetXaxis()->SetLabelSize(0.035);
   hs_stack_1->GetXaxis()->SetTitleSize(0.035);
   hs_stack_1->GetXaxis()->SetTitleFont(42);
   hs_stack_1->GetYaxis()->SetLabelFont(42);
   hs_stack_1->GetYaxis()->SetLabelSize(0.035);
   hs_stack_1->GetYaxis()->SetTitleSize(0.035);
   hs_stack_1->GetYaxis()->SetTitleOffset(0);
   hs_stack_1->GetYaxis()->SetTitleFont(42);
   hs_stack_1->GetZaxis()->SetLabelFont(42);
   hs_stack_1->GetZaxis()->SetLabelSize(0.035);
   hs_stack_1->GetZaxis()->SetTitleSize(0.035);
   hs_stack_1->GetZaxis()->SetTitleFont(42);
   hs->SetHistogram(hs_stack_1);
   
   
   TH1D *h_PureKaonSignalNuMuCCKaon_stack_1 = new TH1D("h_PureKaonSignalNuMuCCKaon_stack_1","",8,0,8);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(1,0.02125384);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(2,0.1168961);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(3,0.2603596);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(4,0.5047788);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(5,0.611048);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(6,0.4091365);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(7,0.2337923);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(8,0.1328365);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(9,0.08501538);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(1,0.01062692);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(2,0.02492234);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(3,0.03719423);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(4,0.05178921);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(5,0.05698052);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(6,0.04662543);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(7,0.03524551);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(8,0.02656731);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(9,0.02125384);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetEntries(453);

   ci = TColor::GetColor("#00ff00");
   h_PureKaonSignalNuMuCCKaon_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaon_stack_1->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaon_stack_1,"HIST");
   
   TH1D *h_PureKaonSignalNuMuCCKaonMultiPion_stack_2 = new TH1D("h_PureKaonSignalNuMuCCKaonMultiPion_stack_2","",8,0,8);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(1,0.07970192);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(2,0.2178519);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(3,0.5738538);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(4,0.818273);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(5,1.030811);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(6,0.887348);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(7,0.5100923);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(8,0.3613154);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(9,0.2231654);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(1,0.02057895);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(2,0.03402275);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(3,0.05521911);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(4,0.06593832);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(5,0.07400795);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(6,0.06866505);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(7,0.05206107);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(8,0.04381592);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(9,0.03443516);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetEntries(947);

   ci = TColor::GetColor("#00cc00");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaonMultiPion_stack_2,"HIST");
   
   TH1D *h_PureKaonSignalNuMuCCKaonHyperon_stack_3 = new TH1D("h_PureKaonSignalNuMuCCKaonHyperon_stack_3","",8,0,8);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(1,0.06907499);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(2,0.6907499);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(3,1.817204);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(4,2.90115);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(5,2.980852);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(6,2.268848);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(7,1.1052);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(8,0.6057346);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(9,0.2656731);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(1,0.01915796);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(2,0.06058278);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(3,0.09826312);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(4,0.1241577);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(5,0.1258517);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(6,0.1097972);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(7,0.07663183);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(8,0.05673224);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(9,0.03757184);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetEntries(2392);

   ci = TColor::GetColor("#009900");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaonHyperon_stack_3,"HIST");
   
   TH1D *h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4 = new TH1D("h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4","",8,0,8);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(1,0.1647173);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(2,1.238036);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(3,3.097748);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(4,4.468621);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(5,4.686473);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(6,3.857573);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(7,2.454819);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(8,1.291171);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(9,0.818273);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(1,0.0295841);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(2,0.08110646);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(3,0.1282956);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(4,0.1540904);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(5,0.1578017);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(6,0.143168);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(7,0.1142085);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(8,0.08282866);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(9,0.06593832);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetEntries(4160);

   ci = TColor::GetColor("#006600");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4,"HIST");
   
   TH1D *h_PureKaonOtherNuMuCC_stack_5 = new TH1D("h_PureKaonOtherNuMuCC_stack_5","",8,0,8);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(1,500.4965);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(2,16760.33);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(3,28502.46);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(4,15658.24);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(5,6792.938);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(6,2652.555);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(7,1008.138);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(8,379.426);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(9,159.4095);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(1,36.32815);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(2,210.4051);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(3,274.3729);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(4,203.3166);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(5,133.8569);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(6,83.60452);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(7,51.5116);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(8,31.59958);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(9,20.46866);
   h_PureKaonOtherNuMuCC_stack_5->SetEntries(39672);
   h_PureKaonOtherNuMuCC_stack_5->SetFillColor(30);

   ci = TColor::GetColor("#000099");
   h_PureKaonOtherNuMuCC_stack_5->SetLineColor(ci);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetLabelFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetTitleFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetLabelFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitleOffset(0);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitleFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetLabelFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonOtherNuMuCC_stack_5,"HIST");
   
   TH1D *h_PureKaonNuECC_stack_6 = new TH1D("h_PureKaonNuECC_stack_6","",8,0,8);
   h_PureKaonNuECC_stack_6->SetBinContent(1,491.7614);
   h_PureKaonNuECC_stack_6->SetBinContent(2,1308.75);
   h_PureKaonNuECC_stack_6->SetBinContent(3,983.8097);
   h_PureKaonNuECC_stack_6->SetBinContent(4,450.1194);
   h_PureKaonNuECC_stack_6->SetBinContent(5,130.0766);
   h_PureKaonNuECC_stack_6->SetBinContent(6,66.38609);
   h_PureKaonNuECC_stack_6->SetBinContent(7,18.6355);
   h_PureKaonNuECC_stack_6->SetBinContent(8,2.700927);
   h_PureKaonNuECC_stack_6->SetBinContent(9,0.005313461);
   h_PureKaonNuECC_stack_6->SetBinError(1,36.03862);
   h_PureKaonNuECC_stack_6->SetBinError(2,58.79147);
   h_PureKaonNuECC_stack_6->SetBinError(3,50.96633);
   h_PureKaonNuECC_stack_6->SetBinError(4,34.45378);
   h_PureKaonNuECC_stack_6->SetBinError(5,18.49744);
   h_PureKaonNuECC_stack_6->SetBinError(6,13.21246);
   h_PureKaonNuECC_stack_6->SetBinError(7,6.991394);
   h_PureKaonNuECC_stack_6->SetBinError(8,2.642537);
   h_PureKaonNuECC_stack_6->SetBinError(9,0.005313461);
   h_PureKaonNuECC_stack_6->SetEntries(2042);

   ci = TColor::GetColor("#cc33ff");
   h_PureKaonNuECC_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonNuECC_stack_6->SetLineColor(ci);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonNuECC_stack_6->GetXaxis()->SetLabelFont(42);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetTitleFont(42);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonNuECC_stack_6->GetYaxis()->SetLabelFont(42);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitleOffset(0);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitleFont(42);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetLabelFont(42);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonNuECC_stack_6,"HIST");
   
   TH1D *h_PureKaonNC_stack_7 = new TH1D("h_PureKaonNC_stack_7","",8,0,8);
   h_PureKaonNC_stack_7->SetBinContent(1,1519.907);
   h_PureKaonNC_stack_7->SetBinContent(2,6588.858);
   h_PureKaonNC_stack_7->SetBinContent(3,4548.223);
   h_PureKaonNC_stack_7->SetBinContent(4,2260.944);
   h_PureKaonNC_stack_7->SetBinContent(5,975.7125);
   h_PureKaonNC_stack_7->SetBinContent(6,356.2743);
   h_PureKaonNC_stack_7->SetBinContent(7,142.1555);
   h_PureKaonNC_stack_7->SetBinContent(8,59.02719);
   h_PureKaonNC_stack_7->SetBinContent(9,37.3879);
   h_PureKaonNC_stack_7->SetBinError(1,63.30942);
   h_PureKaonNC_stack_7->SetBinError(2,131.8596);
   h_PureKaonNC_stack_7->SetBinError(3,109.464);
   h_PureKaonNC_stack_7->SetBinError(4,77.08656);
   h_PureKaonNC_stack_7->SetBinError(5,50.55404);
   h_PureKaonNC_stack_7->SetBinError(6,30.47497);
   h_PureKaonNC_stack_7->SetBinError(7,19.23783);
   h_PureKaonNC_stack_7->SetBinError(8,12.39452);
   h_PureKaonNC_stack_7->SetBinError(9,9.887356);
   h_PureKaonNC_stack_7->SetEntries(16775);

   ci = TColor::GetColor("#ffcc00");
   h_PureKaonNC_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonNC_stack_7->SetLineColor(ci);
   h_PureKaonNC_stack_7->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonNC_stack_7->GetXaxis()->SetLabelFont(42);
   h_PureKaonNC_stack_7->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonNC_stack_7->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonNC_stack_7->GetXaxis()->SetTitleFont(42);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonNC_stack_7->GetYaxis()->SetLabelFont(42);
   h_PureKaonNC_stack_7->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitleOffset(0);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitleFont(42);
   h_PureKaonNC_stack_7->GetZaxis()->SetLabelFont(42);
   h_PureKaonNC_stack_7->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonNC_stack_7->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonNC_stack_7->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonNC_stack_7,"HIST");
   
   TH1D *h_PureKaonOutFV_stack_8 = new TH1D("h_PureKaonOutFV_stack_8","",8,0,8);
   h_PureKaonOutFV_stack_8->SetBinContent(1,1612.776);
   h_PureKaonOutFV_stack_8->SetBinContent(2,9339.834);
   h_PureKaonOutFV_stack_8->SetBinContent(3,6968.654);
   h_PureKaonOutFV_stack_8->SetBinContent(4,2101.58);
   h_PureKaonOutFV_stack_8->SetBinContent(5,695.1827);
   h_PureKaonOutFV_stack_8->SetBinContent(6,191.4381);
   h_PureKaonOutFV_stack_8->SetBinContent(7,56.06059);
   h_PureKaonOutFV_stack_8->SetBinContent(8,8.108094);
   h_PureKaonOutFV_stack_8->SetBinContent(9,10.6443);
   h_PureKaonOutFV_stack_8->SetBinError(1,65.21103);
   h_PureKaonOutFV_stack_8->SetBinError(2,156.9777);
   h_PureKaonOutFV_stack_8->SetBinError(3,135.5674);
   h_PureKaonOutFV_stack_8->SetBinError(4,74.41309);
   h_PureKaonOutFV_stack_8->SetBinError(5,42.77243);
   h_PureKaonOutFV_stack_8->SetBinError(6,22.42231);
   h_PureKaonOutFV_stack_8->SetBinError(7,12.10948);
   h_PureKaonOutFV_stack_8->SetBinError(8,4.577012);
   h_PureKaonOutFV_stack_8->SetBinError(9,5.284995);
   h_PureKaonOutFV_stack_8->SetEntries(16213);

   ci = TColor::GetColor("#cccccc");
   h_PureKaonOutFV_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonOutFV_stack_8->SetLineColor(ci);
   h_PureKaonOutFV_stack_8->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonOutFV_stack_8->GetXaxis()->SetLabelFont(42);
   h_PureKaonOutFV_stack_8->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonOutFV_stack_8->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonOutFV_stack_8->GetXaxis()->SetTitleFont(42);
   h_PureKaonOutFV_stack_8->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonOutFV_stack_8->GetYaxis()->SetLabelFont(42);
   h_PureKaonOutFV_stack_8->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonOutFV_stack_8->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonOutFV_stack_8->GetYaxis()->SetTitleOffset(0);
   h_PureKaonOutFV_stack_8->GetYaxis()->SetTitleFont(42);
   h_PureKaonOutFV_stack_8->GetZaxis()->SetLabelFont(42);
   h_PureKaonOutFV_stack_8->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonOutFV_stack_8->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonOutFV_stack_8->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonOutFV_stack_8,"HIST");
   
   TH1D *h_PureKaonBeamOff_stack_9 = new TH1D("h_PureKaonBeamOff_stack_9","",8,0,8);
   h_PureKaonBeamOff_stack_9->SetBinContent(1,1703.141);
   h_PureKaonBeamOff_stack_9->SetBinContent(2,11553.46);
   h_PureKaonBeamOff_stack_9->SetBinContent(3,8394.616);
   h_PureKaonBeamOff_stack_9->SetBinContent(4,2076.937);
   h_PureKaonBeamOff_stack_9->SetBinContent(5,510.6791);
   h_PureKaonBeamOff_stack_9->SetBinContent(6,155.3096);
   h_PureKaonBeamOff_stack_9->SetBinContent(7,23.6913);
   h_PureKaonBeamOff_stack_9->SetBinContent(9,7.897099);
   h_PureKaonBeamOff_stack_9->SetBinError(1,66.95738);
   h_PureKaonBeamOff_stack_9->SetBinError(2,174.393);
   h_PureKaonBeamOff_stack_9->SetBinError(3,148.653);
   h_PureKaonBeamOff_stack_9->SetBinError(4,73.94092);
   h_PureKaonBeamOff_stack_9->SetBinError(5,36.66462);
   h_PureKaonBeamOff_stack_9->SetBinError(6,20.21959);
   h_PureKaonBeamOff_stack_9->SetBinError(7,7.897099);
   h_PureKaonBeamOff_stack_9->SetBinError(9,4.559392);
   h_PureKaonBeamOff_stack_9->SetEntries(9328);
   h_PureKaonBeamOff_stack_9->SetFillColor(1);
   h_PureKaonBeamOff_stack_9->SetFillStyle(3004);

   ci = TColor::GetColor("#000099");
   h_PureKaonBeamOff_stack_9->SetLineColor(ci);
   h_PureKaonBeamOff_stack_9->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonBeamOff_stack_9->GetXaxis()->SetLabelFont(42);
   h_PureKaonBeamOff_stack_9->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonBeamOff_stack_9->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonBeamOff_stack_9->GetXaxis()->SetTitleFont(42);
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetLabelFont(42);
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetTitleOffset(0);
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetTitleFont(42);
   h_PureKaonBeamOff_stack_9->GetZaxis()->SetLabelFont(42);
   h_PureKaonBeamOff_stack_9->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonBeamOff_stack_9->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonBeamOff_stack_9->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonBeamOff_stack_9,"HIST");
   
   TH1D *h_PureKaonOther_stack_10 = new TH1D("h_PureKaonOther_stack_10","",8,0,8);
   h_PureKaonOther_stack_10->SetBinContent(1,6729.201);
   h_PureKaonOther_stack_10->SetBinContent(2,53017.94);
   h_PureKaonOther_stack_10->SetBinContent(3,41586.7);
   h_PureKaonOther_stack_10->SetBinContent(4,9943.863);
   h_PureKaonOther_stack_10->SetBinContent(5,2087.132);
   h_PureKaonOther_stack_10->SetBinContent(6,539.7755);
   h_PureKaonOther_stack_10->SetBinContent(7,107.9551);
   h_PureKaonOther_stack_10->SetBinContent(8,35.98503);
   h_PureKaonOther_stack_10->SetBinContent(9,11.99501);
   h_PureKaonOther_stack_10->SetBinError(1,284.1071);
   h_PureKaonOther_stack_10->SetBinError(2,797.4652);
   h_PureKaonOther_stack_10->SetBinError(3,706.281);
   h_PureKaonOther_stack_10->SetBinError(4,345.3646);
   h_PureKaonOther_stack_10->SetBinError(5,158.225);
   h_PureKaonOther_stack_10->SetBinError(6,80.46497);
   h_PureKaonOther_stack_10->SetBinError(7,35.98503);
   h_PureKaonOther_stack_10->SetBinError(8,20.77597);
   h_PureKaonOther_stack_10->SetBinError(9,11.99501);
   h_PureKaonOther_stack_10->SetEntries(9509);

   ci = TColor::GetColor("#cc0000");
   h_PureKaonOther_stack_10->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonOther_stack_10->SetLineColor(ci);
   h_PureKaonOther_stack_10->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonOther_stack_10->GetXaxis()->SetLabelFont(42);
   h_PureKaonOther_stack_10->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonOther_stack_10->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonOther_stack_10->GetXaxis()->SetTitleFont(42);
   h_PureKaonOther_stack_10->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonOther_stack_10->GetYaxis()->SetLabelFont(42);
   h_PureKaonOther_stack_10->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonOther_stack_10->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonOther_stack_10->GetYaxis()->SetTitleOffset(0);
   h_PureKaonOther_stack_10->GetYaxis()->SetTitleFont(42);
   h_PureKaonOther_stack_10->GetZaxis()->SetLabelFont(42);
   h_PureKaonOther_stack_10->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonOther_stack_10->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonOther_stack_10->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonOther_stack_10,"HIST");
   hs->Draw("hist same");
   
   TH1D *h_errors__2 = new TH1D("h_errors__2","",8,0,8);
   h_errors__2->SetBinContent(1,12557.62);
   h_errors__2->SetBinContent(2,98571.44);
   h_errors__2->SetBinContent(3,90990.22);
   h_errors__2->SetBinContent(4,32500.38);
   h_errors__2->SetBinContent(5,11201.03);
   h_errors__2->SetBinContent(6,3969.161);
   h_errors__2->SetBinContent(7,1360.94);
   h_errors__2->SetBinContent(8,487.6383);
   h_errors__2->SetBinContent(9,228.7313);
   h_errors__2->SetBinError(1,309.9665);
   h_errors__2->SetBinError(2,869.5513);
   h_errors__2->SetBinError(3,793.2021);
   h_errors__2->SetBinError(4,422.7864);
   h_errors__2->SetBinError(5,221.4148);
   h_errors__2->SetBinError(6,124.4156);
   h_errors__2->SetBinError(7,67.64885);
   h_errors__2->SetBinError(8,40.14652);
   h_errors__2->SetBinError(9,26.6333);
   h_errors__2->SetMinimum(0);
   h_errors__2->SetMaximum(124301.2);
   h_errors__2->SetEntries(101491);
   h_errors__2->SetStats(0);
   h_errors__2->SetFillColor(1);
   h_errors__2->SetFillStyle(3253);

   ci = TColor::GetColor("#000099");
   h_errors__2->SetLineColor(ci);
   h_errors__2->GetXaxis()->SetTitle("Track Multiplicity");
   h_errors__2->GetXaxis()->SetLabelFont(42);
   h_errors__2->GetXaxis()->SetLabelSize(0.045);
   h_errors__2->GetXaxis()->SetTitleSize(0.05);
   h_errors__2->GetXaxis()->SetTitleOffset(0.93);
   h_errors__2->GetXaxis()->SetTitleFont(42);
   h_errors__2->GetYaxis()->SetTitle(" Events/bin");
   h_errors__2->GetYaxis()->SetLabelFont(42);
   h_errors__2->GetYaxis()->SetLabelSize(0.045);
   h_errors__2->GetYaxis()->SetTitleSize(0.05);
   h_errors__2->GetYaxis()->SetTitleOffset(1.06);
   h_errors__2->GetYaxis()->SetTitleFont(42);
   h_errors__2->GetZaxis()->SetLabelFont(42);
   h_errors__2->GetZaxis()->SetLabelSize(0.035);
   h_errors__2->GetZaxis()->SetTitleSize(0.035);
   h_errors__2->GetZaxis()->SetTitleFont(42);
   h_errors__2->Draw("E2 same");
   
   TH1D *h_errors_copy__3 = new TH1D("h_errors_copy__3","",8,0,8);
   h_errors_copy__3->SetBinContent(1,12557.62);
   h_errors_copy__3->SetBinContent(2,98571.44);
   h_errors_copy__3->SetBinContent(3,90990.22);
   h_errors_copy__3->SetBinContent(4,32500.38);
   h_errors_copy__3->SetBinContent(5,11201.03);
   h_errors_copy__3->SetBinContent(6,3969.161);
   h_errors_copy__3->SetBinContent(7,1360.94);
   h_errors_copy__3->SetBinContent(8,487.6383);
   h_errors_copy__3->SetBinContent(9,228.7313);
   h_errors_copy__3->SetBinError(1,309.9665);
   h_errors_copy__3->SetBinError(2,869.5513);
   h_errors_copy__3->SetBinError(3,793.2021);
   h_errors_copy__3->SetBinError(4,422.7864);
   h_errors_copy__3->SetBinError(5,221.4148);
   h_errors_copy__3->SetBinError(6,124.4156);
   h_errors_copy__3->SetBinError(7,67.64885);
   h_errors_copy__3->SetBinError(8,40.14652);
   h_errors_copy__3->SetBinError(9,26.6333);
   h_errors_copy__3->SetMinimum(0);
   h_errors_copy__3->SetMaximum(124301.2);
   h_errors_copy__3->SetEntries(101491);
   h_errors_copy__3->SetDirectory(0);
   h_errors_copy__3->SetStats(0);
   h_errors_copy__3->SetFillColor(1);
   h_errors_copy__3->SetFillStyle(3253);

   ci = TColor::GetColor("#000099");
   h_errors_copy__3->SetLineColor(ci);
   h_errors_copy__3->GetXaxis()->SetTitle("Track Multiplicity");
   h_errors_copy__3->GetXaxis()->SetLabelFont(42);
   h_errors_copy__3->GetXaxis()->SetLabelSize(0.045);
   h_errors_copy__3->GetXaxis()->SetTitleSize(0.05);
   h_errors_copy__3->GetXaxis()->SetTitleOffset(0.93);
   h_errors_copy__3->GetXaxis()->SetTitleFont(42);
   h_errors_copy__3->GetYaxis()->SetTitle(" Events/bin");
   h_errors_copy__3->GetYaxis()->SetLabelFont(42);
   h_errors_copy__3->GetYaxis()->SetLabelSize(0.045);
   h_errors_copy__3->GetYaxis()->SetTitleSize(0.05);
   h_errors_copy__3->GetYaxis()->SetTitleOffset(1.06);
   h_errors_copy__3->GetYaxis()->SetTitleFont(42);
   h_errors_copy__3->GetZaxis()->SetLabelFont(42);
   h_errors_copy__3->GetZaxis()->SetLabelSize(0.035);
   h_errors_copy__3->GetZaxis()->SetTitleSize(0.035);
   h_errors_copy__3->GetZaxis()->SetTitleFont(42);
   h_errors_copy__3->Draw("sameaxis");
   
   leg = new TLegend(0.54,0.815,0.885,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(32);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("NULL","NuMI FHC, 1.2 #times 10^{21} POT","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   leg = new TLegend(0.45,0.9,0.89,0.985,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(32);
   leg->SetTextFont(62);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("NULL","MicroBooNE Simulation, Preliminary","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   p_plot->Modified();
   c->cd();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
