void shower_multi_rhc_fv_ByPureKaonType()
{
//=========Macro generated from canvas: c/c
//=========  (Wed Jan 10 05:43:11 2024) by ROOT version 6.12/06
   TCanvas *c = new TCanvas("c", "c",0,0,800,600);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: p_legend
   TPad *p_legend = new TPad("p_legend", "p_legend",0,0.85,1,1);
   p_legend->Draw();
   p_legend->cd();
   p_legend->Range(0,0,1,1);
   p_legend->SetFillColor(0);
   p_legend->SetBorderMode(0);
   p_legend->SetBorderSize(2);
   p_legend->SetBottomMargin(0);
   p_legend->SetFrameBorderMode(0);
   
   TLegend *leg = new TLegend(0.1,0,0.9,1,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaon","#nu_{#mu}CCK^{0}0#pi","F");

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaonMultiPion","#nu_{#mu}CCK^{0}N#pi","F");

   ci = TColor::GetColor("#00cc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaonHyperon","#nu_{#mu}CCK^{0}Y0#pi","F");

   ci = TColor::GetColor("#009900");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaonHyperonMultiPion","#nu_{#mu}CCK^{0}YN#pi","F");

   ci = TColor::GetColor("#006600");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonOtherNuMuCC","Other #nu_{#mu}CCK^{0}","F");
   entry->SetFillColor(30);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonNuECC","#nu_{e}CCK^{0}","F");

   ci = TColor::GetColor("#cc33ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonNC","NCK^{0}","F");

   ci = TColor::GetColor("#ffcc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonOutOfFV","Out FV","F");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   p_legend->Modified();
   c->cd();
  
// ------------>Primitives in pad: p_plot
   TPad *p_plot = new TPad("p_plot", "p_plot",0,0,1,0.85);
   p_plot->Draw();
   p_plot->cd();
   p_plot->Range(-1,-12.09528,9,108.8575);
   p_plot->SetFillColor(0);
   p_plot->SetBorderMode(0);
   p_plot->SetBorderSize(2);
   p_plot->SetTopMargin(0.01);
   p_plot->SetFrameBorderMode(0);
   p_plot->SetFrameBorderMode(0);
   
   TH1D *h_errors__1 = new TH1D("h_errors__1","",8,0,8);
   h_errors__1->SetBinContent(1,61.90716);
   h_errors__1->SetBinContent(2,85.19599);
   h_errors__1->SetBinContent(3,84.8864);
   h_errors__1->SetBinContent(4,64.89316);
   h_errors__1->SetBinContent(5,39.19755);
   h_errors__1->SetBinContent(6,20.69231);
   h_errors__1->SetBinContent(7,8.858146);
   h_errors__1->SetBinContent(8,3.914761);
   h_errors__1->SetBinContent(9,1.877488);
   h_errors__1->SetBinError(1,0.7862851);
   h_errors__1->SetBinError(2,0.9223998);
   h_errors__1->SetBinError(3,0.9207223);
   h_errors__1->SetBinError(4,0.8050244);
   h_errors__1->SetBinError(5,0.6256609);
   h_errors__1->SetBinError(6,0.4545839);
   h_errors__1->SetBinError(7,0.2974274);
   h_errors__1->SetBinError(8,0.1977253);
   h_errors__1->SetBinError(9,0.1369299);
   h_errors__1->SetMinimum(0);
   h_errors__1->SetMaximum(107.648);
   h_errors__1->SetEntries(37192);
   h_errors__1->SetStats(0);
   h_errors__1->SetFillColor(1);
   h_errors__1->SetFillStyle(3253);

   ci = TColor::GetColor("#000099");
   h_errors__1->SetLineColor(ci);
   h_errors__1->GetXaxis()->SetTitle("Shower Multiplicity");
   h_errors__1->GetXaxis()->SetLabelFont(42);
   h_errors__1->GetXaxis()->SetLabelSize(0.045);
   h_errors__1->GetXaxis()->SetTitleSize(0.05);
   h_errors__1->GetXaxis()->SetTitleOffset(0.93);
   h_errors__1->GetXaxis()->SetTitleFont(42);
   h_errors__1->GetYaxis()->SetTitle(" Events/bin");
   h_errors__1->GetYaxis()->SetLabelFont(42);
   h_errors__1->GetYaxis()->SetLabelSize(0.045);
   h_errors__1->GetYaxis()->SetTitleSize(0.05);
   h_errors__1->GetYaxis()->SetTitleOffset(1.06);
   h_errors__1->GetYaxis()->SetTitleFont(42);
   h_errors__1->GetZaxis()->SetLabelFont(42);
   h_errors__1->GetZaxis()->SetLabelSize(0.035);
   h_errors__1->GetZaxis()->SetTitleSize(0.035);
   h_errors__1->GetZaxis()->SetTitleFont(42);
   h_errors__1->Draw("E2");
   
   THStack *hs = new THStack();
   hs->SetName("hs");
   hs->SetTitle("");
   
   TH1F *hs_stack_1 = new TH1F("hs_stack_1","",8,0,8);
   hs_stack_1->SetMinimum(0);
   hs_stack_1->SetMaximum(89.45579);
   hs_stack_1->SetDirectory(0);
   hs_stack_1->SetStats(0);

   ci = TColor::GetColor("#000099");
   hs_stack_1->SetLineColor(ci);
   hs_stack_1->GetXaxis()->SetLabelFont(42);
   hs_stack_1->GetXaxis()->SetLabelSize(0.035);
   hs_stack_1->GetXaxis()->SetTitleSize(0.035);
   hs_stack_1->GetXaxis()->SetTitleFont(42);
   hs_stack_1->GetYaxis()->SetLabelFont(42);
   hs_stack_1->GetYaxis()->SetLabelSize(0.035);
   hs_stack_1->GetYaxis()->SetTitleSize(0.035);
   hs_stack_1->GetYaxis()->SetTitleOffset(0);
   hs_stack_1->GetYaxis()->SetTitleFont(42);
   hs_stack_1->GetZaxis()->SetLabelFont(42);
   hs_stack_1->GetZaxis()->SetLabelSize(0.035);
   hs_stack_1->GetZaxis()->SetTitleSize(0.035);
   hs_stack_1->GetZaxis()->SetTitleFont(42);
   hs->SetHistogram(hs_stack_1);
   
   
   TH1D *h_PureKaonSignalNuMuCCKaon_stack_1 = new TH1D("h_PureKaonSignalNuMuCCKaon_stack_1","",8,0,8);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(1,1.06857);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(2,2.0173);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(3,1.497995);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(4,1.018637);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(5,0.4693719);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(6,0.109853);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(7,0.06990645);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(8,0.009986636);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(9,0.01997327);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(1,0.1033026);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(2,0.1419368);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(3,0.1223108);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(4,0.1008601);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(5,0.06846493);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(6,0.03312192);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(7,0.02642215);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(8,0.009986636);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(9,0.01412324);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetEntries(629);

   ci = TColor::GetColor("#00ff00");
   h_PureKaonSignalNuMuCCKaon_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaon_stack_1->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetTitle("Shower Multiplicity");
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaon_stack_1,"HIST");
   
   TH1D *h_PureKaonSignalNuMuCCKaonMultiPion_stack_2 = new TH1D("h_PureKaonSignalNuMuCCKaonMultiPion_stack_2","",8,0,8);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(1,0.8089175);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(2,2.946058);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(3,3.635135);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(4,2.796258);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(5,1.867501);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(6,1.058583);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(7,0.4194387);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(8,0.2696392);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(9,0.1198396);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(1,0.08987972);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(2,0.1715261);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(3,0.1905329);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(4,0.1671084);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(5,0.1365652);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(6,0.1028187);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(7,0.0647208);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(8,0.05189208);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(9,0.03459472);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetEntries(1394);

   ci = TColor::GetColor("#00cc00");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetTitle("Shower Multiplicity");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaonMultiPion_stack_2,"HIST");
   
   TH1D *h_PureKaonSignalNuMuCCKaonHyperon_stack_3 = new TH1D("h_PureKaonSignalNuMuCCKaonHyperon_stack_3","",8,0,8);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(1,3.445389);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(2,7.050565);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(3,6.790912);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(4,3.764962);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(5,1.298263);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(6,0.5792249);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(7,0.1797594);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(8,0.04993318);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(9,0.02995991);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(1,0.1854935);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(2,0.2653515);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(3,0.2604196);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(4,0.1939054);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(5,0.1138652);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(6,0.07605595);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(7,0.04236971);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(8,0.0223308);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(9,0.01729736);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetEntries(2322);

   ci = TColor::GetColor("#009900");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetTitle("Shower Multiplicity");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaonHyperon_stack_3,"HIST");
   
   TH1D *h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4 = new TH1D("h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4","",8,0,8);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(1,3.944721);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(2,11.38476);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(3,15.06983);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(4,11.90407);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(5,7.090511);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(6,3.135804);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(7,1.468035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(8,0.5792249);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(9,0.2796258);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(1,0.1984805);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(2,0.3371876);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(3,0.3879393);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(4,0.3447921);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(5,0.2661022);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(6,0.1769636);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(7,0.1210815);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(8,0.07605595);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(9,0.05284431);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetEntries(5493);

   ci = TColor::GetColor("#006600");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetTitle("Shower Multiplicity");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4,"HIST");
   
   TH1D *h_PureKaonOtherNuMuCC_stack_5 = new TH1D("h_PureKaonOtherNuMuCC_stack_5","",8,0,8);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(1,7.360151);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(2,15.69899);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(3,21.27153);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(4,20.16302);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(5,14.78022);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(6,8.738306);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(7,4.014628);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(8,1.847528);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(9,0.9687037);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(1,0.2711146);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(2,0.3959547);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(3,0.4609024);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(4,0.4487323);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(5,0.3841936);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(6,0.2954087);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(7,0.2002314);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(8,0.1358329);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(9,0.09835696);
   h_PureKaonOtherNuMuCC_stack_5->SetEntries(9497);
   h_PureKaonOtherNuMuCC_stack_5->SetFillColor(30);

   ci = TColor::GetColor("#000099");
   h_PureKaonOtherNuMuCC_stack_5->SetLineColor(ci);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetTitle("Shower Multiplicity");
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetLabelFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetTitleFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetLabelFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitleOffset(0);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitleFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetLabelFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonOtherNuMuCC_stack_5,"HIST");
   
   TH1D *h_PureKaonNuECC_stack_6 = new TH1D("h_PureKaonNuECC_stack_6","",8,0,8);
   h_PureKaonNuECC_stack_6->SetBinContent(1,0.2097194);
   h_PureKaonNuECC_stack_6->SetBinContent(2,0.7789576);
   h_PureKaonNuECC_stack_6->SetBinContent(3,1.138476);
   h_PureKaonNuECC_stack_6->SetBinContent(4,1.088543);
   h_PureKaonNuECC_stack_6->SetBinContent(5,0.8288908);
   h_PureKaonNuECC_stack_6->SetBinContent(6,0.5792249);
   h_PureKaonNuECC_stack_6->SetBinContent(7,0.2696392);
   h_PureKaonNuECC_stack_6->SetBinContent(8,0.1398129);
   h_PureKaonNuECC_stack_6->SetBinContent(9,0.04993318);
   h_PureKaonNuECC_stack_6->SetBinError(1,0.04576451);
   h_PureKaonNuECC_stack_6->SetBinError(2,0.08819958);
   h_PureKaonNuECC_stack_6->SetBinError(3,0.1066281);
   h_PureKaonNuECC_stack_6->SetBinError(4,0.1042635);
   h_PureKaonNuECC_stack_6->SetBinError(5,0.09098258);
   h_PureKaonNuECC_stack_6->SetBinError(6,0.07605595);
   h_PureKaonNuECC_stack_6->SetBinError(7,0.05189208);
   h_PureKaonNuECC_stack_6->SetBinError(8,0.03736657);
   h_PureKaonNuECC_stack_6->SetBinError(9,0.0223308);
   h_PureKaonNuECC_stack_6->SetEntries(509);

   ci = TColor::GetColor("#cc33ff");
   h_PureKaonNuECC_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonNuECC_stack_6->SetLineColor(ci);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetTitle("Shower Multiplicity");
   h_PureKaonNuECC_stack_6->GetXaxis()->SetLabelFont(42);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetTitleFont(42);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonNuECC_stack_6->GetYaxis()->SetLabelFont(42);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitleOffset(0);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitleFont(42);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetLabelFont(42);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonNuECC_stack_6,"HIST");
   
   TH1D *h_PureKaonNC_stack_7 = new TH1D("h_PureKaonNC_stack_7","",8,0,8);
   h_PureKaonNC_stack_7->SetBinContent(1,10.59582);
   h_PureKaonNC_stack_7->SetBinContent(2,21.74091);
   h_PureKaonNC_stack_7->SetBinContent(3,23.82811);
   h_PureKaonNC_stack_7->SetBinContent(4,18.73493);
   h_PureKaonNC_stack_7->SetBinContent(5,10.58583);
   h_PureKaonNC_stack_7->SetBinContent(6,5.622476);
   h_PureKaonNC_stack_7->SetBinContent(7,2.13714);
   h_PureKaonNC_stack_7->SetBinContent(8,0.8588507);
   h_PureKaonNC_stack_7->SetBinContent(9,0.3695055);
   h_PureKaonNC_stack_7->SetBinError(1,0.3252946);
   h_PureKaonNC_stack_7->SetBinError(2,0.4659598);
   h_PureKaonNC_stack_7->SetBinError(3,0.4878142);
   h_PureKaonNC_stack_7->SetBinError(4,0.4325493);
   h_PureKaonNC_stack_7->SetBinError(5,0.3251413);
   h_PureKaonNC_stack_7->SetBinError(6,0.2369591);
   h_PureKaonNC_stack_7->SetBinError(7,0.1460919);
   h_PureKaonNC_stack_7->SetBinError(8,0.09261225);
   h_PureKaonNC_stack_7->SetBinError(9,0.06074633);
   h_PureKaonNC_stack_7->SetEntries(9460);

   ci = TColor::GetColor("#ffcc00");
   h_PureKaonNC_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonNC_stack_7->SetLineColor(ci);
   h_PureKaonNC_stack_7->GetXaxis()->SetTitle("Shower Multiplicity");
   h_PureKaonNC_stack_7->GetXaxis()->SetLabelFont(42);
   h_PureKaonNC_stack_7->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonNC_stack_7->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonNC_stack_7->GetXaxis()->SetTitleFont(42);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonNC_stack_7->GetYaxis()->SetLabelFont(42);
   h_PureKaonNC_stack_7->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitleOffset(0);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitleFont(42);
   h_PureKaonNC_stack_7->GetZaxis()->SetLabelFont(42);
   h_PureKaonNC_stack_7->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonNC_stack_7->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonNC_stack_7->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonNC_stack_7,"HIST");
   
   TH1D *h_PureKaonOutOfFV_stack_8 = new TH1D("h_PureKaonOutOfFV_stack_8","",8,0,8);
   h_PureKaonOutOfFV_stack_8->SetBinContent(1,34.47387);
   h_PureKaonOutOfFV_stack_8->SetBinContent(2,23.57845);
   h_PureKaonOutOfFV_stack_8->SetBinContent(3,11.6544);
   h_PureKaonOutOfFV_stack_8->SetBinContent(4,5.422743);
   h_PureKaonOutOfFV_stack_8->SetBinContent(5,2.276953);
   h_PureKaonOutOfFV_stack_8->SetBinContent(6,0.8688373);
   h_PureKaonOutOfFV_stack_8->SetBinContent(7,0.2995991);
   h_PureKaonOutOfFV_stack_8->SetBinContent(8,0.1597862);
   h_PureKaonOutOfFV_stack_8->SetBinContent(9,0.03994654);
   h_PureKaonOutOfFV_stack_8->SetBinError(1,0.586752);
   h_PureKaonOutOfFV_stack_8->SetBinError(2,0.4852519);
   h_PureKaonOutOfFV_stack_8->SetBinError(3,0.3411573);
   h_PureKaonOutOfFV_stack_8->SetBinError(4,0.2327122);
   h_PureKaonOutOfFV_stack_8->SetBinError(5,0.1507949);
   h_PureKaonOutOfFV_stack_8->SetBinError(6,0.09314914);
   h_PureKaonOutOfFV_stack_8->SetBinError(7,0.05469906);
   h_PureKaonOutOfFV_stack_8->SetBinError(8,0.03994654);
   h_PureKaonOutOfFV_stack_8->SetBinError(9,0.01997327);
   h_PureKaonOutOfFV_stack_8->SetEntries(7888);

   ci = TColor::GetColor("#cccccc");
   h_PureKaonOutOfFV_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonOutOfFV_stack_8->SetLineColor(ci);
   h_PureKaonOutOfFV_stack_8->GetXaxis()->SetTitle("Shower Multiplicity");
   h_PureKaonOutOfFV_stack_8->GetXaxis()->SetLabelFont(42);
   h_PureKaonOutOfFV_stack_8->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonOutOfFV_stack_8->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonOutOfFV_stack_8->GetXaxis()->SetTitleFont(42);
   h_PureKaonOutOfFV_stack_8->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonOutOfFV_stack_8->GetYaxis()->SetLabelFont(42);
   h_PureKaonOutOfFV_stack_8->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonOutOfFV_stack_8->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonOutOfFV_stack_8->GetYaxis()->SetTitleOffset(0);
   h_PureKaonOutOfFV_stack_8->GetYaxis()->SetTitleFont(42);
   h_PureKaonOutOfFV_stack_8->GetZaxis()->SetLabelFont(42);
   h_PureKaonOutOfFV_stack_8->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonOutOfFV_stack_8->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonOutOfFV_stack_8->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonOutOfFV_stack_8,"HIST");
   hs->Draw("hist same");
   
   TH1D *h_errors__2 = new TH1D("h_errors__2","",8,0,8);
   h_errors__2->SetBinContent(1,61.90716);
   h_errors__2->SetBinContent(2,85.19599);
   h_errors__2->SetBinContent(3,84.8864);
   h_errors__2->SetBinContent(4,64.89316);
   h_errors__2->SetBinContent(5,39.19755);
   h_errors__2->SetBinContent(6,20.69231);
   h_errors__2->SetBinContent(7,8.858146);
   h_errors__2->SetBinContent(8,3.914761);
   h_errors__2->SetBinContent(9,1.877488);
   h_errors__2->SetBinError(1,0.7862851);
   h_errors__2->SetBinError(2,0.9223998);
   h_errors__2->SetBinError(3,0.9207223);
   h_errors__2->SetBinError(4,0.8050244);
   h_errors__2->SetBinError(5,0.6256609);
   h_errors__2->SetBinError(6,0.4545839);
   h_errors__2->SetBinError(7,0.2974274);
   h_errors__2->SetBinError(8,0.1977253);
   h_errors__2->SetBinError(9,0.1369299);
   h_errors__2->SetMinimum(0);
   h_errors__2->SetMaximum(107.648);
   h_errors__2->SetEntries(37192);
   h_errors__2->SetStats(0);
   h_errors__2->SetFillColor(1);
   h_errors__2->SetFillStyle(3253);

   ci = TColor::GetColor("#000099");
   h_errors__2->SetLineColor(ci);
   h_errors__2->GetXaxis()->SetTitle("Shower Multiplicity");
   h_errors__2->GetXaxis()->SetLabelFont(42);
   h_errors__2->GetXaxis()->SetLabelSize(0.045);
   h_errors__2->GetXaxis()->SetTitleSize(0.05);
   h_errors__2->GetXaxis()->SetTitleOffset(0.93);
   h_errors__2->GetXaxis()->SetTitleFont(42);
   h_errors__2->GetYaxis()->SetTitle(" Events/bin");
   h_errors__2->GetYaxis()->SetLabelFont(42);
   h_errors__2->GetYaxis()->SetLabelSize(0.045);
   h_errors__2->GetYaxis()->SetTitleSize(0.05);
   h_errors__2->GetYaxis()->SetTitleOffset(1.06);
   h_errors__2->GetYaxis()->SetTitleFont(42);
   h_errors__2->GetZaxis()->SetLabelFont(42);
   h_errors__2->GetZaxis()->SetLabelSize(0.035);
   h_errors__2->GetZaxis()->SetTitleSize(0.035);
   h_errors__2->GetZaxis()->SetTitleFont(42);
   h_errors__2->Draw("E2 same");
   
   TH1D *h_errors_copy__3 = new TH1D("h_errors_copy__3","",8,0,8);
   h_errors_copy__3->SetBinContent(1,61.90716);
   h_errors_copy__3->SetBinContent(2,85.19599);
   h_errors_copy__3->SetBinContent(3,84.8864);
   h_errors_copy__3->SetBinContent(4,64.89316);
   h_errors_copy__3->SetBinContent(5,39.19755);
   h_errors_copy__3->SetBinContent(6,20.69231);
   h_errors_copy__3->SetBinContent(7,8.858146);
   h_errors_copy__3->SetBinContent(8,3.914761);
   h_errors_copy__3->SetBinContent(9,1.877488);
   h_errors_copy__3->SetBinError(1,0.7862851);
   h_errors_copy__3->SetBinError(2,0.9223998);
   h_errors_copy__3->SetBinError(3,0.9207223);
   h_errors_copy__3->SetBinError(4,0.8050244);
   h_errors_copy__3->SetBinError(5,0.6256609);
   h_errors_copy__3->SetBinError(6,0.4545839);
   h_errors_copy__3->SetBinError(7,0.2974274);
   h_errors_copy__3->SetBinError(8,0.1977253);
   h_errors_copy__3->SetBinError(9,0.1369299);
   h_errors_copy__3->SetMinimum(0);
   h_errors_copy__3->SetMaximum(107.648);
   h_errors_copy__3->SetEntries(37192);
   h_errors_copy__3->SetDirectory(0);
   h_errors_copy__3->SetStats(0);
   h_errors_copy__3->SetFillColor(1);
   h_errors_copy__3->SetFillStyle(3253);

   ci = TColor::GetColor("#000099");
   h_errors_copy__3->SetLineColor(ci);
   h_errors_copy__3->GetXaxis()->SetTitle("Shower Multiplicity");
   h_errors_copy__3->GetXaxis()->SetLabelFont(42);
   h_errors_copy__3->GetXaxis()->SetLabelSize(0.045);
   h_errors_copy__3->GetXaxis()->SetTitleSize(0.05);
   h_errors_copy__3->GetXaxis()->SetTitleOffset(0.93);
   h_errors_copy__3->GetXaxis()->SetTitleFont(42);
   h_errors_copy__3->GetYaxis()->SetTitle(" Events/bin");
   h_errors_copy__3->GetYaxis()->SetLabelFont(42);
   h_errors_copy__3->GetYaxis()->SetLabelSize(0.045);
   h_errors_copy__3->GetYaxis()->SetTitleSize(0.05);
   h_errors_copy__3->GetYaxis()->SetTitleOffset(1.06);
   h_errors_copy__3->GetYaxis()->SetTitleFont(42);
   h_errors_copy__3->GetZaxis()->SetLabelFont(42);
   h_errors_copy__3->GetZaxis()->SetLabelSize(0.035);
   h_errors_copy__3->GetZaxis()->SetTitleSize(0.035);
   h_errors_copy__3->GetZaxis()->SetTitleFont(42);
   h_errors_copy__3->Draw("sameaxis");
   
   leg = new TLegend(0.54,0.815,0.885,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(32);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("NULL","NuMI RHC, 1.5 #times 10^{21} POT","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   leg = new TLegend(0.45,0.9,0.89,0.985,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(32);
   leg->SetTextFont(62);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("NULL","MicroBooNE Simulation, Preliminary","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   p_plot->Modified();
   c->cd();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
