void shower_multi_rhc_ByPureKaonType()
{
//=========Macro generated from canvas: c/c
//=========  (Wed Jan 10 05:22:34 2024) by ROOT version 6.12/06
   TCanvas *c = new TCanvas("c", "c",0,0,800,600);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: p_legend
   TPad *p_legend = new TPad("p_legend", "p_legend",0,0.85,1,1);
   p_legend->Draw();
   p_legend->cd();
   p_legend->Range(0,0,1,1);
   p_legend->SetFillColor(0);
   p_legend->SetBorderMode(0);
   p_legend->SetBorderSize(2);
   p_legend->SetBottomMargin(0);
   p_legend->SetFrameBorderMode(0);
   
   TLegend *leg = new TLegend(0.1,0,0.9,1,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaon","#nu_{#mu}CCK^{0}0#pi","F");

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaonMultiPion","#nu_{#mu}CCK^{0}N#pi","F");

   ci = TColor::GetColor("#00cc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaonHyperon","#nu_{#mu}CCK^{0}Y0#pi","F");

   ci = TColor::GetColor("#009900");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaonHyperonMultiPion","#nu_{#mu}CCK^{0}YN#pi","F");

   ci = TColor::GetColor("#006600");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonOtherNuMuCC","Other #nu_{#mu}CCK^{0}","F");
   entry->SetFillColor(30);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonNuECC","#nu_{e}CCK^{0}","F");

   ci = TColor::GetColor("#cc33ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonNC","NCK^{0}","F");

   ci = TColor::GetColor("#ffcc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonOutOfFV","Out FV","F");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   p_legend->Modified();
   c->cd();
  
// ------------>Primitives in pad: p_plot
   TPad *p_plot = new TPad("p_plot", "p_plot",0,0,1,0.85);
   p_plot->Draw();
   p_plot->cd();
   p_plot->Range(-0.7500001,-94.96942,6.75,854.7247);
   p_plot->SetFillColor(0);
   p_plot->SetBorderMode(0);
   p_plot->SetBorderSize(2);
   p_plot->SetTopMargin(0.01);
   p_plot->SetFrameBorderMode(0);
   p_plot->SetFrameBorderMode(0);
   
   TH1D *h_errors__1 = new TH1D("h_errors__1","",6,0,6);
   h_errors__1->SetBinContent(1,673.5886);
   h_errors__1->SetBinContent(2,179.1602);
   h_errors__1->SetBinContent(3,150.6883);
   h_errors__1->SetBinContent(4,101.2845);
   h_errors__1->SetBinContent(5,57.1635);
   h_errors__1->SetBinContent(6,27.91265);
   h_errors__1->SetBinContent(7,17.79619);
   h_errors__1->SetBinError(1,2.593624);
   h_errors__1->SetBinError(2,1.337613);
   h_errors__1->SetBinError(3,1.226731);
   h_errors__1->SetBinError(4,1.005729);
   h_errors__1->SetBinError(5,0.7555601);
   h_errors__1->SetBinError(6,0.5279711);
   h_errors__1->SetBinError(7,0.4215733);
   h_errors__1->SetMinimum(0);
   h_errors__1->SetMaximum(845.2278);
   h_errors__1->SetEntries(120921);
   h_errors__1->SetStats(0);
   h_errors__1->SetFillColor(1);
   h_errors__1->SetFillStyle(3253);

   ci = TColor::GetColor("#000099");
   h_errors__1->SetLineColor(ci);
   h_errors__1->GetXaxis()->SetTitle("Shower Multiplicity");
   h_errors__1->GetXaxis()->SetLabelFont(42);
   h_errors__1->GetXaxis()->SetLabelSize(0.045);
   h_errors__1->GetXaxis()->SetTitleSize(0.05);
   h_errors__1->GetXaxis()->SetTitleOffset(0.93);
   h_errors__1->GetXaxis()->SetTitleFont(42);
   h_errors__1->GetYaxis()->SetTitle(" Events/bin");
   h_errors__1->GetYaxis()->SetLabelFont(42);
   h_errors__1->GetYaxis()->SetLabelSize(0.045);
   h_errors__1->GetYaxis()->SetTitleSize(0.05);
   h_errors__1->GetYaxis()->SetTitleOffset(1.06);
   h_errors__1->GetYaxis()->SetTitleFont(42);
   h_errors__1->GetZaxis()->SetLabelFont(42);
   h_errors__1->GetZaxis()->SetLabelSize(0.035);
   h_errors__1->GetZaxis()->SetTitleSize(0.035);
   h_errors__1->GetZaxis()->SetTitleFont(42);
   h_errors__1->Draw("E2");
   
   THStack *hs = new THStack();
   hs->SetName("hs");
   hs->SetTitle("");
   
   TH1F *hs_stack_1 = new TH1F("hs_stack_1","",6,0,6);
   hs_stack_1->SetMinimum(0);
   hs_stack_1->SetMaximum(707.268);
   hs_stack_1->SetDirectory(0);
   hs_stack_1->SetStats(0);

   ci = TColor::GetColor("#000099");
   hs_stack_1->SetLineColor(ci);
   hs_stack_1->GetXaxis()->SetLabelFont(42);
   hs_stack_1->GetXaxis()->SetLabelSize(0.035);
   hs_stack_1->GetXaxis()->SetTitleSize(0.035);
   hs_stack_1->GetXaxis()->SetTitleFont(42);
   hs_stack_1->GetYaxis()->SetLabelFont(42);
   hs_stack_1->GetYaxis()->SetLabelSize(0.035);
   hs_stack_1->GetYaxis()->SetTitleSize(0.035);
   hs_stack_1->GetYaxis()->SetTitleOffset(0);
   hs_stack_1->GetYaxis()->SetTitleFont(42);
   hs_stack_1->GetZaxis()->SetLabelFont(42);
   hs_stack_1->GetZaxis()->SetLabelSize(0.035);
   hs_stack_1->GetZaxis()->SetTitleSize(0.035);
   hs_stack_1->GetZaxis()->SetTitleFont(42);
   hs->SetHistogram(hs_stack_1);
   
   
   TH1D *h_PureKaonSignalNuMuCCKaon_stack_1 = new TH1D("h_PureKaonSignalNuMuCCKaon_stack_1","",6,0,6);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(1,1.967367);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(2,2.117167);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(3,1.557915);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(4,1.03861);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(5,0.4693719);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(6,0.1298263);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(7,0.09986636);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(1,0.1401691);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(2,0.1454076);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(3,0.124733);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(4,0.1018441);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(5,0.06846493);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(6,0.03600733);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(7,0.03158052);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetEntries(739);

   ci = TColor::GetColor("#00ff00");
   h_PureKaonSignalNuMuCCKaon_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaon_stack_1->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetTitle("Shower Multiplicity");
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaon_stack_1,"HIST");
   
   TH1D *h_PureKaonSignalNuMuCCKaonMultiPion_stack_2 = new TH1D("h_PureKaonSignalNuMuCCKaonMultiPion_stack_2","",6,0,6);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(1,3.255643);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(2,3.165764);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(3,3.904775);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(4,2.926084);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(5,1.937407);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(6,1.088543);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(7,0.8288908);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(1,0.1803134);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(2,0.177807);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(3,0.1974729);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(4,0.1709437);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(5,0.1390977);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(6,0.1042635);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(7,0.09098258);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetEntries(1713);

   ci = TColor::GetColor("#00cc00");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetTitle("Shower Multiplicity");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaonMultiPion_stack_2,"HIST");
   
   TH1D *h_PureKaonSignalNuMuCCKaonHyperon_stack_3 = new TH1D("h_PureKaonSignalNuMuCCKaonHyperon_stack_3","",6,0,6);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(1,6.47134);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(2,7.410084);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(3,7.060552);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(4,3.864828);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(5,1.308249);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(6,0.5991982);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(7,0.2596525);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(1,0.2542182);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(2,0.2720327);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(3,0.2655394);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(4,0.1964603);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(5,0.1143023);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(6,0.07735615);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(7,0.05092205);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetEntries(2701);

   ci = TColor::GetColor("#009900");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetTitle("Shower Multiplicity");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaonHyperon_stack_3,"HIST");
   
   TH1D *h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4 = new TH1D("h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4","",6,0,6);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(1,11.39475);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(2,12.26359);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(3,15.80884);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(4,12.38343);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(5,7.300231);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(6,3.255643);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(7,2.396793);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(1,0.3373355);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(2,0.34996);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(3,0.3973376);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(4,0.3516657);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(5,0.2700088);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(6,0.1803134);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(7,0.1547123);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetEntries(6489);

   ci = TColor::GetColor("#006600");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetTitle("Shower Multiplicity");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4,"HIST");
   
   TH1D *h_PureKaonOtherNuMuCC_stack_5 = new TH1D("h_PureKaonOtherNuMuCC_stack_5","",6,0,6);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(1,20.96195);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(2,17.30684);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(3,22.61973);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(4,20.922);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(5,15.35945);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(6,8.868133);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(7,6.980658);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(1,0.4575362);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(2,0.4157368);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(3,0.4752841);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(4,0.4571);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(5,0.3916493);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(6,0.297595);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(7,0.2640328);
   h_PureKaonOtherNuMuCC_stack_5->SetEntries(11317);
   h_PureKaonOtherNuMuCC_stack_5->SetFillColor(30);

   ci = TColor::GetColor("#000099");
   h_PureKaonOtherNuMuCC_stack_5->SetLineColor(ci);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetTitle("Shower Multiplicity");
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetLabelFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetTitleFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetLabelFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitleOffset(0);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitleFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetLabelFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonOtherNuMuCC_stack_5,"HIST");
   
   TH1D *h_PureKaonNuECC_stack_6 = new TH1D("h_PureKaonNuECC_stack_6","",6,0,6);
   h_PureKaonNuECC_stack_6->SetBinContent(1,0.958717);
   h_PureKaonNuECC_stack_6->SetBinContent(2,0.9287571);
   h_PureKaonNuECC_stack_6->SetBinContent(3,1.238343);
   h_PureKaonNuECC_stack_6->SetBinContent(4,1.208383);
   h_PureKaonNuECC_stack_6->SetBinContent(5,0.9087839);
   h_PureKaonNuECC_stack_6->SetBinContent(6,0.5991982);
   h_PureKaonNuECC_stack_6->SetBinContent(7,0.4693719);
   h_PureKaonNuECC_stack_6->SetBinError(1,0.09784865);
   h_PureKaonNuECC_stack_6->SetBinError(2,0.09630763);
   h_PureKaonNuECC_stack_6->SetBinError(3,0.1112065);
   h_PureKaonNuECC_stack_6->SetBinError(4,0.109853);
   h_PureKaonNuECC_stack_6->SetBinError(5,0.09526643);
   h_PureKaonNuECC_stack_6->SetBinError(6,0.07735615);
   h_PureKaonNuECC_stack_6->SetBinError(7,0.06846493);
   h_PureKaonNuECC_stack_6->SetEntries(632);

   ci = TColor::GetColor("#cc33ff");
   h_PureKaonNuECC_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonNuECC_stack_6->SetLineColor(ci);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetTitle("Shower Multiplicity");
   h_PureKaonNuECC_stack_6->GetXaxis()->SetLabelFont(42);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetTitleFont(42);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonNuECC_stack_6->GetYaxis()->SetLabelFont(42);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitleOffset(0);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitleFont(42);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetLabelFont(42);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonNuECC_stack_6,"HIST");
   
   TH1D *h_PureKaonNC_stack_7 = new TH1D("h_PureKaonNC_stack_7","",6,0,6);
   h_PureKaonNC_stack_7->SetBinContent(1,26.64434);
   h_PureKaonNC_stack_7->SetBinContent(2,24.19762);
   h_PureKaonNC_stack_7->SetBinContent(3,25.75553);
   h_PureKaonNC_stack_7->SetBinContent(4,19.97327);
   h_PureKaonNC_stack_7->SetBinContent(5,11.11513);
   h_PureKaonNC_stack_7->SetBinContent(6,5.762289);
   h_PureKaonNC_stack_7->SetBinContent(7,3.465363);
   h_PureKaonNC_stack_7->SetBinError(1,0.5158366);
   h_PureKaonNC_stack_7->SetBinError(2,0.4915819);
   h_PureKaonNC_stack_7->SetBinError(3,0.5071599);
   h_PureKaonNC_stack_7->SetBinError(4,0.4466159);
   h_PureKaonNC_stack_7->SetBinError(5,0.3331707);
   h_PureKaonNC_stack_7->SetBinError(6,0.2398872);
   h_PureKaonNC_stack_7->SetBinError(7,0.1860304);
   h_PureKaonNC_stack_7->SetEntries(11707);

   ci = TColor::GetColor("#ffcc00");
   h_PureKaonNC_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonNC_stack_7->SetLineColor(ci);
   h_PureKaonNC_stack_7->GetXaxis()->SetTitle("Shower Multiplicity");
   h_PureKaonNC_stack_7->GetXaxis()->SetLabelFont(42);
   h_PureKaonNC_stack_7->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonNC_stack_7->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonNC_stack_7->GetXaxis()->SetTitleFont(42);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonNC_stack_7->GetYaxis()->SetLabelFont(42);
   h_PureKaonNC_stack_7->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitleOffset(0);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitleFont(42);
   h_PureKaonNC_stack_7->GetZaxis()->SetLabelFont(42);
   h_PureKaonNC_stack_7->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonNC_stack_7->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonNC_stack_7->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonNC_stack_7,"HIST");
   
   TH1D *h_PureKaonOutOfFV_stack_8 = new TH1D("h_PureKaonOutOfFV_stack_8","",6,0,6);
   h_PureKaonOutOfFV_stack_8->SetBinContent(1,601.9345);
   h_PureKaonOutOfFV_stack_8->SetBinContent(2,111.7704);
   h_PureKaonOutOfFV_stack_8->SetBinContent(3,72.74266);
   h_PureKaonOutOfFV_stack_8->SetBinContent(4,38.96785);
   h_PureKaonOutOfFV_stack_8->SetBinContent(5,18.76489);
   h_PureKaonOutOfFV_stack_8->SetBinContent(6,7.609817);
   h_PureKaonOutOfFV_stack_8->SetBinContent(7,3.29559);
   h_PureKaonOutOfFV_stack_8->SetBinError(1,2.451795);
   h_PureKaonOutOfFV_stack_8->SetBinError(2,1.056509);
   h_PureKaonOutOfFV_stack_8->SetBinError(3,0.8523229);
   h_PureKaonOutOfFV_stack_8->SetBinError(4,0.6238251);
   h_PureKaonOutOfFV_stack_8->SetBinError(5,0.432895);
   h_PureKaonOutOfFV_stack_8->SetBinError(6,0.2756746);
   h_PureKaonOutOfFV_stack_8->SetBinError(7,0.1814162);
   h_PureKaonOutOfFV_stack_8->SetEntries(85623);

   ci = TColor::GetColor("#cccccc");
   h_PureKaonOutOfFV_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonOutOfFV_stack_8->SetLineColor(ci);
   h_PureKaonOutOfFV_stack_8->GetXaxis()->SetTitle("Shower Multiplicity");
   h_PureKaonOutOfFV_stack_8->GetXaxis()->SetLabelFont(42);
   h_PureKaonOutOfFV_stack_8->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonOutOfFV_stack_8->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonOutOfFV_stack_8->GetXaxis()->SetTitleFont(42);
   h_PureKaonOutOfFV_stack_8->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonOutOfFV_stack_8->GetYaxis()->SetLabelFont(42);
   h_PureKaonOutOfFV_stack_8->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonOutOfFV_stack_8->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonOutOfFV_stack_8->GetYaxis()->SetTitleOffset(0);
   h_PureKaonOutOfFV_stack_8->GetYaxis()->SetTitleFont(42);
   h_PureKaonOutOfFV_stack_8->GetZaxis()->SetLabelFont(42);
   h_PureKaonOutOfFV_stack_8->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonOutOfFV_stack_8->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonOutOfFV_stack_8->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonOutOfFV_stack_8,"HIST");
   hs->Draw("hist same");
   
   TH1D *h_errors__2 = new TH1D("h_errors__2","",6,0,6);
   h_errors__2->SetBinContent(1,673.5886);
   h_errors__2->SetBinContent(2,179.1602);
   h_errors__2->SetBinContent(3,150.6883);
   h_errors__2->SetBinContent(4,101.2845);
   h_errors__2->SetBinContent(5,57.1635);
   h_errors__2->SetBinContent(6,27.91265);
   h_errors__2->SetBinContent(7,17.79619);
   h_errors__2->SetBinError(1,2.593624);
   h_errors__2->SetBinError(2,1.337613);
   h_errors__2->SetBinError(3,1.226731);
   h_errors__2->SetBinError(4,1.005729);
   h_errors__2->SetBinError(5,0.7555601);
   h_errors__2->SetBinError(6,0.5279711);
   h_errors__2->SetBinError(7,0.4215733);
   h_errors__2->SetMinimum(0);
   h_errors__2->SetMaximum(845.2278);
   h_errors__2->SetEntries(120921);
   h_errors__2->SetStats(0);
   h_errors__2->SetFillColor(1);
   h_errors__2->SetFillStyle(3253);

   ci = TColor::GetColor("#000099");
   h_errors__2->SetLineColor(ci);
   h_errors__2->GetXaxis()->SetTitle("Shower Multiplicity");
   h_errors__2->GetXaxis()->SetLabelFont(42);
   h_errors__2->GetXaxis()->SetLabelSize(0.045);
   h_errors__2->GetXaxis()->SetTitleSize(0.05);
   h_errors__2->GetXaxis()->SetTitleOffset(0.93);
   h_errors__2->GetXaxis()->SetTitleFont(42);
   h_errors__2->GetYaxis()->SetTitle(" Events/bin");
   h_errors__2->GetYaxis()->SetLabelFont(42);
   h_errors__2->GetYaxis()->SetLabelSize(0.045);
   h_errors__2->GetYaxis()->SetTitleSize(0.05);
   h_errors__2->GetYaxis()->SetTitleOffset(1.06);
   h_errors__2->GetYaxis()->SetTitleFont(42);
   h_errors__2->GetZaxis()->SetLabelFont(42);
   h_errors__2->GetZaxis()->SetLabelSize(0.035);
   h_errors__2->GetZaxis()->SetTitleSize(0.035);
   h_errors__2->GetZaxis()->SetTitleFont(42);
   h_errors__2->Draw("E2 same");
   
   TH1D *h_errors_copy__3 = new TH1D("h_errors_copy__3","",6,0,6);
   h_errors_copy__3->SetBinContent(1,673.5886);
   h_errors_copy__3->SetBinContent(2,179.1602);
   h_errors_copy__3->SetBinContent(3,150.6883);
   h_errors_copy__3->SetBinContent(4,101.2845);
   h_errors_copy__3->SetBinContent(5,57.1635);
   h_errors_copy__3->SetBinContent(6,27.91265);
   h_errors_copy__3->SetBinContent(7,17.79619);
   h_errors_copy__3->SetBinError(1,2.593624);
   h_errors_copy__3->SetBinError(2,1.337613);
   h_errors_copy__3->SetBinError(3,1.226731);
   h_errors_copy__3->SetBinError(4,1.005729);
   h_errors_copy__3->SetBinError(5,0.7555601);
   h_errors_copy__3->SetBinError(6,0.5279711);
   h_errors_copy__3->SetBinError(7,0.4215733);
   h_errors_copy__3->SetMinimum(0);
   h_errors_copy__3->SetMaximum(845.2278);
   h_errors_copy__3->SetEntries(120921);
   h_errors_copy__3->SetDirectory(0);
   h_errors_copy__3->SetStats(0);
   h_errors_copy__3->SetFillColor(1);
   h_errors_copy__3->SetFillStyle(3253);

   ci = TColor::GetColor("#000099");
   h_errors_copy__3->SetLineColor(ci);
   h_errors_copy__3->GetXaxis()->SetTitle("Shower Multiplicity");
   h_errors_copy__3->GetXaxis()->SetLabelFont(42);
   h_errors_copy__3->GetXaxis()->SetLabelSize(0.045);
   h_errors_copy__3->GetXaxis()->SetTitleSize(0.05);
   h_errors_copy__3->GetXaxis()->SetTitleOffset(0.93);
   h_errors_copy__3->GetXaxis()->SetTitleFont(42);
   h_errors_copy__3->GetYaxis()->SetTitle(" Events/bin");
   h_errors_copy__3->GetYaxis()->SetLabelFont(42);
   h_errors_copy__3->GetYaxis()->SetLabelSize(0.045);
   h_errors_copy__3->GetYaxis()->SetTitleSize(0.05);
   h_errors_copy__3->GetYaxis()->SetTitleOffset(1.06);
   h_errors_copy__3->GetYaxis()->SetTitleFont(42);
   h_errors_copy__3->GetZaxis()->SetLabelFont(42);
   h_errors_copy__3->GetZaxis()->SetLabelSize(0.035);
   h_errors_copy__3->GetZaxis()->SetTitleSize(0.035);
   h_errors_copy__3->GetZaxis()->SetTitleFont(42);
   h_errors_copy__3->Draw("sameaxis");
   
   leg = new TLegend(0.54,0.815,0.885,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(32);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("NULL","NuMI RHC, 1.5 #times 10^{21} POT","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   leg = new TLegend(0.45,0.9,0.89,0.985,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(32);
   leg->SetTextFont(62);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("NULL","MicroBooNE Simulation, Preliminary","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   p_plot->Modified();
   c->cd();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
