void signal_bdt_selector_rhc_ByPureKaonType()
{
//=========Macro generated from canvas: c/c
//=========  (Thu Feb 22 06:48:13 2024) by ROOT version 6.12/06
   TCanvas *c = new TCanvas("c", "c",0,0,800,600);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: p_legend
   TPad *p_legend = new TPad("p_legend", "p_legend",0,0.85,1,1);
   p_legend->Draw();
   p_legend->cd();
   p_legend->Range(0,0,1,1);
   p_legend->SetFillColor(0);
   p_legend->SetBorderMode(0);
   p_legend->SetBorderSize(2);
   p_legend->SetBottomMargin(0);
   p_legend->SetFrameBorderMode(0);
   
   TLegend *leg = new TLegend(0.1,0,0.9,1,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaon","#nu_{#mu}CCK^{0}0#pi","F");

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaonMultiPion","#nu_{#mu}CCK^{0}N#pi","F");

   ci = TColor::GetColor("#00cc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaonHyperon","#nu_{#mu}CCK^{0}Y0#pi","F");

   ci = TColor::GetColor("#009900");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaonHyperonMultiPion","#nu_{#mu}CCK^{0}YN#pi","F");

   ci = TColor::GetColor("#006600");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonOtherNuMuCC","Other #nu_{#mu}CC","F");
   entry->SetFillColor(30);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonNuECC","#nu_{e}CC","F");

   ci = TColor::GetColor("#cc33ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonNC","NC","F");

   ci = TColor::GetColor("#ffcc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonOutFV","Out FV","F");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonBeamOff","Beam-Off","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3004);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonOther","Other","F");

   ci = TColor::GetColor("#cc0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   p_legend->Modified();
   c->cd();
  
// ------------>Primitives in pad: p_plot
   TPad *p_plot = new TPad("p_plot", "p_plot",0,0,1,0.85);
   p_plot->Draw();
   p_plot->cd();
   p_plot->Range(-0.625,-2.431192,0.625,21.88072);
   p_plot->SetFillColor(0);
   p_plot->SetBorderMode(0);
   p_plot->SetBorderSize(2);
   p_plot->SetTopMargin(0.01);
   p_plot->SetFrameBorderMode(0);
   p_plot->SetFrameBorderMode(0);
   
   TH1D *h_errors__1 = new TH1D("h_errors__1","",20,-0.5,0.5);
   h_errors__1->SetBinContent(4,0.006453464);
   h_errors__1->SetBinContent(5,1.00674);
   h_errors__1->SetBinContent(6,4.220566);
   h_errors__1->SetBinContent(7,10.20938);
   h_errors__1->SetBinContent(8,15.10756);
   h_errors__1->SetBinContent(9,16.97906);
   h_errors__1->SetBinContent(10,7.234334);
   h_errors__1->SetBinContent(11,0.98738);
   h_errors__1->SetBinContent(12,0.01290693);
   h_errors__1->SetBinError(4,0.006453464);
   h_errors__1->SetBinError(5,0.08060374);
   h_errors__1->SetBinError(6,0.1650372);
   h_errors__1->SetBinError(7,0.2566824);
   h_errors__1->SetBinError(8,0.3122437);
   h_errors__1->SetBinError(9,0.3310193);
   h_errors__1->SetBinError(10,0.2160706);
   h_errors__1->SetBinError(11,0.07982495);
   h_errors__1->SetBinError(12,0.009126577);
   h_errors__1->SetMinimum(0);
   h_errors__1->SetMaximum(21.6376);
   h_errors__1->SetEntries(8641);
   h_errors__1->SetStats(0);
   h_errors__1->SetFillColor(1);
   h_errors__1->SetFillStyle(3253);

   ci = TColor::GetColor("#000099");
   h_errors__1->SetLineColor(ci);
   h_errors__1->GetXaxis()->SetTitle("Event Selector BDT Score");
   h_errors__1->GetXaxis()->SetLabelFont(42);
   h_errors__1->GetXaxis()->SetLabelSize(0.045);
   h_errors__1->GetXaxis()->SetTitleSize(0.05);
   h_errors__1->GetXaxis()->SetTitleOffset(0.93);
   h_errors__1->GetXaxis()->SetTitleFont(42);
   h_errors__1->GetYaxis()->SetTitle("Events/bin");
   h_errors__1->GetYaxis()->SetLabelFont(42);
   h_errors__1->GetYaxis()->SetLabelSize(0.045);
   h_errors__1->GetYaxis()->SetTitleSize(0.05);
   h_errors__1->GetYaxis()->SetTitleOffset(1.06);
   h_errors__1->GetYaxis()->SetTitleFont(42);
   h_errors__1->GetZaxis()->SetLabelFont(42);
   h_errors__1->GetZaxis()->SetLabelSize(0.035);
   h_errors__1->GetZaxis()->SetTitleSize(0.035);
   h_errors__1->GetZaxis()->SetTitleFont(42);
   h_errors__1->Draw("E2");
   
   THStack *hs = new THStack();
   hs->SetName("hs");
   hs->SetTitle("");
   
   TH1F *hs_stack_1 = new TH1F("hs_stack_1","",20,-0.5,0.5);
   hs_stack_1->SetMinimum(0);
   hs_stack_1->SetMaximum(17.82802);
   hs_stack_1->SetDirectory(0);
   hs_stack_1->SetStats(0);

   ci = TColor::GetColor("#000099");
   hs_stack_1->SetLineColor(ci);
   hs_stack_1->GetXaxis()->SetLabelFont(42);
   hs_stack_1->GetXaxis()->SetLabelSize(0.035);
   hs_stack_1->GetXaxis()->SetTitleSize(0.035);
   hs_stack_1->GetXaxis()->SetTitleFont(42);
   hs_stack_1->GetYaxis()->SetLabelFont(42);
   hs_stack_1->GetYaxis()->SetLabelSize(0.035);
   hs_stack_1->GetYaxis()->SetTitleSize(0.035);
   hs_stack_1->GetYaxis()->SetTitleOffset(0);
   hs_stack_1->GetYaxis()->SetTitleFont(42);
   hs_stack_1->GetZaxis()->SetLabelFont(42);
   hs_stack_1->GetZaxis()->SetLabelSize(0.035);
   hs_stack_1->GetZaxis()->SetTitleSize(0.035);
   hs_stack_1->GetZaxis()->SetTitleFont(42);
   hs->SetHistogram(hs_stack_1);
   
   
   TH1D *h_PureKaonSignalNuMuCCKaon_stack_1 = new TH1D("h_PureKaonSignalNuMuCCKaon_stack_1","",20,-0.5,0.5);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(5,0.02581386);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(6,0.05162771);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(7,0.2000574);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(8,0.264592);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(9,0.458196);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(10,0.1936039);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(11,0.01936039);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(5,0.01290693);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(6,0.01825315);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(7,0.03593137);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(8,0.04132233);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(9,0.05437786);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(10,0.03534708);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(11,0.01117773);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetEntries(188);

   ci = TColor::GetColor("#00ff00");
   h_PureKaonSignalNuMuCCKaon_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaon_stack_1->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetTitle("Event Selector BDT Score");
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitle("Events/bin");
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaon_stack_1,"HIST");
   
   TH1D *h_PureKaonSignalNuMuCCKaonMultiPion_stack_2 = new TH1D("h_PureKaonSignalNuMuCCKaonMultiPion_stack_2","",20,-0.5,0.5);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(5,0.01936039);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(6,0.1936039);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(7,0.361394);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(8,0.7421484);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(9,0.7421484);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(10,0.3743009);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(11,0.05162771);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(5,0.01117773);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(6,0.03534708);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(7,0.0482933);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(8,0.06920569);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(9,0.06920569);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(10,0.04914812);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(11,0.01825315);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetEntries(385);

   ci = TColor::GetColor("#00cc00");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetTitle("Event Selector BDT Score");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitle("Events/bin");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaonMultiPion_stack_2,"HIST");
   
   TH1D *h_PureKaonSignalNuMuCCKaonHyperon_stack_3 = new TH1D("h_PureKaonSignalNuMuCCKaonHyperon_stack_3","",20,-0.5,0.5);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(5,0.04517425);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(6,0.2129643);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(7,0.8131365);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(8,1.645633);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(9,2.349061);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(10,1.084182);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(11,0.2065109);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(5,0.01707426);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(6,0.03707233);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(7,0.07243996);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(8,0.1030536);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(9,0.1231243);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(10,0.08364646);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(11,0.03650631);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetEntries(985);

   ci = TColor::GetColor("#009900");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetTitle("Event Selector BDT Score");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitle("Events/bin");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaonHyperon_stack_3,"HIST");
   
   TH1D *h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4 = new TH1D("h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4","",20,-0.5,0.5);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(5,0.1677901);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(6,0.6776138);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(7,1.774703);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(8,2.904059);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(9,3.497778);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(10,1.63918);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(11,0.2387782);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(5,0.03290634);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(6,0.06612833);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(7,0.1070186);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(8,0.1368987);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(9,0.1502424);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(10,0.1028513);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(11,0.03925489);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetEntries(1689);

   ci = TColor::GetColor("#006600");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetTitle("Event Selector BDT Score");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitle("Events/bin");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4,"HIST");
   
   TH1D *h_PureKaonOtherNuMuCC_stack_5 = new TH1D("h_PureKaonOtherNuMuCC_stack_5","",20,-0.5,0.5);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(5,0.3807544);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(6,1.774703);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(7,4.104403);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(8,5.446724);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(9,6.104977);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(10,2.387782);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(11,0.277499);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(5,0.04957);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(6,0.1070186);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(7,0.1627502);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(8,0.187484);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(9,0.1984899);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(10,0.1241349);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(11,0.0423182);
   h_PureKaonOtherNuMuCC_stack_5->SetEntries(3173);
   h_PureKaonOtherNuMuCC_stack_5->SetFillColor(30);

   ci = TColor::GetColor("#000099");
   h_PureKaonOtherNuMuCC_stack_5->SetLineColor(ci);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetTitle("Event Selector BDT Score");
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetLabelFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetTitleFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitle("Events/bin");
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetLabelFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitleOffset(0);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitleFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetLabelFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonOtherNuMuCC_stack_5,"HIST");
   
   TH1D *h_PureKaonNuECC_stack_6 = new TH1D("h_PureKaonNuECC_stack_6","",20,-0.5,0.5);
   h_PureKaonNuECC_stack_6->SetBinContent(5,0.006453464);
   h_PureKaonNuECC_stack_6->SetBinContent(6,0.04517425);
   h_PureKaonNuECC_stack_6->SetBinContent(7,0.1936039);
   h_PureKaonNuECC_stack_6->SetBinContent(8,0.2194178);
   h_PureKaonNuECC_stack_6->SetBinContent(9,0.2323247);
   h_PureKaonNuECC_stack_6->SetBinContent(10,0.07744157);
   h_PureKaonNuECC_stack_6->SetBinContent(11,0.006453464);
   h_PureKaonNuECC_stack_6->SetBinError(5,0.006453464);
   h_PureKaonNuECC_stack_6->SetBinError(6,0.01707426);
   h_PureKaonNuECC_stack_6->SetBinError(7,0.03534708);
   h_PureKaonNuECC_stack_6->SetBinError(8,0.03762984);
   h_PureKaonNuECC_stack_6->SetBinError(9,0.03872079);
   h_PureKaonNuECC_stack_6->SetBinError(10,0.02235546);
   h_PureKaonNuECC_stack_6->SetBinError(11,0.006453464);
   h_PureKaonNuECC_stack_6->SetEntries(121);

   ci = TColor::GetColor("#cc33ff");
   h_PureKaonNuECC_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonNuECC_stack_6->SetLineColor(ci);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetTitle("Event Selector BDT Score");
   h_PureKaonNuECC_stack_6->GetXaxis()->SetLabelFont(42);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetTitleFont(42);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitle("Events/bin");
   h_PureKaonNuECC_stack_6->GetYaxis()->SetLabelFont(42);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitleOffset(0);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitleFont(42);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetLabelFont(42);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonNuECC_stack_6,"HIST");
   
   TH1D *h_PureKaonNC_stack_7 = new TH1D("h_PureKaonNC_stack_7","",20,-0.5,0.5);
   h_PureKaonNC_stack_7->SetBinContent(4,0.006453464);
   h_PureKaonNC_stack_7->SetBinContent(5,0.3162198);
   h_PureKaonNC_stack_7->SetBinContent(6,1.103542);
   h_PureKaonNC_stack_7->SetBinContent(7,2.323247);
   h_PureKaonNC_stack_7->SetBinContent(8,3.233186);
   h_PureKaonNC_stack_7->SetBinContent(9,3.013768);
   h_PureKaonNC_stack_7->SetBinContent(10,1.226158);
   h_PureKaonNC_stack_7->SetBinContent(11,0.1419762);
   h_PureKaonNC_stack_7->SetBinContent(12,0.01290693);
   h_PureKaonNC_stack_7->SetBinError(4,0.006453464);
   h_PureKaonNC_stack_7->SetBinError(5,0.04517425);
   h_PureKaonNC_stack_7->SetBinError(6,0.08439);
   h_PureKaonNC_stack_7->SetBinError(7,0.1224459);
   h_PureKaonNC_stack_7->SetBinError(8,0.1444481);
   h_PureKaonNC_stack_7->SetBinError(9,0.1394605);
   h_PureKaonNC_stack_7->SetBinError(10,0.08895487);
   h_PureKaonNC_stack_7->SetBinError(11,0.03026943);
   h_PureKaonNC_stack_7->SetBinError(12,0.009126577);
   h_PureKaonNC_stack_7->SetEntries(1763);

   ci = TColor::GetColor("#ffcc00");
   h_PureKaonNC_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonNC_stack_7->SetLineColor(ci);
   h_PureKaonNC_stack_7->GetXaxis()->SetTitle("Event Selector BDT Score");
   h_PureKaonNC_stack_7->GetXaxis()->SetLabelFont(42);
   h_PureKaonNC_stack_7->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonNC_stack_7->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonNC_stack_7->GetXaxis()->SetTitleFont(42);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitle("Events/bin");
   h_PureKaonNC_stack_7->GetYaxis()->SetLabelFont(42);
   h_PureKaonNC_stack_7->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitleOffset(0);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitleFont(42);
   h_PureKaonNC_stack_7->GetZaxis()->SetLabelFont(42);
   h_PureKaonNC_stack_7->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonNC_stack_7->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonNC_stack_7->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonNC_stack_7,"HIST");
   
   TH1D *h_PureKaonOutFV_stack_8 = new TH1D("h_PureKaonOutFV_stack_8","",20,-0.5,0.5);
   h_PureKaonOutFV_stack_8->SetBinContent(5,0.04517425);
   h_PureKaonOutFV_stack_8->SetBinContent(6,0.1613366);
   h_PureKaonOutFV_stack_8->SetBinContent(7,0.4388356);
   h_PureKaonOutFV_stack_8->SetBinContent(8,0.6517999);
   h_PureKaonOutFV_stack_8->SetBinContent(9,0.5808118);
   h_PureKaonOutFV_stack_8->SetBinContent(10,0.2516851);
   h_PureKaonOutFV_stack_8->SetBinContent(11,0.04517425);
   h_PureKaonOutFV_stack_8->SetBinError(5,0.01707426);
   h_PureKaonOutFV_stack_8->SetBinError(6,0.03226732);
   h_PureKaonOutFV_stack_8->SetBinError(7,0.05321663);
   h_PureKaonOutFV_stack_8->SetBinError(8,0.06485651);
   h_PureKaonOutFV_stack_8->SetBinError(9,0.06122294);
   h_PureKaonOutFV_stack_8->SetBinError(10,0.04030187);
   h_PureKaonOutFV_stack_8->SetBinError(11,0.01707426);
   h_PureKaonOutFV_stack_8->SetEntries(337);

   ci = TColor::GetColor("#cccccc");
   h_PureKaonOutFV_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonOutFV_stack_8->SetLineColor(ci);
   h_PureKaonOutFV_stack_8->GetXaxis()->SetTitle("Event Selector BDT Score");
   h_PureKaonOutFV_stack_8->GetXaxis()->SetLabelFont(42);
   h_PureKaonOutFV_stack_8->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonOutFV_stack_8->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonOutFV_stack_8->GetXaxis()->SetTitleFont(42);
   h_PureKaonOutFV_stack_8->GetYaxis()->SetTitle("Events/bin");
   h_PureKaonOutFV_stack_8->GetYaxis()->SetLabelFont(42);
   h_PureKaonOutFV_stack_8->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonOutFV_stack_8->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonOutFV_stack_8->GetYaxis()->SetTitleOffset(0);
   h_PureKaonOutFV_stack_8->GetYaxis()->SetTitleFont(42);
   h_PureKaonOutFV_stack_8->GetZaxis()->SetLabelFont(42);
   h_PureKaonOutFV_stack_8->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonOutFV_stack_8->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonOutFV_stack_8->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonOutFV_stack_8,"HIST");
   
   TH1D *h_PureKaonBeamOff_stack_9 = new TH1D("h_PureKaonBeamOff_stack_9","",20,-0.5,0.5);
   h_PureKaonBeamOff_stack_9->SetFillColor(1);
   h_PureKaonBeamOff_stack_9->SetFillStyle(3004);

   ci = TColor::GetColor("#000099");
   h_PureKaonBeamOff_stack_9->SetLineColor(ci);
   h_PureKaonBeamOff_stack_9->GetXaxis()->SetTitle("Event Selector BDT Score");
   h_PureKaonBeamOff_stack_9->GetXaxis()->SetLabelFont(42);
   h_PureKaonBeamOff_stack_9->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonBeamOff_stack_9->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonBeamOff_stack_9->GetXaxis()->SetTitleFont(42);
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetTitle("Events/bin");
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetLabelFont(42);
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetTitleOffset(0);
   h_PureKaonBeamOff_stack_9->GetYaxis()->SetTitleFont(42);
   h_PureKaonBeamOff_stack_9->GetZaxis()->SetLabelFont(42);
   h_PureKaonBeamOff_stack_9->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonBeamOff_stack_9->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonBeamOff_stack_9->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonBeamOff_stack_9,"HIST");
   
   TH1D *h_PureKaonOther_stack_10 = new TH1D("h_PureKaonOther_stack_10","",20,-0.5,0.5);

   ci = TColor::GetColor("#cc0000");
   h_PureKaonOther_stack_10->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonOther_stack_10->SetLineColor(ci);
   h_PureKaonOther_stack_10->GetXaxis()->SetTitle("Event Selector BDT Score");
   h_PureKaonOther_stack_10->GetXaxis()->SetLabelFont(42);
   h_PureKaonOther_stack_10->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonOther_stack_10->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonOther_stack_10->GetXaxis()->SetTitleFont(42);
   h_PureKaonOther_stack_10->GetYaxis()->SetTitle("Events/bin");
   h_PureKaonOther_stack_10->GetYaxis()->SetLabelFont(42);
   h_PureKaonOther_stack_10->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonOther_stack_10->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonOther_stack_10->GetYaxis()->SetTitleOffset(0);
   h_PureKaonOther_stack_10->GetYaxis()->SetTitleFont(42);
   h_PureKaonOther_stack_10->GetZaxis()->SetLabelFont(42);
   h_PureKaonOther_stack_10->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonOther_stack_10->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonOther_stack_10->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonOther_stack_10,"HIST");
   hs->Draw("hist same");
   
   TH1D *h_errors__2 = new TH1D("h_errors__2","",20,-0.5,0.5);
   h_errors__2->SetBinContent(4,0.006453464);
   h_errors__2->SetBinContent(5,1.00674);
   h_errors__2->SetBinContent(6,4.220566);
   h_errors__2->SetBinContent(7,10.20938);
   h_errors__2->SetBinContent(8,15.10756);
   h_errors__2->SetBinContent(9,16.97906);
   h_errors__2->SetBinContent(10,7.234334);
   h_errors__2->SetBinContent(11,0.98738);
   h_errors__2->SetBinContent(12,0.01290693);
   h_errors__2->SetBinError(4,0.006453464);
   h_errors__2->SetBinError(5,0.08060374);
   h_errors__2->SetBinError(6,0.1650372);
   h_errors__2->SetBinError(7,0.2566824);
   h_errors__2->SetBinError(8,0.3122437);
   h_errors__2->SetBinError(9,0.3310193);
   h_errors__2->SetBinError(10,0.2160706);
   h_errors__2->SetBinError(11,0.07982495);
   h_errors__2->SetBinError(12,0.009126577);
   h_errors__2->SetMinimum(0);
   h_errors__2->SetMaximum(21.6376);
   h_errors__2->SetEntries(8641);
   h_errors__2->SetStats(0);
   h_errors__2->SetFillColor(1);
   h_errors__2->SetFillStyle(3253);

   ci = TColor::GetColor("#000099");
   h_errors__2->SetLineColor(ci);
   h_errors__2->GetXaxis()->SetTitle("Event Selector BDT Score");
   h_errors__2->GetXaxis()->SetLabelFont(42);
   h_errors__2->GetXaxis()->SetLabelSize(0.045);
   h_errors__2->GetXaxis()->SetTitleSize(0.05);
   h_errors__2->GetXaxis()->SetTitleOffset(0.93);
   h_errors__2->GetXaxis()->SetTitleFont(42);
   h_errors__2->GetYaxis()->SetTitle("Events/bin");
   h_errors__2->GetYaxis()->SetLabelFont(42);
   h_errors__2->GetYaxis()->SetLabelSize(0.045);
   h_errors__2->GetYaxis()->SetTitleSize(0.05);
   h_errors__2->GetYaxis()->SetTitleOffset(1.06);
   h_errors__2->GetYaxis()->SetTitleFont(42);
   h_errors__2->GetZaxis()->SetLabelFont(42);
   h_errors__2->GetZaxis()->SetLabelSize(0.035);
   h_errors__2->GetZaxis()->SetTitleSize(0.035);
   h_errors__2->GetZaxis()->SetTitleFont(42);
   h_errors__2->Draw("E2 same");
   
   TH1D *h_errors_copy__3 = new TH1D("h_errors_copy__3","",20,-0.5,0.5);
   h_errors_copy__3->SetBinContent(4,0.006453464);
   h_errors_copy__3->SetBinContent(5,1.00674);
   h_errors_copy__3->SetBinContent(6,4.220566);
   h_errors_copy__3->SetBinContent(7,10.20938);
   h_errors_copy__3->SetBinContent(8,15.10756);
   h_errors_copy__3->SetBinContent(9,16.97906);
   h_errors_copy__3->SetBinContent(10,7.234334);
   h_errors_copy__3->SetBinContent(11,0.98738);
   h_errors_copy__3->SetBinContent(12,0.01290693);
   h_errors_copy__3->SetBinError(4,0.006453464);
   h_errors_copy__3->SetBinError(5,0.08060374);
   h_errors_copy__3->SetBinError(6,0.1650372);
   h_errors_copy__3->SetBinError(7,0.2566824);
   h_errors_copy__3->SetBinError(8,0.3122437);
   h_errors_copy__3->SetBinError(9,0.3310193);
   h_errors_copy__3->SetBinError(10,0.2160706);
   h_errors_copy__3->SetBinError(11,0.07982495);
   h_errors_copy__3->SetBinError(12,0.009126577);
   h_errors_copy__3->SetMinimum(0);
   h_errors_copy__3->SetMaximum(21.6376);
   h_errors_copy__3->SetEntries(8641);
   h_errors_copy__3->SetDirectory(0);
   h_errors_copy__3->SetStats(0);
   h_errors_copy__3->SetFillColor(1);
   h_errors_copy__3->SetFillStyle(3253);

   ci = TColor::GetColor("#000099");
   h_errors_copy__3->SetLineColor(ci);
   h_errors_copy__3->GetXaxis()->SetTitle("Event Selector BDT Score");
   h_errors_copy__3->GetXaxis()->SetLabelFont(42);
   h_errors_copy__3->GetXaxis()->SetLabelSize(0.045);
   h_errors_copy__3->GetXaxis()->SetTitleSize(0.05);
   h_errors_copy__3->GetXaxis()->SetTitleOffset(0.93);
   h_errors_copy__3->GetXaxis()->SetTitleFont(42);
   h_errors_copy__3->GetYaxis()->SetTitle("Events/bin");
   h_errors_copy__3->GetYaxis()->SetLabelFont(42);
   h_errors_copy__3->GetYaxis()->SetLabelSize(0.045);
   h_errors_copy__3->GetYaxis()->SetTitleSize(0.05);
   h_errors_copy__3->GetYaxis()->SetTitleOffset(1.06);
   h_errors_copy__3->GetYaxis()->SetTitleFont(42);
   h_errors_copy__3->GetZaxis()->SetLabelFont(42);
   h_errors_copy__3->GetZaxis()->SetLabelSize(0.035);
   h_errors_copy__3->GetZaxis()->SetTitleSize(0.035);
   h_errors_copy__3->GetZaxis()->SetTitleFont(42);
   h_errors_copy__3->Draw("sameaxis");
   
   leg = new TLegend(0.54,0.815,0.885,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(32);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("NULL","NuMI FHC, 1.2 #times 10^{21} POT","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   leg = new TLegend(0.45,0.9,0.89,0.985,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(32);
   leg->SetTextFont(62);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("NULL","MicroBooNE Simulation, Preliminary","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   p_plot->Modified();
   c->cd();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
