void track_multi_rhc_ByPureKaonType()
{
//=========Macro generated from canvas: c/c
//=========  (Wed Jan 10 05:17:15 2024) by ROOT version 6.12/06
   TCanvas *c = new TCanvas("c", "c",0,0,800,600);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: p_legend
   TPad *p_legend = new TPad("p_legend", "p_legend",0,0.85,1,1);
   p_legend->Draw();
   p_legend->cd();
   p_legend->Range(0,0,1,1);
   p_legend->SetFillColor(0);
   p_legend->SetBorderMode(0);
   p_legend->SetBorderSize(2);
   p_legend->SetBottomMargin(0);
   p_legend->SetFrameBorderMode(0);
   
   TLegend *leg = new TLegend(0.1,0,0.9,1,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaon","#nu_{#mu}CCK^{0}0#pi","F");

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaonMultiPion","#nu_{#mu}CCK^{0}N#pi","F");

   ci = TColor::GetColor("#00cc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaonHyperon","#nu_{#mu}CCK^{0}Y0#pi","F");

   ci = TColor::GetColor("#009900");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonSignalNuMuCCKaonHyperonMultiPion","#nu_{#mu}CCK^{0}YN#pi","F");

   ci = TColor::GetColor("#006600");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonOtherNuMuCC","Other #nu_{#mu}CCK^{0}","F");
   entry->SetFillColor(30);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonNuECC","#nu_{e}CCK^{0}","F");

   ci = TColor::GetColor("#cc33ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonNC","NCK^{0}","F");

   ci = TColor::GetColor("#ffcc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_PureKaonOutOfFV","Out FV","F");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   p_legend->Modified();
   c->cd();
  
// ------------>Primitives in pad: p_plot
   TPad *p_plot = new TPad("p_plot", "p_plot",0,0,1,0.85);
   p_plot->Draw();
   p_plot->cd();
   p_plot->Range(-1,-75.81567,9,682.341);
   p_plot->SetFillColor(0);
   p_plot->SetBorderMode(0);
   p_plot->SetBorderSize(2);
   p_plot->SetTopMargin(0.01);
   p_plot->SetFrameBorderMode(0);
   p_plot->SetFrameBorderMode(0);
   
   TH1D *h_errors__1 = new TH1D("h_errors__1","",8,0,8);
   h_errors__1->SetBinContent(1,537.4907);
   h_errors__1->SetBinContent(2,175.2155);
   h_errors__1->SetBinContent(3,159.3168);
   h_errors__1->SetBinContent(4,126.5407);
   h_errors__1->SetBinContent(5,94.86305);
   h_errors__1->SetBinContent(6,58.24206);
   h_errors__1->SetBinContent(7,31.58773);
   h_errors__1->SetBinContent(8,14.44068);
   h_errors__1->SetBinContent(9,9.896756);
   h_errors__1->SetBinError(1,2.316835);
   h_errors__1->SetBinError(2,1.322805);
   h_errors__1->SetBinError(3,1.261364);
   h_errors__1->SetBinError(4,1.124151);
   h_errors__1->SetBinError(5,0.9733256);
   h_errors__1->SetBinError(6,0.7626547);
   h_errors__1->SetBinError(7,0.5616539);
   h_errors__1->SetBinError(8,0.3797549);
   h_errors__1->SetBinError(9,0.3143808);
   h_errors__1->SetMinimum(0);
   h_errors__1->SetMaximum(674.7595);
   h_errors__1->SetEntries(120921);
   h_errors__1->SetStats(0);
   h_errors__1->SetFillColor(1);
   h_errors__1->SetFillStyle(3253);

   ci = TColor::GetColor("#000099");
   h_errors__1->SetLineColor(ci);
   h_errors__1->GetXaxis()->SetTitle("Track Multiplicity");
   h_errors__1->GetXaxis()->SetLabelFont(42);
   h_errors__1->GetXaxis()->SetLabelSize(0.045);
   h_errors__1->GetXaxis()->SetTitleSize(0.05);
   h_errors__1->GetXaxis()->SetTitleOffset(0.93);
   h_errors__1->GetXaxis()->SetTitleFont(42);
   h_errors__1->GetYaxis()->SetTitle(" Events/bin");
   h_errors__1->GetYaxis()->SetLabelFont(42);
   h_errors__1->GetYaxis()->SetLabelSize(0.045);
   h_errors__1->GetYaxis()->SetTitleSize(0.05);
   h_errors__1->GetYaxis()->SetTitleOffset(1.06);
   h_errors__1->GetYaxis()->SetTitleFont(42);
   h_errors__1->GetZaxis()->SetLabelFont(42);
   h_errors__1->GetZaxis()->SetLabelSize(0.035);
   h_errors__1->GetZaxis()->SetTitleSize(0.035);
   h_errors__1->GetZaxis()->SetTitleFont(42);
   h_errors__1->Draw("E2");
   
   THStack *hs = new THStack();
   hs->SetName("hs");
   hs->SetTitle("");
   
   TH1F *hs_stack_1 = new TH1F("hs_stack_1","",8,0,8);
   hs_stack_1->SetMinimum(0);
   hs_stack_1->SetMaximum(564.3653);
   hs_stack_1->SetDirectory(0);
   hs_stack_1->SetStats(0);

   ci = TColor::GetColor("#000099");
   hs_stack_1->SetLineColor(ci);
   hs_stack_1->GetXaxis()->SetLabelFont(42);
   hs_stack_1->GetXaxis()->SetLabelSize(0.035);
   hs_stack_1->GetXaxis()->SetTitleSize(0.035);
   hs_stack_1->GetXaxis()->SetTitleFont(42);
   hs_stack_1->GetYaxis()->SetLabelFont(42);
   hs_stack_1->GetYaxis()->SetLabelSize(0.035);
   hs_stack_1->GetYaxis()->SetTitleSize(0.035);
   hs_stack_1->GetYaxis()->SetTitleOffset(0);
   hs_stack_1->GetYaxis()->SetTitleFont(42);
   hs_stack_1->GetZaxis()->SetLabelFont(42);
   hs_stack_1->GetZaxis()->SetLabelSize(0.035);
   hs_stack_1->GetZaxis()->SetTitleSize(0.035);
   hs_stack_1->GetZaxis()->SetTitleFont(42);
   hs->SetHistogram(hs_stack_1);
   
   
   TH1D *h_PureKaonSignalNuMuCCKaon_stack_1 = new TH1D("h_PureKaonSignalNuMuCCKaon_stack_1","",8,0,8);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(1,0.7889442);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(2,0.4094521);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(3,0.8089175);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(4,1.118503);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(5,1.458049);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(6,1.318236);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(7,0.7589843);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(8,0.3994654);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinContent(9,0.3195723);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(1,0.08876316);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(2,0.06394567);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(3,0.08987972);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(4,0.1056886);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(5,0.120669);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(6,0.1147377);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(7,0.08706147);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(8,0.06316103);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetBinError(9,0.05649294);
   h_PureKaonSignalNuMuCCKaon_stack_1->SetEntries(739);

   ci = TColor::GetColor("#00ff00");
   h_PureKaonSignalNuMuCCKaon_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaon_stack_1->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaon_stack_1->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaon_stack_1,"HIST");
   
   TH1D *h_PureKaonSignalNuMuCCKaonMultiPion_stack_2 = new TH1D("h_PureKaonSignalNuMuCCKaonMultiPion_stack_2","",8,0,8);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(1,2.396793);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(2,0.9187705);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(3,1.807581);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(4,2.736338);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(5,2.786271);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(6,2.1671);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(7,1.897461);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(8,1.12849);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinContent(9,1.268303);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(1,0.1547123);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(2,0.09578845);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(3,0.1343564);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(4,0.1653082);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(5,0.1668097);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(6,0.1471123);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(7,0.1376563);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(8,0.1061594);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetBinError(9,0.1125437);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetEntries(1713);

   ci = TColor::GetColor("#00cc00");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonMultiPion_stack_2->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaonMultiPion_stack_2,"HIST");
   
   TH1D *h_PureKaonSignalNuMuCCKaonHyperon_stack_3 = new TH1D("h_PureKaonSignalNuMuCCKaonHyperon_stack_3","",8,0,8);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(1,2.766298);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(2,1.21837);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(3,3.17575);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(4,5.203037);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(5,6.281594);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(6,4.36416);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(7,2.526619);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(8,0.8987972);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinContent(9,0.5392783);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(1,0.1662107);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(2,0.110306);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(3,0.1780872);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(4,0.2279492);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(5,0.2504636);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(6,0.2087661);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(7,0.1588472);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(8,0.09474155);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetBinError(9,0.07338649);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetEntries(2701);

   ci = TColor::GetColor("#009900");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperon_stack_3->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaonHyperon_stack_3,"HIST");
   
   TH1D *h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4 = new TH1D("h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4","",8,0,8);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(1,7.130458);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(2,3.495323);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(3,7.549897);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(4,11.53456);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(5,12.15374);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(6,10.33617);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(7,6.750966);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(8,3.32555);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinContent(9,2.526619);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(1,0.2668507);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(2,0.1868328);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(3,0.2745871);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(4,0.3393987);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(5,0.3483891);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(6,0.3212842);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(7,0.2596525);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(8,0.182239);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetBinError(9,0.1588472);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetEntries(6489);

   ci = TColor::GetColor("#006600");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->SetLineColor(ci);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetXaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitleOffset(0);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetYaxis()->SetTitleFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetLabelFont(42);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonSignalNuMuCCKaonHyperonMultiPion_stack_4,"HIST");
   
   TH1D *h_PureKaonOtherNuMuCC_stack_5 = new TH1D("h_PureKaonOtherNuMuCC_stack_5","",8,0,8);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(1,14.07117);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(2,12.24362);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(3,21.49124);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(4,24.34742);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(5,19.18433);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(6,11.55454);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(7,5.962022);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(8,2.566565);
   h_PureKaonOtherNuMuCC_stack_5->SetBinContent(9,1.597862);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(1,0.3748648);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(2,0.3496749);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(3,0.4632766);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(4,0.4931012);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(5,0.4377064);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(6,0.3396924);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(7,0.2440093);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(8,0.160098);
   h_PureKaonOtherNuMuCC_stack_5->SetBinError(9,0.1263221);
   h_PureKaonOtherNuMuCC_stack_5->SetEntries(11317);
   h_PureKaonOtherNuMuCC_stack_5->SetFillColor(30);

   ci = TColor::GetColor("#000099");
   h_PureKaonOtherNuMuCC_stack_5->SetLineColor(ci);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetLabelFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetXaxis()->SetTitleFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetLabelFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitleOffset(0);
   h_PureKaonOtherNuMuCC_stack_5->GetYaxis()->SetTitleFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetLabelFont(42);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonOtherNuMuCC_stack_5->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonOtherNuMuCC_stack_5,"HIST");
   
   TH1D *h_PureKaonNuECC_stack_6 = new TH1D("h_PureKaonNuECC_stack_6","",8,0,8);
   h_PureKaonNuECC_stack_6->SetBinContent(1,0.9687037);
   h_PureKaonNuECC_stack_6->SetBinContent(2,1.018637);
   h_PureKaonNuECC_stack_6->SetBinContent(3,1.687741);
   h_PureKaonNuECC_stack_6->SetBinContent(4,1.168436);
   h_PureKaonNuECC_stack_6->SetBinContent(5,0.6691046);
   h_PureKaonNuECC_stack_6->SetBinContent(6,0.4893452);
   h_PureKaonNuECC_stack_6->SetBinContent(7,0.1797594);
   h_PureKaonNuECC_stack_6->SetBinContent(8,0.09986636);
   h_PureKaonNuECC_stack_6->SetBinContent(9,0.02995991);
   h_PureKaonNuECC_stack_6->SetBinError(1,0.09835696);
   h_PureKaonNuECC_stack_6->SetBinError(2,0.1008601);
   h_PureKaonNuECC_stack_6->SetBinError(3,0.1298263);
   h_PureKaonNuECC_stack_6->SetBinError(4,0.108022);
   h_PureKaonNuECC_stack_6->SetBinError(5,0.08174414);
   h_PureKaonNuECC_stack_6->SetBinError(6,0.06990645);
   h_PureKaonNuECC_stack_6->SetBinError(7,0.04236971);
   h_PureKaonNuECC_stack_6->SetBinError(8,0.03158052);
   h_PureKaonNuECC_stack_6->SetBinError(9,0.01729736);
   h_PureKaonNuECC_stack_6->SetEntries(632);

   ci = TColor::GetColor("#cc33ff");
   h_PureKaonNuECC_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonNuECC_stack_6->SetLineColor(ci);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonNuECC_stack_6->GetXaxis()->SetLabelFont(42);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonNuECC_stack_6->GetXaxis()->SetTitleFont(42);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonNuECC_stack_6->GetYaxis()->SetLabelFont(42);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitleOffset(0);
   h_PureKaonNuECC_stack_6->GetYaxis()->SetTitleFont(42);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetLabelFont(42);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonNuECC_stack_6->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonNuECC_stack_6,"HIST");
   
   TH1D *h_PureKaonNC_stack_7 = new TH1D("h_PureKaonNC_stack_7","",8,0,8);
   h_PureKaonNC_stack_7->SetBinContent(1,20.18299);
   h_PureKaonNC_stack_7->SetBinContent(2,17.94598);
   h_PureKaonNC_stack_7->SetBinContent(3,24.14769);
   h_PureKaonNC_stack_7->SetBinContent(4,22.01055);
   h_PureKaonNC_stack_7->SetBinContent(5,16.53787);
   h_PureKaonNC_stack_7->SetBinContent(6,8.908079);
   h_PureKaonNC_stack_7->SetBinContent(7,4.39412);
   h_PureKaonNC_stack_7->SetBinContent(8,1.827554);
   h_PureKaonNC_stack_7->SetBinContent(9,0.958717);
   h_PureKaonNC_stack_7->SetBinError(1,0.4489545);
   h_PureKaonNC_stack_7->SetBinError(2,0.4233438);
   h_PureKaonNC_stack_7->SetBinError(3,0.4910745);
   h_PureKaonNC_stack_7->SetBinError(4,0.4688404);
   h_PureKaonNC_stack_7->SetBinError(5,0.406396);
   h_PureKaonNC_stack_7->SetBinError(6,0.2982646);
   h_PureKaonNC_stack_7->SetBinError(7,0.2094814);
   h_PureKaonNC_stack_7->SetBinError(8,0.1350967);
   h_PureKaonNC_stack_7->SetBinError(9,0.09784865);
   h_PureKaonNC_stack_7->SetEntries(11707);

   ci = TColor::GetColor("#ffcc00");
   h_PureKaonNC_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonNC_stack_7->SetLineColor(ci);
   h_PureKaonNC_stack_7->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonNC_stack_7->GetXaxis()->SetLabelFont(42);
   h_PureKaonNC_stack_7->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonNC_stack_7->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonNC_stack_7->GetXaxis()->SetTitleFont(42);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonNC_stack_7->GetYaxis()->SetLabelFont(42);
   h_PureKaonNC_stack_7->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitleOffset(0);
   h_PureKaonNC_stack_7->GetYaxis()->SetTitleFont(42);
   h_PureKaonNC_stack_7->GetZaxis()->SetLabelFont(42);
   h_PureKaonNC_stack_7->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonNC_stack_7->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonNC_stack_7->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonNC_stack_7,"HIST");
   
   TH1D *h_PureKaonOutOfFV_stack_8 = new TH1D("h_PureKaonOutOfFV_stack_8","",8,0,8);
   h_PureKaonOutOfFV_stack_8->SetBinContent(1,489.1854);
   h_PureKaonOutOfFV_stack_8->SetBinContent(2,137.9654);
   h_PureKaonOutOfFV_stack_8->SetBinContent(3,98.64799);
   h_PureKaonOutOfFV_stack_8->SetBinContent(4,58.42182);
   h_PureKaonOutOfFV_stack_8->SetBinContent(5,35.7921);
   h_PureKaonOutOfFV_stack_8->SetBinContent(6,19.10443);
   h_PureKaonOutOfFV_stack_8->SetBinContent(7,9.117799);
   h_PureKaonOutOfFV_stack_8->SetBinContent(8,4.194387);
   h_PureKaonOutOfFV_stack_8->SetBinContent(9,2.656445);
   h_PureKaonOutOfFV_stack_8->SetBinError(1,2.210275);
   h_PureKaonOutOfFV_stack_8->SetBinError(2,1.173801);
   h_PureKaonOutOfFV_stack_8->SetBinError(3,0.992553);
   h_PureKaonOutOfFV_stack_8->SetBinError(4,0.7638308);
   h_PureKaonOutOfFV_stack_8->SetBinError(5,0.5978651);
   h_PureKaonOutOfFV_stack_8->SetBinError(6,0.436794);
   h_PureKaonOutOfFV_stack_8->SetBinError(7,0.3017551);
   h_PureKaonOutOfFV_stack_8->SetBinError(8,0.2046651);
   h_PureKaonOutOfFV_stack_8->SetBinError(9,0.1628771);
   h_PureKaonOutOfFV_stack_8->SetEntries(85623);

   ci = TColor::GetColor("#cccccc");
   h_PureKaonOutOfFV_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   h_PureKaonOutOfFV_stack_8->SetLineColor(ci);
   h_PureKaonOutOfFV_stack_8->GetXaxis()->SetTitle("Track Multiplicity");
   h_PureKaonOutOfFV_stack_8->GetXaxis()->SetLabelFont(42);
   h_PureKaonOutOfFV_stack_8->GetXaxis()->SetLabelSize(0.035);
   h_PureKaonOutOfFV_stack_8->GetXaxis()->SetTitleSize(0.035);
   h_PureKaonOutOfFV_stack_8->GetXaxis()->SetTitleFont(42);
   h_PureKaonOutOfFV_stack_8->GetYaxis()->SetTitle(" Events/bin");
   h_PureKaonOutOfFV_stack_8->GetYaxis()->SetLabelFont(42);
   h_PureKaonOutOfFV_stack_8->GetYaxis()->SetLabelSize(0.035);
   h_PureKaonOutOfFV_stack_8->GetYaxis()->SetTitleSize(0.035);
   h_PureKaonOutOfFV_stack_8->GetYaxis()->SetTitleOffset(0);
   h_PureKaonOutOfFV_stack_8->GetYaxis()->SetTitleFont(42);
   h_PureKaonOutOfFV_stack_8->GetZaxis()->SetLabelFont(42);
   h_PureKaonOutOfFV_stack_8->GetZaxis()->SetLabelSize(0.035);
   h_PureKaonOutOfFV_stack_8->GetZaxis()->SetTitleSize(0.035);
   h_PureKaonOutOfFV_stack_8->GetZaxis()->SetTitleFont(42);
   hs->Add(h_PureKaonOutOfFV_stack_8,"HIST");
   hs->Draw("hist same");
   
   TH1D *h_errors__2 = new TH1D("h_errors__2","",8,0,8);
   h_errors__2->SetBinContent(1,537.4907);
   h_errors__2->SetBinContent(2,175.2155);
   h_errors__2->SetBinContent(3,159.3168);
   h_errors__2->SetBinContent(4,126.5407);
   h_errors__2->SetBinContent(5,94.86305);
   h_errors__2->SetBinContent(6,58.24206);
   h_errors__2->SetBinContent(7,31.58773);
   h_errors__2->SetBinContent(8,14.44068);
   h_errors__2->SetBinContent(9,9.896756);
   h_errors__2->SetBinError(1,2.316835);
   h_errors__2->SetBinError(2,1.322805);
   h_errors__2->SetBinError(3,1.261364);
   h_errors__2->SetBinError(4,1.124151);
   h_errors__2->SetBinError(5,0.9733256);
   h_errors__2->SetBinError(6,0.7626547);
   h_errors__2->SetBinError(7,0.5616539);
   h_errors__2->SetBinError(8,0.3797549);
   h_errors__2->SetBinError(9,0.3143808);
   h_errors__2->SetMinimum(0);
   h_errors__2->SetMaximum(674.7595);
   h_errors__2->SetEntries(120921);
   h_errors__2->SetStats(0);
   h_errors__2->SetFillColor(1);
   h_errors__2->SetFillStyle(3253);

   ci = TColor::GetColor("#000099");
   h_errors__2->SetLineColor(ci);
   h_errors__2->GetXaxis()->SetTitle("Track Multiplicity");
   h_errors__2->GetXaxis()->SetLabelFont(42);
   h_errors__2->GetXaxis()->SetLabelSize(0.045);
   h_errors__2->GetXaxis()->SetTitleSize(0.05);
   h_errors__2->GetXaxis()->SetTitleOffset(0.93);
   h_errors__2->GetXaxis()->SetTitleFont(42);
   h_errors__2->GetYaxis()->SetTitle(" Events/bin");
   h_errors__2->GetYaxis()->SetLabelFont(42);
   h_errors__2->GetYaxis()->SetLabelSize(0.045);
   h_errors__2->GetYaxis()->SetTitleSize(0.05);
   h_errors__2->GetYaxis()->SetTitleOffset(1.06);
   h_errors__2->GetYaxis()->SetTitleFont(42);
   h_errors__2->GetZaxis()->SetLabelFont(42);
   h_errors__2->GetZaxis()->SetLabelSize(0.035);
   h_errors__2->GetZaxis()->SetTitleSize(0.035);
   h_errors__2->GetZaxis()->SetTitleFont(42);
   h_errors__2->Draw("E2 same");
   
   TH1D *h_errors_copy__3 = new TH1D("h_errors_copy__3","",8,0,8);
   h_errors_copy__3->SetBinContent(1,537.4907);
   h_errors_copy__3->SetBinContent(2,175.2155);
   h_errors_copy__3->SetBinContent(3,159.3168);
   h_errors_copy__3->SetBinContent(4,126.5407);
   h_errors_copy__3->SetBinContent(5,94.86305);
   h_errors_copy__3->SetBinContent(6,58.24206);
   h_errors_copy__3->SetBinContent(7,31.58773);
   h_errors_copy__3->SetBinContent(8,14.44068);
   h_errors_copy__3->SetBinContent(9,9.896756);
   h_errors_copy__3->SetBinError(1,2.316835);
   h_errors_copy__3->SetBinError(2,1.322805);
   h_errors_copy__3->SetBinError(3,1.261364);
   h_errors_copy__3->SetBinError(4,1.124151);
   h_errors_copy__3->SetBinError(5,0.9733256);
   h_errors_copy__3->SetBinError(6,0.7626547);
   h_errors_copy__3->SetBinError(7,0.5616539);
   h_errors_copy__3->SetBinError(8,0.3797549);
   h_errors_copy__3->SetBinError(9,0.3143808);
   h_errors_copy__3->SetMinimum(0);
   h_errors_copy__3->SetMaximum(674.7595);
   h_errors_copy__3->SetEntries(120921);
   h_errors_copy__3->SetDirectory(0);
   h_errors_copy__3->SetStats(0);
   h_errors_copy__3->SetFillColor(1);
   h_errors_copy__3->SetFillStyle(3253);

   ci = TColor::GetColor("#000099");
   h_errors_copy__3->SetLineColor(ci);
   h_errors_copy__3->GetXaxis()->SetTitle("Track Multiplicity");
   h_errors_copy__3->GetXaxis()->SetLabelFont(42);
   h_errors_copy__3->GetXaxis()->SetLabelSize(0.045);
   h_errors_copy__3->GetXaxis()->SetTitleSize(0.05);
   h_errors_copy__3->GetXaxis()->SetTitleOffset(0.93);
   h_errors_copy__3->GetXaxis()->SetTitleFont(42);
   h_errors_copy__3->GetYaxis()->SetTitle(" Events/bin");
   h_errors_copy__3->GetYaxis()->SetLabelFont(42);
   h_errors_copy__3->GetYaxis()->SetLabelSize(0.045);
   h_errors_copy__3->GetYaxis()->SetTitleSize(0.05);
   h_errors_copy__3->GetYaxis()->SetTitleOffset(1.06);
   h_errors_copy__3->GetYaxis()->SetTitleFont(42);
   h_errors_copy__3->GetZaxis()->SetLabelFont(42);
   h_errors_copy__3->GetZaxis()->SetLabelSize(0.035);
   h_errors_copy__3->GetZaxis()->SetTitleSize(0.035);
   h_errors_copy__3->GetZaxis()->SetTitleFont(42);
   h_errors_copy__3->Draw("sameaxis");
   
   leg = new TLegend(0.54,0.815,0.885,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(32);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("NULL","NuMI RHC, 1.5 #times 10^{21} POT","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   leg = new TLegend(0.45,0.9,0.89,0.985,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(32);
   leg->SetTextFont(62);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("NULL","MicroBooNE Simulation, Preliminary","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   p_plot->Modified();
   c->cd();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
